import type { LessonVideoScript } from "../../types";

export const M_CIRCLES: LessonVideoScript[] = [
  {
    subskillId: "m-circles",
    pattern: "The Circle Equation (Center-Radius Form)",
    example: 1,
    hook: "A circle's equation is its address and its size, written in one line. You just have to read the signs right.",
    idea: [
      { point: "(x − h)² + (y − k)² = r²", say: "The center is h comma k, and the radius is r. The template subtracts h and k, and squares r." },
      { point: "Subtracting a negative = adding", say: "So a negative coordinate shows up with a plus sign. And the right side is the radius squared, not the radius." },
    ],
    steps: [
      {
        say: "Start from the template, with h and k being subtracted.",
        work: "(x − h)² + (y − k)² = r²",
        note: "center-radius form",
        focus: ["circ", "cen"],
      },
      {
        say: "The center is negative four comma one, and the radius is six, all the way around. Drop them in exactly as they are.",
        highlight: ["center (-4, 1)", "radius 6"],
        work: "(x − (−4))² + (y − 1)² = 6²",
        note: "h = −4, k = 1, r = 6",
        move: [{ id: "rad", turn: -360, about: "C" }],
        focus: ["cen", "rad", "circ"],
      },
      {
        say: "Minus negative four becomes plus four. The center sits four to the left of the axis. And six squared is thirty-six.",
        work: "(x + 4)² + (y − 1)² = 36",
        note: "clean up signs",
        draw: ["four"],
        focus: ["four", "cen", "rad"],
      },
      {
        say: "The second choice flips both signs, like the template adds. The fourth flips only the y sign.",
        strike: [1, 3],
        focus: ["cen"],
      },
      {
        say: "And the third puts six on the right. That's the radius, but the equation needs it squared.",
        strike: [2],
        focus: ["rad"],
      },
    ],
    answer: "X plus four, squared, plus y minus one, squared, equals thirty-six.",
    trap: { point: "Trap: keeping the center's sign", say: "The equation subtracts the center. So a center at negative four shows up as x plus four." },
    recap: { point: "Flip the center's signs, square r", say: "Write each center coordinate with the opposite sign in the parentheses, and square the radius on the right." },
    tint: { "4": "yellow", "1": "yellow", "6": "green", "36": "green" },
    scene: {
      x: [-12, 4],
      y: [-5.6, 7.6],
      pts: { C: [-4, 1] },
      objects: [
        { id: "xAx", kind: "seg", from: [-11.5, 0], to: [3.5, 0], color: "gray" },
        { id: "yAx", kind: "seg", from: [0, -5.4], to: [0, 7.4], color: "gray" },
        { id: "circ", kind: "circle", c: "C", r: 6 },
        { id: "rad", kind: "seg", from: "C", to: [-4, 7], color: "green", label: "6" },
        { id: "cen", kind: "point", at: "C", color: "yellow", label: "(−4, 1)", labelOffset: [-60, 26] },
        { id: "four", kind: "seg", from: "C", to: [0, 1], color: "yellow", dash: true, label: "4", labelOffset: [4, 0] },
      ],
    },
  },
  {
    subskillId: "m-circles",
    pattern: "Arc Length and Sector Area as Fractions of the Whole Circle",
    example: 1,
    hook: "An arc is just a slice of the circle's edge. Figure out how big a slice.",
    idea: [
      { point: "Fraction = angle / 360°", say: "The central angle over three sixty tells you what fraction of the circle you've got." },
      { point: "Arc: × 2πr. Sector: × πr²", say: "For arc length, take that fraction of the circumference. For sector area, take it of the whole area." },
    ],
    steps: [
      {
        say: "The central angle is one hundred twenty degrees. Three copies of that slice fill the whole circle, so it's one third.",
        highlight: ["central angle of 120°"],
        work: "120/360 = 1/3",
        note: "fraction of circle",
        draw: ["sec1", "sec2", "sec3"],
        move: [
          { id: "sec2", turn: 120, about: "O" },
          { id: "sec3", turn: 240, about: "O" },
        ],
        focus: ["sec1", "sec2", "sec3", "ang"],
      },
      {
        say: "It's asking for arc length, so we need the circumference. Two pi times nine is eighteen pi.",
        highlight: ["radius 9", "arc length"],
        work: "C = 2π(9) = 18π",
        note: "whole circumference",
        hide: ["sec2", "sec3"],
        move: [{ id: "rad1", turn: 360, about: "O" }],
        focus: ["circ", "rad1"],
      },
      {
        say: "Take one third of eighteen pi. Six pi.",
        work: "arc = (1/3)(18π) = 6π",
        note: "fraction × whole",
        draw: ["arc", "t6"],
        focus: ["arc", "t6", "sec1"],
      },
      {
        say: "Eighteen pi is the whole circumference, and nine pi is half. We only want a third.",
        strike: [1, 2],
        focus: ["circ"],
      },
      {
        say: "Two pi is a slip. A third of eighteen pi is six pi, not two.",
        strike: [3],
        focus: ["arc"],
      },
    ],
    answer: "Six pi. One third of the way around a circle whose edge is eighteen pi.",
    trap: { point: "Trap: skipping the fraction", say: "Turn the angle into a fraction of three sixty first. Otherwise you're working with the whole circle." },
    recap: { point: "Angle over 360°, times the whole", say: "Arc length and sector area are the same move. Find the fraction, then apply it to the circumference or area." },
    tint: { "120": "blue", "1/3": "blue", "9": "yellow", "6π": "green" },
    scene: {
      x: [-15, 15],
      y: [-10.2, 10.2],
      pts: { O: [0, 0], P: [-4.5, 7.794] },
      objects: [
        { id: "circ", kind: "circle", c: "O", r: 9 },
        { id: "rad2", kind: "seg", from: "O", to: "P" },
        { id: "rad1", kind: "seg", from: "O", to: [9, 0], color: "yellow", label: "9", labelOffset: [0, 26] },
        { id: "ang", kind: "angle", at: "O", from: [9, 0], to: "P", r: 22, color: "blue", label: "120°", labelOffset: [6, -2] },
        { id: "sec1", kind: "poly", pts: [[0, 0], [9.0, 0.0], [8.863, 1.563], [8.457, 3.078], [7.794, 4.5], [6.894, 5.785], [5.785, 6.894], [4.5, 7.794], [3.078, 8.457], [1.563, 8.863], [0.0, 9.0], [-1.563, 8.863], [-3.078, 8.457], [-4.5, 7.794]], color: "blue", fill: true },
        { id: "sec2", kind: "poly", pts: [[0, 0], [9.0, 0.0], [8.863, 1.563], [8.457, 3.078], [7.794, 4.5], [6.894, 5.785], [5.785, 6.894], [4.5, 7.794], [3.078, 8.457], [1.563, 8.863], [0.0, 9.0], [-1.563, 8.863], [-3.078, 8.457], [-4.5, 7.794]], color: "blue", fill: true },
        { id: "sec3", kind: "poly", pts: [[0, 0], [9.0, 0.0], [8.863, 1.563], [8.457, 3.078], [7.794, 4.5], [6.894, 5.785], [5.785, 6.894], [4.5, 7.794], [3.078, 8.457], [1.563, 8.863], [0.0, 9.0], [-1.563, 8.863], [-3.078, 8.457], [-4.5, 7.794]], color: "blue", fill: true },
        { id: "arc", kind: "poly", open: true, pts: [[9.0, 0.0], [8.863, 1.563], [8.457, 3.078], [7.794, 4.5], [6.894, 5.785], [5.785, 6.894], [4.5, 7.794], [3.078, 8.457], [1.563, 8.863], [0.0, 9.0], [-1.563, 8.863], [-3.078, 8.457], [-4.5, 7.794]], color: "green" },
        { id: "t6", kind: "text", at: [7.6, 7.4], text: "6π", color: "green", size: 17 },
      ],
    },
  },
  {
    subskillId: "m-circles",
    pattern: "Solving the Circle Equation for a Coordinate's Possible Values",
    example: 2,
    hook: "Draw a vertical line through a circle and it usually hits twice. So expect two answers.",
    idea: [
      { point: "Plug in the known coordinate", say: "Put the coordinate you know into its spot in the equation, then solve for the other one." },
      { point: "Square root gives ±", say: "When you undo a square, there's a positive root and a negative root. Keep both." },
    ],
    steps: [
      {
        say: "X is five, so put five in for x. That's this vertical line.",
        highlight: ["x=5"],
        work: "(5 + 1)² + (y − 4)² = 40",
        note: "plug in x = 5",
        draw: ["vline"],
        focus: ["vline", "circ"],
      },
      {
        say: "Five plus one is six: the line is six to the right of the center. Six squared is thirty-six.",
        work: "36 + (y − 4)² = 40",
        note: "simplify",
        draw: ["leg6"],
        focus: ["leg6", "cen"],
      },
      {
        say: "Subtract thirty-six from both sides. Of the radius squared, forty, four is left for the up-and-down part.",
        work: "(y − 4)² = 4",
        note: "−36 both sides",
        draw: ["rad"],
        focus: ["rad", "leg6"],
      },
      {
        say: "Take the square root. Y minus four could be two or negative two: up two, or down two.",
        work: "y − 4 = ±2",
        note: "± square root",
        draw: ["up", "down"],
        focus: ["up", "down"],
      },
      {
        say: "Add four to both. Y is six or two, one point above the center and one below.",
        work: "y = 6 or y = 2",
        note: "+4 both sides",
        draw: ["P1", "P2"],
        focus: ["P1", "P2", "vline"],
      },
      {
        say: "Eight or zero doesn't check. Six only drops the negative root. And negative six or negative two is a sign slip.",
        strike: [1, 2, 3],
        focus: ["P1", "P2"],
      },
    ],
    answer: "Y equals six or y equals two. One point above the center, one below.",
    trap: { point: "Trap: forgetting the negative root", say: "Something squared equals four has two answers, two and negative two. Dropping one loses a point on the circle." },
    recap: { point: "Substitute, isolate the square, take ±", say: "Plug in what you know, get the squared piece alone, and take both square roots." },
    tint: { "5": "blue", "36": "yellow", "2": "green", y: "green" },
    scene: {
      // Center (−1, 4), radius √40 = 6.32; x = 5 meets it at y = 6 and y = 2.
      x: [-10.5, 10.5],
      y: [-3.2, 11.2],
      pts: { C: [-1, 4], M: [5, 4] },
      objects: [
        { id: "xAx", kind: "seg", from: [-8.5, 0], to: [8.5, 0], color: "gray" },
        { id: "yAx", kind: "seg", from: [0, -3], to: [0, 11], color: "gray" },
        { id: "circ", kind: "circle", c: "C", r: 6.325 },
        { id: "cen", kind: "point", at: "C", color: "white" },
        { id: "vline", kind: "line", through: [[5, 0], [5, 1]], dash: true, color: "blue", label: "x = 5", labelOffset: [46, 14] },
        { id: "leg6", kind: "seg", from: "C", to: "M", color: "yellow", label: "6", labelOffset: [0, 26] },
        { id: "rad", kind: "seg", from: "C", to: [5, 6], color: "gray", label: "√40", labelOffset: [-6, 0] },
        { id: "up", kind: "seg", from: "M", to: [5, 6], color: "green", width: 4, label: "+2", labelOffset: [34, 0] },
        { id: "down", kind: "seg", from: "M", to: [5, 2], color: "green", width: 4, label: "−2", labelOffset: [34, 0] },
        { id: "P1", kind: "point", at: [5, 6], color: "green" },
        { id: "P2", kind: "point", at: [5, 2], color: "green" },
      ],
    },
  },
  {
    subskillId: "m-circles",
    pattern: "Circle Theorems: Central Angles, Arcs, and Tangent Lines",
    example: 2,
    hook: "A tangent line hides a right angle. Find it, and you've got a right triangle.",
    idea: [
      { point: "Radius ⊥ tangent", say: "A radius drawn to the point where a tangent touches always meets it at ninety degrees." },
      { point: "Then use a² + b² = c²", say: "That right angle means the Pythagorean theorem works. Just figure out which side is the hypotenuse first." },
    ],
    steps: [
      {
        say: "P Q touches the circle at Q, and O Q is a radius. So the angle at Q is a right angle.",
        highlight: ["tangent to a circle at point Q"],
        work: "OQ ⊥ PQ",
        note: "radius ⊥ tangent",
        draw: ["right"],
        focus: ["right", "OQ", "PQ"],
      },
      {
        say: "The side across from that right angle is O P, thirteen. That's the hypotenuse.",
        highlight: ["OQ = 5", "OP = 13"],
        work: "5² + PQ² = 13²",
        note: "OP is hypotenuse",
        focus: ["OQ", "PQ", "OP", "right"],
      },
      {
        say: "One hundred sixty-nine minus twenty-five is one hundred forty-four.",
        work: "PQ² = 169 − 25 = 144",
        note: "subtract squares",
        focus: ["PQ", "OP", "OQ"],
      },
      {
        say: "Take the square root. P Q is twelve.",
        work: "PQ = 12",
        note: "√ both sides",
        hide: ["PQ"],
        draw: ["PQ12"],
        focus: ["PQ12"],
      },
      {
        say: "Eighteen and eight just add or subtract the lengths. The square root of one hundred ninety-four adds the squares, but O P is the hypotenuse.",
        strike: [1, 2, 3],
        focus: ["OP"],
      },
    ],
    answer: "Twelve. A five, twelve, thirteen right triangle, hiding inside a circle.",
    trap: { point: "Trap: missing the right angle", say: "Nothing in the question says right angle. The tangent says it for you." },
    recap: { point: "Tangent → right angle → Pythagoras", say: "Draw the radius to the point of tangency, mark the right angle, and solve the triangle." },
    tint: { "5": "blue", "25": "blue", "13": "green", "169": "green", PQ: "yellow", "144": "yellow", "12": "yellow" },
    scene: {
      // Radius 5 to Q at the top; the tangent at Q is horizontal, so P = (12, 5) and OP = 13.
      x: [-6.5, 14.5],
      y: [-6, 7.6],
      pts: { O: [0, 0], Q: [0, 5], P: [12, 5] },
      objects: [
        { id: "circ", kind: "circle", c: "O", r: 5 },
        { id: "tan", kind: "line", through: ["Q", "P"], color: "gray", dash: true },
        { id: "OQ", kind: "seg", from: "O", to: "Q", color: "blue", label: "5" },
        { id: "PQ", kind: "seg", from: "Q", to: "P", color: "yellow", label: "?" },
        { id: "OP", kind: "seg", from: "O", to: "P", color: "green", label: "13", labelOffset: [10, 24] },
        { id: "lO", kind: "text", at: [-0.9, -1.4], text: "O" },
        { id: "lQ", kind: "text", at: [-0.9, 5.5], text: "Q" },
        { id: "lP", kind: "text", at: [12.9, 5.5], text: "P" },
        { id: "right", kind: "angle", at: "Q", from: "O", to: "P", right: true, color: "white" },
        { id: "PQ12", kind: "seg", from: "Q", to: "P", color: "yellow", label: "12" },
      ],
    },
  },
  {
    subskillId: "m-circles",
    pattern: "Inscribed Figures and Radii as Equal Sides",
    example: 2,
    hook: "Any segment from the center to the circle is a radius. That gives you free sides.",
    idea: [
      { point: "Every radius is the same length", say: "A triangle with one corner at the center and two on the circle has two radii for sides. They're equal." },
      { point: "Count both radii", say: "So when a problem gives you one radius, you actually know two sides." },
    ],
    steps: [
      {
        say: "O is the center, and P and Q are on the circle. So O P and O Q are both radii, nine each.",
        highlight: ["radius of the circle is 9"],
        work: "OP = OQ = 9",
        note: "both are radii",
        draw: ["OQ9"],
        focus: ["OP", "OQ9"],
      },
      {
        say: "The perimeter adds all three sides. Lay them end to end: nine plus nine plus P Q makes thirty-four.",
        highlight: ["perimeter of triangle OPQ is 34"],
        work: "9 + 9 + PQ = 34",
        note: "perimeter",
        draw: ["bar", "cOP", "cOQ"],
        move: [
          { id: "cOP", by: [-8.5, -9.938], turn: -27.27 },
          { id: "cOQ", by: [-7.5, -9.938], turn: 27.27 },
        ],
        focus: ["bar", "cOP", "cOQ"],
      },
      {
        say: "Subtract eighteen from both sides. The chord fills the rest of the bar exactly: P Q is sixteen.",
        work: "PQ = 34 − 18 = 16",
        note: "−18 both sides",
        draw: ["cPQ"],
        move: [{ id: "cPQ", by: [9, -7.877] }],
        focus: ["cPQ", "PQ", "bar", "cOP", "cOQ"],
      },
      {
        say: "Twenty-five subtracts only one radius. Nine assumes the chord equals the radius, which only happens at sixty degrees.",
        strike: [0, 1],
        focus: ["OP", "OQ9"],
      },
      {
        say: "And eighteen is the diameter. This chord misses the center, so it's shorter.",
        strike: [2],
        draw: ["diam"],
        focus: ["diam", "PQ"],
      },
    ],
    answer: "Sixteen. Thirty-four minus both radii.",
    trap: { point: "Trap: counting only one radius", say: "The problem mentions the radius once, but the triangle uses it twice. Subtract both." },
    recap: { point: "Spot the radii, then use them", say: "Look for sides that run from the center to the circle. They're radii, so they're equal." },
    tint: { "9": "yellow", PQ: "blue", "16": "blue" },
    scene: {
      // The figure's own points: OP = OQ = 9, PQ = 16. Below, a bar 34 long
      // (the perimeter) that the three sides fill end to end.
      x: [-18, 18],
      y: [-15, 10.6],
      pts: { O: [0, 0], P: [-8, -4.1231], Q: [8, -4.1231] },
      objects: [
        { id: "circ", kind: "circle", c: "O", r: 9 },
        { id: "OP", kind: "seg", from: "O", to: "P", color: "yellow", label: "9" },
        { id: "OQ", kind: "seg", from: "O", to: "Q" },
        { id: "PQ", kind: "seg", from: "P", to: "Q", color: "blue", label: "?", labelOffset: [0, 28] },
        { id: "lO", kind: "text", at: [0, 1.4], text: "O" },
        { id: "lP", kind: "text", at: [-9.6, -6.2], text: "P" },
        { id: "lQ", kind: "text", at: [9.6, -6.2], text: "Q" },
        { id: "OQ9", kind: "seg", from: "O", to: "Q", color: "yellow", label: "9" },
        { id: "bar", kind: "seg", from: [-17, -12], to: [17, -12], color: "gray", label: "34", labelOffset: [0, 34] },
        { id: "cOP", kind: "seg", from: [-0.133, -0.069], to: [-7.867, -4.054], color: "yellow", width: 6 },
        { id: "cOQ", kind: "seg", from: [0.133, -0.069], to: [7.867, -4.054], color: "yellow", width: 6 },
        { id: "cPQ", kind: "seg", from: [-7.85, -4.1231], to: [7.85, -4.1231], color: "blue", width: 6, label: "16" },
        { id: "diam", kind: "seg", from: [-9, 0], to: [9, 0], color: "gray", dash: true, label: "18", labelOffset: [-44, 0] },
      ],
    },
  },
];
