import type { LessonVideoScript } from "../../types";

export const M_INFERENCE: LessonVideoScript[] = [
  {
    subskillId: "m-inference",
    pattern: "Interpreting Confidence Intervals Correctly",
    example: 4,
    hook: "A confidence interval is a range of believable answers. Not a promise, and not a prediction about individuals.",
    idea: [
      { point: "It's about the population mean", say: "The interval gives a plausible range for the true average of the whole population." },
      { point: "Not individuals, not a guarantee", say: "It doesn't say where individual data points fall, and it doesn't guarantee anything." },
      { point: "Inside = plausible; outside = questionable", say: "A claimed value inside the interval is plausible. One outside it isn't well supported." },
    ],
    steps: [
      {
        say: "The claim is twenty-seven minutes. The interval runs from twenty-four to thirty: the blue band of plausible means.",
        highlight: ["27 minutes", "(24, 30) minutes"],
        focus: ["ci", "claim"],
      },
      {
        say: "Is twenty-seven between twenty-four and thirty? Yes, it lands inside the band, so the data doesn't contradict the claim.",
        work: "24 < 27 < 30",
        note: "inside the interval",
        focus: ["claim", "ci"],
      },
      {
        say: "It doesn't have to sit in the exact center. Slide anywhere along the band, and that value is plausible too.",
        draw: ["probe"],
        set: [{ id: "probe", at: [29.4, 0] }],
        focus: ["ci", "probe"],
        strike: [1],
      },
      {
        say: "Since twenty-seven is inside, the data can't rule it out. But it doesn't prove it either, since other values are just as plausible.",
        focus: ["ci", "claim", "probe"],
        strike: [2, 3],
      },
    ],
    answer: "No contradiction. Twenty-seven is inside the interval, so it's a plausible value.",
    trap: { point: "Trap: treating it as proof", say: "An interval makes a value plausible or questionable. It never proves the mean is exactly one number." },
    recap: { point: "Check inside or outside, nothing more", say: "Ask whether the claimed value lands inside the range. Inside is plausible, outside is questionable." },
    tint: { "27": "yellow", "24": "blue", "30": "blue" },
    scene: {
      x: [21, 33],
      y: [-1.6, 3],
      objects: [
        { id: "nl", kind: "numline", y: 0, min: 22, max: 32, step: 2 },
        { id: "ci", kind: "seg", from: [24, 0], to: [30, 0], width: 10, color: "blue", label: "95% interval", labelOffset: [-40, -14] },
        { id: "claim", kind: "point", at: [27, 0], color: "yellow", label: "27", labelOffset: [6, -6] },
        { id: "probe", kind: "point", at: [24.6, 0], open: true, color: "white" },
      ],
    },
  },
  {
    subskillId: "m-inference",
    pattern: "Sample Size's Effect on Margin of Error",
    example: 4,
    hook: "Two knobs control how wide a confidence interval is, and they turn in opposite directions.",
    idea: [
      { point: "Bigger sample → narrower interval", say: "A bigger sample gives a smaller margin of error, so the interval gets narrower." },
      { point: "Higher confidence → wider interval", say: "A higher confidence level does the opposite. To be more sure, you need a wider range." },
    ],
    steps: [
      {
        say: "This study turns both knobs at once: bigger sample, and higher confidence level. Here's the interval before either change.",
        highlight: ["increases both its sample size and its confidence level"],
        focus: ["ci", "L", "R"],
      },
      {
        say: "The bigger sample on its own pushes the interval narrower. Blue arrows, pushing in.",
        work: "bigger n → narrower",
        note: "pushes in",
        draw: ["inL", "inR"],
        focus: ["inL", "inR", "ci"],
      },
      {
        say: "The higher confidence level on its own pushes it wider. Orange arrows, pushing out.",
        work: "higher confidence → wider",
        note: "pushes out",
        draw: ["outL", "outR"],
        focus: ["outL", "outR", "ci"],
      },
      {
        say: "Both at once means two pushes in opposite directions. Without their sizes, you can't tell which wins. The colleague ignored half the story.",
        work: "net width: unknown",
        note: "opposite pushes",
        draw: ["q"],
        focus: ["inL", "inR", "outL", "outR", "q"],
      },
      {
        say: "So the colleague isn't fully correct. And a higher confidence level widens an interval; it doesn't narrow it.",
        strike: [1, 2],
        focus: ["outL", "outR"],
      },
      {
        say: "Each change matters on its own. They don't need to happen at the same rate to have an effect.",
        strike: [3],
      },
    ],
    answer: "The reasoning is incomplete. The higher confidence level pushes the other way.",
    trap: { point: "Trap: mixing up the two knobs", say: "Bigger samples narrow the interval. Higher confidence widens it. Don't let one rule stand in for the other." },
    recap: { point: "Sample size in, confidence level out", say: "More data, narrower. More confidence, wider. If both change, check each one." },
    tint: { n: "blue", narrower: "blue", confidence: "orange", wider: "orange" },
    scene: {
      x: [-4.2, 8.2],
      y: [-1.15, 1.15],
      objects: [
        { id: "ci", kind: "seg", from: [0, 0], to: [4, 0], width: 7 },
        { id: "L", kind: "point", at: [0, 0] },
        { id: "R", kind: "point", at: [4, 0] },
        { id: "inL", kind: "seg", from: [-3.6, 0.7], to: [-0.5, 0.7], width: 3, arrow: true, color: "blue" },
        { id: "inR", kind: "seg", from: [7.6, 0.7], to: [4.5, 0.7], width: 3, arrow: true, color: "blue" },
        { id: "outL", kind: "seg", from: [-0.5, -0.7], to: [-3.6, -0.7], width: 3, arrow: true, color: "orange" },
        { id: "outR", kind: "seg", from: [4.5, -0.7], to: [7.6, -0.7], width: 3, arrow: true, color: "orange" },
        { id: "q", kind: "text", at: [2, 0.35], text: "?", size: 20, color: "yellow" },
      ],
    },
  },
  {
    subskillId: "m-inference",
    pattern: "Estimating a Population Count from a Sample Proportion",
    example: 2,
    hook: "A good random sample is a tiny model of the whole population. Scale it up.",
    idea: [
      { point: "Sample proportion = count / sample size", say: "First turn the sample's count into a proportion: the count over the sample size." },
      { point: "Then × the population", say: "Then apply that same proportion to the full population." },
      { point: "Only if the sample was random", say: "This only works if the sample was random. A self-selected sample can't stand in for everyone." },
    ],
    steps: [
      {
        say: "One seventy-five out of two fifty support the measure: the green part of the small sample bar. But the question asks who does not.",
        highlight: ["175 support a proposed measure", "do NOT support"],
        draw: ["sY"],
        focus: ["sY", "samp"],
      },
      {
        say: "The supporting proportion is one seventy-five over two fifty. That's zero point seven.",
        work: "175/250 = 0.7",
        note: "sample proportion",
        focus: ["sY", "samp"],
      },
      {
        say: "Everyone else doesn't support it: the orange slice. One minus zero point seven is zero point three.",
        work: "1 − 0.7 = 0.3",
        note: "the NOT group",
        draw: ["sN"],
        focus: ["sN"],
      },
      {
        say: "A random sample is a tiny model of the district, so stretch it to sixty thousand. Zero point three of that is eighteen thousand.",
        work: "0.3 × 60,000 = 18,000",
        note: "scale up",
        draw: ["c0", "c1", "c2", "pN"],
        focus: ["sN", "c1", "c2", "pN"],
      },
      {
        say: "Forty-two thousand is the green part, the supporters. And one seventy-five is the raw sample count.",
        draw: ["pY"],
        focus: ["pY"],
        strike: [1, 2],
      },
      {
        say: "Twelve thousand uses twenty percent. Non-supporters are seventy-five out of two fifty, which is thirty percent.",
        strike: [3],
      },
    ],
    answer: "Eighteen thousand. Thirty percent of the district doesn't support it.",
    trap: { point: "Trap: scaling up the wrong group", say: "Read the question twice. If it asks about who does not, use the other part of the sample." },
    recap: { point: "Proportion first, then scale up", say: "Turn the sample count into a proportion, check that it's the right group, then multiply by the population." },
    tint: { "175/250": "green", "0.7": "green", "0.3": "orange", "18,000": "orange" },
    scene: {
      x: [-1, 23],
      y: [-1.6, 12.6],
      objects: [
        { id: "samp", kind: "poly", pts: [[0, 9], [4, 9], [4, 11], [0, 11]] },
        { id: "tSamp", kind: "text", at: [9.2, 9.6], text: "sample of 250", size: 13 },
        { id: "pop", kind: "poly", pts: [[0, 1], [20, 1], [20, 5], [0, 5]] },
        { id: "tPop", kind: "text", at: [10, -0.9], text: "district of 60,000", size: 13 },
        { id: "sY", kind: "poly", pts: [[0, 9], [2.8, 9], [2.8, 11], [0, 11]], fill: true, color: "green", label: "175", labelOffset: [0, -22] },
        { id: "sN", kind: "poly", pts: [[2.8, 9], [4, 9], [4, 11], [2.8, 11]], fill: true, color: "orange", label: "75", labelOffset: [6, -22] },
        { id: "c0", kind: "seg", from: [0, 9], to: [0, 5], dash: true, color: "gray" },
        { id: "c1", kind: "seg", from: [2.8, 9], to: [14, 5], dash: true, color: "gray" },
        { id: "c2", kind: "seg", from: [4, 9], to: [20, 5], dash: true, color: "gray" },
        { id: "pN", kind: "poly", pts: [[14, 1], [20, 1], [20, 5], [14, 5]], fill: true, color: "orange", label: "18,000" },
        { id: "pY", kind: "poly", pts: [[0, 1], [14, 1], [14, 5], [0, 5]], fill: true, color: "green", label: "42,000" },
      ],
    },
  },
];
