import type { LessonVideoScript } from "../../types";

export const M_LINEAR_EQ_2VAR: LessonVideoScript[] = [
  {
    subskillId: "m-linear-eq-2var",
    pattern: "Reading Slope and Intercepts from Standard Form",
    example: 1,
    hook: "In standard form, the slope is hiding. The number in front of x is not it.",
    idea: [
      { point: "For slope, solve for y first", say: "Get y by itself. Once it's y equals m x plus b, the slope is just the number on x." },
      { point: "Intercepts: set x or y to 0", say: "For intercepts, skip the rearranging. Set y to zero for the x-intercept, and x to zero for the y-intercept." },
    ],
    steps: [
      {
        say: "Six x minus three y equals twelve. They want the slope, so we need y alone.",
        highlight: ["6x - 3y = 12"],
        work: "6x − 3y = 12",
        focus: ["line"],
      },
      {
        say: "Subtract six x from both sides. Negative three y equals negative six x plus twelve. Same line, new outfit.",
        work: "−3y = −6x + 12",
        note: "−6x both sides",
        focus: ["line"],
      },
      {
        say: "Divide every term by negative three. Negative six x over negative three is positive two x. So y equals two x minus four.",
        work: "y = 2x − 4",
        note: "÷(−3) both sides",
        draw: ["yi"],
        focus: ["line", "yi"],
      },
      {
        say: "Check it on the graph. From the y-intercept, go over two and up four. Rise over run is two.",
        work: "slope = 4/2 = 2",
        note: "rise over run",
        draw: ["run", "rise"],
        focus: ["run", "rise", "line"],
      },
      {
        say: "Negative two misses that two negatives make a positive. Six is the standard-form coefficient. Negative six forgets to divide by negative three.",
        strike: [1, 2, 3],
      },
    ],
    answer: "Two. Read it off once y is by itself.",
    trap: { point: "Trap: reading slope off Ax + By", say: "The x coefficient in standard form isn't the slope. Solve for y first, and watch the signs when you divide." },
    recap: { point: "Isolate y, then read the slope", say: "Solve for y, then the number on x is the slope. For intercepts, set the other variable to zero." },
    tint: { "2x": "green", "2": "green", "4/2": "green", "6x": "blue" },
    scene: {
      x: [-2, 5],
      y: [-6, 6],
      objects: [
        { id: "axes", kind: "axes", xStep: 2, yStep: 4 },
        { id: "line", kind: "fn", y: "2x - 4", color: "white" },
        { id: "yi", kind: "point", at: [0, -4], color: "yellow", label: "(0, −4)", labelOffset: [-64, 0] },
        { id: "run", kind: "seg", from: [0, -4], to: [2, -4], dash: true, color: "blue", label: "2", labelOffset: [0, 30] },
        { id: "rise", kind: "seg", from: [2, -4], to: [2, 0], width: 4, arrow: true, color: "green", label: "4", labelOffset: [30, 0] },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-2var",
    pattern: "Parallel and Perpendicular Line Relationships",
    example: 3,
    hook: "Parallel or perpendicular comes down to two slopes. Get both, then compare.",
    idea: [
      { point: "Parallel: same slope", say: "Parallel lines have exactly the same slope. They run side by side forever." },
      { point: "Perpendicular: flip it, change the sign", say: "Perpendicular slopes are negative reciprocals. Flip the fraction and change the sign. Multiplied together, they give negative one." },
    ],
    steps: [
      {
        say: "Our line has slope two. The other is two x plus four y equals sixteen, so first we find its slope.",
        highlight: ["slope 2", "2x + 4y = 16"],
        work: "2x + 4y = 16",
        draw: ["given", "gl"],
        focus: ["given", "gl"],
      },
      {
        say: "Subtract two x from both sides.",
        work: "4y = −2x + 16",
        note: "−2x both sides",
        focus: ["given", "gl"],
      },
      {
        say: "Divide everything by four. Its slope is negative one half: over two, down one.",
        work: "y = −(1/2)x + 4",
        note: "÷4 both sides",
        draw: ["T"],
        focus: ["given", "gl", "T"],
      },
      {
        say: "Now turn that slope triangle a quarter turn. Now it's over one, up two. Flip negative one half, change the sign, and you get two.",
        work: "2 · (−1/2) = −1",
        note: "product is −1",
        draw: ["T2", "ours", "perp"],
        move: [{ id: "T2", turn: 90, about: [4, 2], by: [-2, 1] }],
        focus: ["T2", "ours", "perp", "given", "gl"],
      },
      {
        say: "Parallel and the same line both need matching slopes, and these don't match. And negative reciprocals are exactly perpendicular, so the neither choice is out.",
        strike: [1, 2, 3],
        focus: ["given", "ours", "perp"],
      },
    ],
    answer: "Perpendicular. Two and negative one half are negative reciprocals.",
    trap: { point: "Trap: flipping without changing sign", say: "Perpendicular takes two moves. Flip the fraction and change the sign. Just flipping gets you the wrong slope." },
    recap: { point: "Find both slopes, then compare", say: "Put each line in slope-intercept form. Same slope is parallel. Negative reciprocals are perpendicular." },
    tint: { "2": "green", "1/2": "blue" },
    scene: {
      x: [-0.6, 7.4],
      y: [-0.6, 5.4],
      objects: [
        { id: "xax", kind: "seg", from: [-0.6, 0], to: [7.4, 0], width: 1.5, color: "gray" },
        { id: "yax", kind: "seg", from: [0, -0.6], to: [0, 5.4], width: 1.5, color: "gray" },
        { id: "given", kind: "fn", y: "-x/2 + 4", color: "blue" },
        { id: "gl", kind: "text", at: [1.4, 4.3], text: "−1/2", color: "blue" },
        { id: "T", kind: "poly", pts: [[4, 2], [6, 2], [6, 1]], fill: true, color: "yellow" },
        { id: "T2", kind: "poly", pts: [[4, 2], [6, 2], [6, 1]], fill: true, color: "yellow" },
        { id: "ours", kind: "fn", y: "2x - 1", color: "green", label: "2", labelOffset: [24, 16] },
        { id: "perp", kind: "angle", at: [2, 3], from: [4, 2], to: [3, 5], right: true, color: "white" },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-2var",
    pattern: "Interpreting a Constant or Coefficient in a Real-World Equation",
    example: 1,
    hook: "They give you the equation and ask what one number means. Look at what it's attached to.",
    idea: [
      { point: "Attached to a variable = a rate", say: "A number multiplying a variable is a rate. It counts once for each unit of that variable." },
      { point: "Standing alone = fixed amount", say: "A number standing alone is a fixed amount. It's there even when the variables are zero." },
    ],
    steps: [
      {
        say: "Y equals five x plus two hundred, the cost of renting a hall, where x is the number of guests.",
        highlight: ["y = 5x + 200", "x guests"],
        work: "y = 5x + 200",
        focus: ["line", "start"],
      },
      {
        say: "The two hundred stands alone. You pay it even with zero guests, so it's the flat rental fee.",
        work: "200 = flat fee",
        note: "alone → fixed",
        draw: ["fee"],
        focus: ["start", "fee"],
      },
      {
        say: "The five multiplies x, the guests. Each extra guest adds five more dollars. That's a per-guest cost.",
        work: "5 = dollars per guest",
        note: "on x → per guest",
        draw: ["r1", "s1", "r2", "s2", "r3", "s3"],
        focus: ["r1", "s1", "r2", "s2", "r3", "s3"],
      },
      {
        say: "The flat fee is the two hundred, not the five. And x is the guest count, not five.",
        strike: [1, 2],
        focus: ["start", "fee"],
      },
      {
        say: "Nothing in this equation sets a maximum. The five is just added per guest.",
        strike: [3],
      },
    ],
    answer: "Five is the extra cost, in dollars, for each guest.",
    trap: { point: "Trap: mixing up rate and fixed amount", say: "The coefficient rides along with a variable. The constant doesn't. Keep them straight and most of these answer themselves." },
    recap: { point: "On a variable: rate. Alone: fixed.", say: "Ask what the number is attached to. Tied to a variable, it's a rate. Standing alone, it's a fixed amount." },
    tint: { "5": "green", "5x": "green", "200": "yellow" },
    scene: {
      x: [-0.5, 7.5],
      y: [192, 238],
      objects: [
        { id: "axes", kind: "axes", xStep: 2, yStep: 20 },
        { id: "line", kind: "fn", y: "5x + 200", color: "blue" },
        { id: "start", kind: "point", at: [0, 200], color: "yellow", label: "200", labelOffset: [0, 26] },
        { id: "fee", kind: "seg", from: [0, 200], to: [7.5, 200], dash: true, color: "yellow" },
        { id: "r1", kind: "seg", from: [3, 215], to: [4, 215], dash: true, color: "white" },
        { id: "s1", kind: "seg", from: [4, 215], to: [4, 220], width: 3, color: "green" },
        { id: "r2", kind: "seg", from: [4, 220], to: [5, 220], dash: true, color: "white" },
        { id: "s2", kind: "seg", from: [5, 220], to: [5, 225], width: 3, color: "green" },
        { id: "r3", kind: "seg", from: [5, 225], to: [6, 225], dash: true, color: "white" },
        { id: "s3", kind: "seg", from: [6, 225], to: [6, 230], width: 3, color: "green", label: "+5 each", labelOffset: [44, 22] },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-2var",
    pattern: "Translating a Word Scenario into a Two-Variable Equation",
    example: 1,
    hook: "Two kinds of things, one total. That's the whole shape of this equation.",
    idea: [
      { point: "Two quantities = two variables", say: "Name each quantity with its own letter, and say in words what it counts." },
      { point: "\"Each\" or \"per\" means multiply", say: "Each or per means multiply that number by its own variable. Then the pieces add up to the total." },
    ],
    steps: [
      {
        say: "Chickens have two legs, cows have four, and there are one hundred seventy-two legs in all.",
        highlight: ["Chickens have 2 legs", "cows have 4 legs", "172 legs"],
        focus: ["total"],
      },
      {
        say: "Two legs for each chicken, and there are h chickens. So chicken legs total two h.",
        work: "chicken legs = 2h",
        note: "2 per chicken",
        draw: ["tc", "chick"],
        focus: ["tc", "chick"],
      },
      {
        say: "Four legs for each cow, and w cows. Cow legs total four w.",
        work: "cow legs = 4w",
        note: "4 per cow",
        draw: ["tw", "cow"],
        focus: ["tw", "cow"],
      },
      {
        say: "Together they make the total. Two h plus four w equals one hundred seventy-two.",
        work: "2h + 4w = 172",
        note: "parts add to total",
        hide: ["tc", "tw"],
        move: [
          { id: "chick", by: [0, -32] },
          { id: "cow", by: [0, -32] },
        ],
        focus: ["chick", "cow", "total"],
      },
      {
        say: "Four h plus two w gives chickens four legs. Subtracting h and w means nothing here. And h plus w counts animals, not legs.",
        strike: [1, 2, 3],
      },
    ],
    answer: "Two h plus four w equals one hundred seventy-two. Legs per animal, times animals, added up.",
    trap: { point: "Trap: rate on the wrong variable", say: "Double check which variable each per number belongs to. Four goes with cows, not chickens." },
    recap: { point: "Rate × its variable, then add", say: "Name both quantities, multiply each by its own rate, and set the sum equal to the total." },
    tint: { h: "yellow", w: "green" },
    scene: {
      x: [-4, 176],
      y: [-14, 68],
      objects: [
        { id: "total", kind: "poly", pts: [[0, 0], [172, 0], [172, 22], [0, 22]], fill: true, color: "white", label: "172 legs", labelOffset: [0, 30] },
        { id: "tc", kind: "text", at: [30, 61], text: "h chickens", color: "yellow" },
        { id: "chick", kind: "poly", pts: [[0.8, 32], [59.2, 32], [59.2, 54], [0.8, 54]], fill: true, color: "yellow", label: "2h" },
        { id: "tw", kind: "text", at: [116, 61], text: "w cows", color: "green" },
        { id: "cow", kind: "poly", pts: [[60.8, 32], [171.2, 32], [171.2, 54], [60.8, 54]], fill: true, color: "green", label: "4w" },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-2var",
    pattern: "Solving for One Variable Given the Other's Value",
    example: 1,
    hook: "Two variables, but they give you one of them. Now it's just a one-variable equation.",
    idea: [
      { point: "Substitute the known value", say: "Put the known value in for its variable, in parentheses. Make sure it's the right variable." },
      { point: "Then solve like usual", say: "What's left is an ordinary equation. Watch the sign if the variable you want has a minus in front." },
    ],
    steps: [
      {
        say: "Four a minus b equals fifteen, and a is six.",
        highlight: ["4a - b = 15", "a = 6"],
        work: "4a − b = 15",
        focus: ["f15"],
      },
      {
        say: "Put six in for a. Four a is four blocks of six.",
        work: "4(6) − b = 15",
        note: "plug in a = 6",
        draw: ["a1", "a2", "a3", "a4"],
        focus: ["a1", "a2", "a3", "a4"],
      },
      {
        say: "Four times six is twenty-four.",
        work: "24 − b = 15",
        note: "multiply",
        focus: ["a1", "a2", "a3", "a4", "f15"],
      },
      {
        say: "Subtract twenty-four from both sides. Negative b equals negative nine. Twenty-four minus b leaves fifteen, so b fills the gap.",
        work: "−b = −9",
        note: "−24 both sides",
        draw: ["gap"],
        focus: ["gap", "f15"],
      },
      {
        say: "That's negative b, not b. Multiply both sides by negative one, and b is nine.",
        work: "b = 9",
        note: "×(−1) both sides",
        hide: ["gap"],
        draw: ["b9"],
        focus: ["b9"],
        strike: [1],
      },
      {
        say: "Thirty-nine adds fifteen to twenty-four. And three fails the check: twenty-four minus three is twenty-one.",
        strike: [2, 3],
      },
    ],
    answer: "B equals nine. Twenty-four minus nine is fifteen.",
    trap: { point: "Trap: stopping at negative b", say: "Negative b equals negative nine isn't finished. Flip the sign to get b." },
    recap: { point: "Substitute, then solve for what's left", say: "Plug in the value you're given, then solve the one-variable equation that's left. Check the sign at the end." },
    tint: { a: "blue", b: "green", "6": "blue", "24": "blue", "15": "yellow", "9": "green" },
    scene: {
      x: [-1, 25],
      y: [-1.5, 9.5],
      objects: [
        { id: "f15", kind: "poly", pts: [[0.15, 0], [14.85, 0], [14.85, 3], [0.15, 3]], fill: true, color: "yellow", label: "15" },
        { id: "a1", kind: "poly", pts: [[0.15, 5], [5.85, 5], [5.85, 8], [0.15, 8]], fill: true, color: "blue", label: "6" },
        { id: "a2", kind: "poly", pts: [[6.15, 5], [11.85, 5], [11.85, 8], [6.15, 8]], fill: true, color: "blue", label: "6" },
        { id: "a3", kind: "poly", pts: [[12.15, 5], [17.85, 5], [17.85, 8], [12.15, 8]], fill: true, color: "blue", label: "6" },
        { id: "a4", kind: "poly", pts: [[18.15, 5], [23.85, 5], [23.85, 8], [18.15, 8]], fill: true, color: "blue", label: "6" },
        { id: "gap", kind: "poly", pts: [[15.15, 0], [23.85, 0], [23.85, 3], [15.15, 3]], dash: true, color: "green", label: "b" },
        { id: "b9", kind: "poly", pts: [[15.15, 0], [23.85, 0], [23.85, 3], [15.15, 3]], fill: true, color: "green", label: "b = 9" },
      ],
    },
  },
];
