import type { LessonVideoScript } from "../../types";

export const M_LINEAR_EQ_1VAR: LessonVideoScript[] = [
  {
    subskillId: "m-linear-eq-1var",
    pattern: "Standard Isolate-the-Variable Equations",
    example: 0,
    hook: "Solving for x is unwrapping a present. Take off the outside layers first.",
    idea: [
      { point: "Clear parentheses first", say: "If there are parentheses, multiply them out first, and hit every term inside." },
      { point: "Undo + and − before × and ÷", say: "Then undo adding and subtracting, and only after that, undo multiplying and dividing." },
      { point: "One move per line", say: "Write one move per line. Almost every mistake here is a sign slip done in your head." },
    ],
    steps: [
      {
        say: "Here's the equation. Five times the quantity x plus two equals three x plus eighteen. Top bar is the left side, bottom bar the right.",
        work: "5(x + 2) = 3x + 18",
        draw: ["rx0", "rx1", "rx2", "r18"],
      },
      {
        say: "Distribute the five to both terms. Five x's, and five twos. Slide the twos together and that's five x plus ten.",
        work: "5x + 10 = 3x + 18",
        note: "distribute the 5",
        move: [
          { id: "x1", by: [-2, 0] },
          { id: "x2", by: [-4, 0] },
          { id: "x3", by: [-6, 0] },
          { id: "x4", by: [-8, 0] },
          { id: "t0", by: [16, 0] },
          { id: "t1", by: [12, 0] },
          { id: "t2", by: [8, 0] },
          { id: "t3", by: [4, 0] },
        ],
        focus: ["t0", "t1", "t2", "t3", "t4"],
      },
      {
        say: "Get the x terms on one side. Take three x off both bars, and they still match.",
        work: "2x + 10 = 18",
        note: "−3x both sides",
        hide: ["x0", "x1", "x2", "rx0", "rx1", "rx2", "r18"],
        draw: ["r8", "r10"],
        set: [{ id: "view", x: [11, 31], y: [-1, 8] }],
      },
      {
        say: "Now undo the plus ten. Subtract ten from both sides.",
        work: "2x = 8",
        note: "−10 both sides",
        hide: ["t0", "t1", "t2", "t3", "t4", "r10"],
        set: [{ id: "view", x: [11, 21], y: [-1, 8] }],
      },
      {
        say: "Last layer: divide both sides by two. Each x matches a four. X equals four.",
        work: "x = 4",
        note: "÷2 both sides",
        hide: ["r8"],
        draw: ["r4a", "r4b"],
        focus: ["x3", "x4", "r4a", "r4b"],
      },
      {
        say: "Eight is what you get if you forget to multiply the two by five. One and negative four are sign slips.",
        strike: [1, 2, 3],
      },
    ],
    answer: "X equals four. Plug it back in and both sides come out to thirty.",
    trap: { point: "Trap: distributing to only one term", say: "The five multiplies everything in the parentheses, not just the x." },
    recap: { point: "Outside in, one move per line", say: "Clear the parentheses, undo plus and minus, then times and divide. One move per line." },
    tint: { x: "blue", "10": "orange", "18": "yellow", "8": "yellow", "4": "green" },
    scene: {
      x: [-0.5, 30.5],
      y: [-1, 8],
      objects: [
        { id: "x0", kind: "poly", pts: [[0.15, 4], [3.85, 4], [3.85, 7], [0.15, 7]], fill: true, color: "blue", label: "x" },
        { id: "t0", kind: "poly", pts: [[4.15, 4], [5.85, 4], [5.85, 7], [4.15, 7]], fill: true, color: "orange", label: "2" },
        { id: "x1", kind: "poly", pts: [[6.15, 4], [9.85, 4], [9.85, 7], [6.15, 7]], fill: true, color: "blue", label: "x" },
        { id: "t1", kind: "poly", pts: [[10.15, 4], [11.85, 4], [11.85, 7], [10.15, 7]], fill: true, color: "orange", label: "2" },
        { id: "x2", kind: "poly", pts: [[12.15, 4], [15.85, 4], [15.85, 7], [12.15, 7]], fill: true, color: "blue", label: "x" },
        { id: "t2", kind: "poly", pts: [[16.15, 4], [17.85, 4], [17.85, 7], [16.15, 7]], fill: true, color: "orange", label: "2" },
        { id: "x3", kind: "poly", pts: [[18.15, 4], [21.85, 4], [21.85, 7], [18.15, 7]], fill: true, color: "blue", label: "x" },
        { id: "t3", kind: "poly", pts: [[22.15, 4], [23.85, 4], [23.85, 7], [22.15, 7]], fill: true, color: "orange", label: "2" },
        { id: "x4", kind: "poly", pts: [[24.15, 4], [27.85, 4], [27.85, 7], [24.15, 7]], fill: true, color: "blue", label: "x" },
        { id: "t4", kind: "poly", pts: [[28.15, 4], [29.85, 4], [29.85, 7], [28.15, 7]], fill: true, color: "orange", label: "2" },
        { id: "rx0", kind: "poly", pts: [[0.15, 0], [3.85, 0], [3.85, 3], [0.15, 3]], fill: true, color: "blue", label: "x" },
        { id: "rx1", kind: "poly", pts: [[4.15, 0], [7.85, 0], [7.85, 3], [4.15, 3]], fill: true, color: "blue", label: "x" },
        { id: "rx2", kind: "poly", pts: [[8.15, 0], [11.85, 0], [11.85, 3], [8.15, 3]], fill: true, color: "blue", label: "x" },
        { id: "r18", kind: "poly", pts: [[12.15, 0], [29.85, 0], [29.85, 3], [12.15, 3]], fill: true, color: "yellow", label: "18" },
        { id: "r8", kind: "poly", pts: [[12.15, 0], [19.85, 0], [19.85, 3], [12.15, 3]], fill: true, color: "yellow", label: "8" },
        { id: "r10", kind: "poly", pts: [[20.15, 0], [29.85, 0], [29.85, 3], [20.15, 3]], fill: true, color: "orange", label: "10" },
        { id: "r4a", kind: "poly", pts: [[12.15, 0], [15.85, 0], [15.85, 3], [12.15, 3]], fill: true, color: "green", label: "4" },
        { id: "r4b", kind: "poly", pts: [[16.15, 0], [19.85, 0], [19.85, 3], [16.15, 3]], fill: true, color: "green", label: "4" },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-1var",
    pattern: "No-Solution and Infinite-Solution Equations",
    example: 3,
    hook: "Sometimes x just vanishes from the equation. That's not a mistake. That's the answer showing up.",
    idea: [
      { point: "Simplify both sides first", say: "Distribute and combine on each side first. The x terms often only match once everything's cleaned up." },
      { point: "x-terms cancel? Check what's left", say: "If the x terms cancel, stop solving. There's no x left to find. Look at the leftover numbers." },
      { point: "False → none. True → infinite.", say: "A false statement like five equals seven means no solution. A true one like five equals five means every number works." },
    ],
    steps: [
      {
        say: "Here's the equation. Five x minus three times the quantity x plus four equals two x plus three. Graph each side as a line.",
        highlight: ["5x - 3(x + 4) = 2x + 3"],
        work: "5x − 3(x + 4) = 2x + 3",
        draw: ["lhs", "rhs"],
      },
      {
        say: "Distribute the negative three to both terms. Negative three x, and negative twelve.",
        work: "5x − 3x − 12 = 2x + 3",
        note: "distribute the −3",
        focus: ["lhs"],
      },
      {
        say: "Combine the x terms on the left. Five x minus three x is two x. Both lines climb at the same slope.",
        work: "2x − 12 = 2x + 3",
        note: "combine like terms",
        focus: ["lhs", "rhs"],
      },
      {
        say: "Now subtract two x from both sides. The x terms cancel completely, and we're left with negative twelve equals three.",
        work: "−12 = 3",
        note: "−2x both sides",
        draw: ["gA", "gB", "gap"],
        focus: ["gA", "gB", "gap"],
      },
      {
        say: "That's false for every x. The lines are parallel, fifteen apart everywhere, so they never meet. Not one solution, and not infinitely many.",
        strike: [1, 2],
        set: [
          { id: "gA", at: [3, -6] },
          { id: "gB", at: [3, 9] },
        ],
        focus: ["gA", "gB", "gap", "lhs", "rhs"],
      },
      {
        say: "And exactly two is out on principle. A linear equation has none, one, or infinitely many solutions. Never two.",
        strike: [3],
      },
    ],
    answer: "No solution. Negative twelve never equals three, no matter what x is.",
    trap: { point: "Trap: mixing up false and true", say: "A false leftover means no solution. A true leftover means infinitely many. Don't swap them." },
    recap: { point: "x cancels? Judge the leftover", say: "When the x terms cancel, don't hunt for x. Check if what's left is true or false." },
    tint: { "12": "yellow" },
    scene: {
      x: [-4, 8],
      y: [-20, 22],
      objects: [
        { id: "axes", kind: "axes", xStep: 4, yStep: 10 },
        { id: "lhs", kind: "fn", y: "5x - 3(x + 4)", color: "yellow", label: "left side", labelOffset: [0, 30] },
        { id: "rhs", kind: "fn", y: "2x + 3", color: "green", label: "right side" },
        { id: "gA", kind: "point", at: [-2, -16], color: "yellow" },
        { id: "gB", kind: "point", at: [-2, -1], color: "green" },
        { id: "gap", kind: "seg", from: "gA", to: "gB", dash: true, color: "orange", label: "15" },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-1var",
    pattern: "Solving for a Related Expression Without Fully Isolating x",
    example: 0,
    hook: "Read the question before you start solving. Sometimes they don't even want x.",
    idea: [
      { point: "Find what they're asking for", say: "If the question asks for x minus seven, or two x, that's your target. Not x itself." },
      { point: "Reshape the equation to hit it", say: "Divide, add, or combine the whole equation so the exact target lands on one side. Usually one move." },
    ],
    steps: [
      {
        say: "Four x minus twenty-eight equals negative twenty-four, and they want x minus seven.",
        highlight: ["4x - 28 = -24", "x - 7"],
        work: "4x − 28 = −24",
        focus: ["whole"],
      },
      {
        say: "Notice four x divided by four is x, and twenty-eight divided by four is seven. So divide every term by four.",
        work: "(4x − 28)/4 = −24/4",
        note: "÷4 every term",
        hide: ["whole"],
        draw: ["q1", "q2", "q3", "q4"],
      },
      {
        say: "That lands right on the target. One piece is x minus seven, and it reaches negative six. No need to find x first.",
        work: "x − 7 = −6",
        note: "exactly the target",
        draw: ["pt"],
        focus: ["q1", "pt"],
      },
      {
        say: "One is x itself, which they didn't ask for. Positive six is a sign slip on negative twenty-four divided by four.",
        strike: [2, 3],
      },
      {
        say: "And negative one isn't what you get when every term is divided by four.",
        strike: [1],
      },
    ],
    answer: "Negative six. One division, and you're done.",
    trap: { point: "Trap: answering with x", say: "Solving all the way to x out of habit hands you the wrong answer, and it's always a choice." },
    recap: { point: "Aim for the expression, not x", say: "Find the expression they asked for, then reshape the whole equation to land on it." },
    tint: { x: "blue", "24": "yellow", "6": "green" },
    scene: {
      x: [-27, 3],
      y: [-2, 5],
      objects: [
        { id: "nl", kind: "numline", min: -24, max: 0, step: 6 },
        { id: "whole", kind: "seg", from: [0, 1.6], to: [-24, 1.6], width: 8, color: "yellow", label: "4x − 28" },
        { id: "q1", kind: "seg", from: [-0.8, 1.6], to: [-5.2, 1.6], width: 8, color: "blue", label: "x − 7" },
        { id: "q2", kind: "seg", from: [-6.8, 1.6], to: [-11.2, 1.6], width: 8, color: "blue" },
        { id: "q3", kind: "seg", from: [-12.8, 1.6], to: [-17.2, 1.6], width: 8, color: "blue" },
        { id: "q4", kind: "seg", from: [-18.8, 1.6], to: [-23.2, 1.6], width: 8, color: "blue" },
        { id: "pt", kind: "point", at: [-6, 0], color: "green" },
      ],
    },
  },
  {
    subskillId: "m-linear-eq-1var",
    pattern: "Translating a Word Problem into an Equation",
    example: 3,
    hook: "Word problems are a translation job. Go phrase by phrase, and watch out for less than.",
    idea: [
      { point: "Name the unknown", say: "Pick a letter for the unknown, and say in plain words what it stands for." },
      { point: "Translate one phrase at a time", say: "More than means add. Times means multiply. Is means equals. Do it piece by piece, not all at once." },
      { point: "\"Less than\" flips the order", say: "Less than is the sneaky one. It's written in the opposite order from how you say it." },
    ],
    steps: [
      {
        say: "Twelve less than a number is forty-five. The number is n.",
        highlight: ["12 less than a number", "is 45"],
        focus: ["nspan", "nA", "nB"],
      },
      {
        say: "Twelve less than a number means start with the number, then take twelve away. So n minus twelve, not twelve minus n.",
        work: "n − 12",
        note: "less than: flip it",
        draw: ["twelve"],
        hide: ["nB"],
        move: [{ id: "twelve", by: [2, -10] }],
        focus: ["twelve", "nA"],
      },
      {
        say: "The word is becomes the equals sign. What's left is forty-five. N minus twelve equals forty-five.",
        work: "n − 12 = 45",
        note: "\"is\" means =",
        draw: ["r45"],
        hide: ["nA"],
        focus: ["r45", "nspan", "twelve"],
      },
      {
        say: "Twelve minus n reverses the order. N plus twelve adds when it should subtract, and twelve n multiplies.",
        strike: [1, 2, 3],
      },
    ],
    answer: "N minus twelve equals forty-five. The number comes first, then twelve comes off.",
    trap: { point: "Trap: writing less than in spoken order", say: "Twelve less than n is n minus twelve. Writing it in the order you hear it flips the meaning." },
    recap: { point: "Phrase by phrase, flip less than", say: "Name your variable, translate one phrase at a time, and flip the order for less than." },
    tint: { n: "blue", "12": "orange", "45": "yellow" },
    scene: {
      x: [-1.5, 60],
      y: [-11, 13],
      objects: [
        { id: "nspan", kind: "seg", from: [0, 10], to: [57, 10], width: 2, color: "blue", label: "n" },
        { id: "nA", kind: "poly", pts: [[0.3, 1], [44.7, 1], [44.7, 7], [0.3, 7]], fill: true, color: "blue" },
        { id: "nB", kind: "poly", pts: [[45.3, 1], [56.7, 1], [56.7, 7], [45.3, 7]], fill: true, color: "blue" },
        { id: "twelve", kind: "poly", pts: [[45.3, 1], [56.7, 1], [56.7, 7], [45.3, 7]], fill: true, color: "orange", label: "12" },
        { id: "r45", kind: "poly", pts: [[0.3, 1], [44.7, 1], [44.7, 7], [0.3, 7]], fill: true, color: "yellow", label: "45" },
      ],
    },
  },
];
