import type { LessonVideoScript } from "../../types";

export const M_LINES_ANGLES_TRI: LessonVideoScript[] = [
  {
    subskillId: "m-lines-angles-tri",
    pattern: "Triangle Angle Sum and Exterior Angles",
    example: 0,
    hook: "There's a shortcut for exterior angles that saves you a whole step.",
    idea: [
      { point: "Inside angles add to 180°", say: "The three angles inside any triangle add up to one hundred eighty degrees." },
      { point: "Exterior = the two far angles", say: "And an exterior angle equals the two inside angles that aren't next to it, added together." },
    ],
    steps: [
      {
        say: "The exterior angle is one hundred ten degrees, and one far angle is forty.",
        highlight: ["exterior angle measures 110°", "40°"],
        focus: ["ext", "angB"],
      },
      {
        say: "The exterior angle equals the two far angles together. So forty plus x equals one hundred ten.",
        work: "40 + x = 110",
        note: "exterior = far + far",
        draw: ["copyB", "copyA"],
        move: [
          { id: "copyB", by: [5, 0] },
          { id: "copyA", by: [1.17, -3.214], turn: 180 },
        ],
        focus: ["ext", "copyA", "copyB"],
      },
      {
        say: "Subtract forty from both sides. X is seventy degrees.",
        work: "x = 70°",
        note: "−40 both sides",
        focus: ["angA"],
      },
      {
        say: "One hundred ten is the exterior angle itself, and forty is the angle we were given.",
        strike: [1, 2],
      },
      {
        say: "And one fifty adds them. The exterior angle is already the sum, so subtract.",
        strike: [3],
      },
    ],
    answer: "Seventy degrees. One step, no need to find the angle next to it first.",
    trap: { point: "Trap: adding when you should subtract", say: "The exterior angle is already the total. Take away the angle you know." },
    recap: { point: "Exterior = sum of the two far angles", say: "An exterior angle equals the two far inside angles added together. Use it to skip a step." },
    tint: { x: "blue", "40": "yellow", "110": "pink" },
    scene: {
      x: [-0.6, 8],
      y: [-0.6, 3.9],
      pts: { B: [0, 0], C: [5, 0], A: [3.83, 3.214], D: [7.6, 0] },
      objects: [
        { id: "tri", kind: "poly", pts: ["A", "B", "C"] },
        { id: "ext-line", kind: "seg", from: "C", to: "D", dash: true, color: "gray" },
        { id: "angB", kind: "angle", at: "B", from: "C", to: "A", r: 34, color: "yellow", label: "40°" },
        { id: "angA", kind: "angle", at: "A", from: "B", to: "C", r: 26, color: "blue", label: "x" },
        { id: "ext", kind: "angle", at: "C", from: "D", to: "A", r: 48, color: "pink", label: "110°", labelOffset: [8, -4] },
        { id: "copyB", kind: "angle", at: "B", from: "C", to: "A", r: 34, color: "yellow" },
        { id: "copyA", kind: "angle", at: "A", from: "B", to: "C", r: 34, color: "blue" },
      ],
    },
  },
  {
    subskillId: "m-lines-angles-tri",
    pattern: "Parallel Lines Cut by a Transversal",
    example: 0,
    hook: "Parallel lines give you a bunch of angles for free. You just have to know which pairs match.",
    idea: [
      { point: "Corresponding, alternate: equal", say: "Corresponding angles and alternate interior angles are equal. Same spot, or a clean zigzag across." },
      { point: "Same-side interior: add to 180°", say: "But two angles between the lines, on the same side of the transversal, add up to one hundred eighty." },
      { point: "Name the pair before you calculate", say: "So before any math, name which kind of pair you're looking at. That decides everything." },
    ],
    steps: [
      {
        say: "One angle is sixty-five degrees, and we want its same-side interior partner, up at the other line.",
        highlight: ["65°", "co-interior (same-side interior) angle"],
        focus: ["ang65", "angX"],
      },
      {
        say: "Slide the sixty-five up the transversal. It lands right beside x on a straight line, so sixty-five plus x is one eighty.",
        work: "65 + x = 180",
        note: "same-side → sum 180°",
        draw: ["copy65"],
        move: [{ id: "copy65", by: [1.119, 2.4] }],
        focus: ["copy65", "angX", "trans"],
      },
      {
        say: "Subtract sixty-five from both sides. The angle is one hundred fifteen degrees.",
        work: "x = 115°",
        note: "−65 both sides",
        focus: ["angX"],
      },
      {
        say: "Sixty-five treats the pair as equal, which only works for corresponding or alternate angles.",
        strike: [1],
        focus: ["ang65", "angX"],
      },
      {
        say: "Twenty-five uses ninety instead of one eighty, and one eighty is the total, not the missing angle.",
        strike: [2, 3],
      },
    ],
    answer: "One hundred fifteen degrees. One sharp angle, one wide one, adding to a straight line.",
    trap: { point: "Trap: calling same-side angles equal", say: "Same-side interior angles look like partners, so it's tempting to make them equal. They add to one eighty instead." },
    recap: { point: "Name the pair, then equal or 180°", say: "Figure out the pair type first. Equal for corresponding and alternate, one eighty for same-side interior." },
    tint: { x: "blue", "65": "yellow" },
    scene: {
      // Transversal at 65° through B; it meets the top line 2.4 up at T.
      x: [-0.1, 5.9],
      y: [-1.05, 3.45],
      pts: { B: [2, 0], T: [3.119, 2.4], R1: [5.7, 0], R2: [5.7, 2.4] },
      objects: [
        { id: "bot", kind: "seg", from: [0.1, 0], to: "R1" },
        { id: "top", kind: "seg", from: [0.1, 2.4], to: "R2" },
        { id: "trans", kind: "seg", from: [1.577, -0.906], to: [3.542, 3.306], color: "gray" },
        { id: "ang65", kind: "angle", at: "B", from: "R1", to: "T", r: 28, color: "yellow", label: "65°", labelOffset: [8, 0] },
        { id: "angX", kind: "angle", at: "T", from: "R2", to: "B", r: 28, color: "blue", label: "x" },
        { id: "copy65", kind: "angle", at: "B", from: "R1", to: "T", r: 28, color: "yellow" },
      ],
    },
  },
  {
    subskillId: "m-lines-angles-tri",
    pattern: "Similar and Congruent Triangles: Corresponding Parts",
    example: 2,
    hook: "The letters in a similarity statement are a map. Follow the order, not the picture.",
    idea: [
      { point: "Vertex order = matching parts", say: "Triangle ABC similar to EFD means A matches E, B matches F, and C matches D, in that order." },
      { point: "New side = k × old side", say: "Matching sides all share one ratio, the scale factor. Find it from one known pair, then use it." },
    ],
    steps: [
      {
        say: "Read the letters in order. A goes with E, B with F, C with D. Watch where each corner lands.",
        highlight: ["triangle EFD (note the vertex order)"],
        work: "A↔E, B↔F, C↔D",
        note: "match in order",
        draw: ["ghost", "gA", "gB", "gC"],
        focus: ["ghost", "gA", "gB", "gC", "lA", "lB", "lC", "lE", "lF", "lD"],
      },
      {
        say: "Send each corner to its partner. The copy flips and grows. A B to E F is fifteen over ten, one and a half.",
        highlight: ["AB = 10", "EF = 15"],
        work: "k = 15/10 = 1.5",
        note: "scale factor",
        set: [
          { id: "gA", at: [30, 0] },
          { id: "gB", at: [15, 0] },
          { id: "gC", at: [24, 10.392] },
        ],
        focus: ["ghost", "sAB", "sEF"],
      },
      {
        say: "Now D E. D goes with C and E goes with A, so D E matches C A, which is eight.",
        highlight: ["CA = 8"],
        work: "DE ↔ CA = 8",
        note: "find the partner",
        focus: ["sCA", "sDE"],
      },
      {
        say: "Multiply by the scale factor. Eight times one and a half is twelve.",
        work: "DE = 1.5 × 8 = 12",
        note: "× k",
        hide: ["sDE"],
        draw: ["sDE12"],
        focus: ["sCA", "sDE12"],
      },
      {
        say: "Eight is C A itself, and ten is A B. Neither one got scaled.",
        strike: [1, 2],
        focus: ["sCA", "sAB"],
      },
      {
        say: "And five point three three divides by the scale factor. DE is on the bigger triangle, so multiply.",
        strike: [3],
        focus: ["sDE12"],
      },
    ],
    answer: "Twelve. The bigger triangle's side should be bigger, and it is.",
    trap: { point: "Trap: matching sides by position", say: "Don't pair sides because they look alike or sit near each other. The vertex order tells you who matches whom." },
    recap: { point: "Match by letters, then multiply by k", say: "Use the vertex order to find each side's partner, get the scale factor from a known pair, and apply it." },
    tint: { "10": "yellow", "15": "yellow", "8": "blue", "12": "blue", "1.5": "green", k: "green" },
    scene: {
      // ABC: AB = 10, CA = 8, angle A = 60°. EFD is ABC × 1.5, mirrored
      // (E at the right), so the picture doesn't give the matching away.
      x: [-2, 32.5],
      y: [-2.8, 13],
      pts: { A: [0, 0], B: [10, 0], C: [4, 6.928], E: [30, 0], F: [15, 0], D: [24, 10.392] },
      objects: [
        { id: "abc", kind: "poly", pts: ["A", "B", "C"] },
        { id: "efd", kind: "poly", pts: ["E", "F", "D"] },
        { id: "sAB", kind: "seg", from: "A", to: "B", color: "yellow", label: "10" },
        { id: "sCA", kind: "seg", from: "C", to: "A", color: "blue", label: "8" },
        { id: "sEF", kind: "seg", from: "E", to: "F", color: "yellow", label: "15" },
        { id: "sDE", kind: "seg", from: "D", to: "E", color: "blue", label: "?" },
        { id: "lA", kind: "text", at: [-1, -2.1], text: "A" },
        { id: "lB", kind: "text", at: [10.9, -2.1], text: "B" },
        { id: "lC", kind: "text", at: [4, 7.7], text: "C" },
        { id: "lE", kind: "text", at: [31, -2.1], text: "E" },
        { id: "lF", kind: "text", at: [14.1, -2.1], text: "F" },
        { id: "lD", kind: "text", at: [24, 11.1], text: "D" },
        { id: "gA", kind: "point", at: "A", color: "green" },
        { id: "gB", kind: "point", at: "B", color: "green" },
        { id: "gC", kind: "point", at: "C", color: "green" },
        { id: "ghost", kind: "poly", pts: ["gA", "gB", "gC"], color: "green", fill: true, dash: true },
        { id: "sDE12", kind: "seg", from: "D", to: "E", color: "blue", label: "12" },
      ],
    },
  },
  {
    subskillId: "m-lines-angles-tri",
    pattern: "Vertical Angles and Basic Angle Relationships",
    example: 2,
    hook: "Two lines cross, and you get two facts that crack almost every one of these.",
    idea: [
      { point: "Vertical angles are equal", say: "Angles straight across from each other at a crossing are vertical angles, and they're always equal." },
      { point: "Side by side on a line: 180°", say: "Angles next to each other along one line add to one hundred eighty, since a line is straight." },
    ],
    steps: [
      {
        say: "These two angles are vertical. Spin one a half turn about the crossing and it lands exactly on the other. So they're equal.",
        highlight: ["its vertical angle"],
        work: "3x + 15 = 5x − 25",
        note: "vertical angles equal",
        draw: ["copyTop"],
        move: [{ id: "copyTop", turn: 180 }],
        focus: ["copyTop", "angBot"],
      },
      {
        say: "Subtract three x from both sides to get the x terms together.",
        work: "15 = 2x − 25",
        note: "−3x both sides",
        focus: ["angTop", "angBot"],
      },
      {
        say: "Add twenty-five to both sides.",
        work: "40 = 2x",
        note: "+25 both sides",
        focus: ["angTop", "angBot"],
      },
      {
        say: "Divide by two. X is twenty, and both angles come out to seventy-five degrees.",
        work: "x = 20",
        note: "÷2 both sides",
        focus: ["angTop", "angBot"],
      },
      {
        say: "Forty is two x, one step early. Five doesn't check out, and negative twenty is a sign slip.",
        strike: [1, 2, 3],
      },
    ],
    answer: "X equals twenty. Plug it in and both angles are seventy-five degrees, as vertical angles should be.",
    trap: { point: "Trap: vertical vs. side-by-side", say: "Across the crossing means equal. Next to each other on a line means they add to one eighty. Don't swap them." },
    recap: { point: "Across = equal, beside = 180°", say: "Spot where the angles sit, write the equation that matches, and solve." },
    tint: { x: "blue", "15": "yellow", "25": "orange" },
    scene: {
      // Two lines crossing at 75° (the angles' true size once x = 20).
      x: [-5.7, 5.7],
      y: [-3.5, 3.5],
      pts: { O: [0, 0], R: [4.4, 0], L: [-4.4, 0], U: [0.854, 3.188], Dn: [-0.854, -3.188] },
      objects: [
        { id: "l1", kind: "seg", from: "L", to: "R" },
        { id: "l2", kind: "seg", from: "Dn", to: "U" },
        { id: "angTop", kind: "angle", at: "O", from: "R", to: "U", r: 30, color: "yellow", label: "(3x + 15)°", labelOffset: [50, -14] },
        { id: "angBot", kind: "angle", at: "O", from: "L", to: "Dn", r: 30, color: "orange", label: "(5x − 25)°", labelOffset: [-50, 14] },
        { id: "copyTop", kind: "angle", at: "O", from: "R", to: "U", r: 30, color: "yellow" },
      ],
    },
  },
];
