import type { LessonVideoScript } from "../../types";

export const M_LINEAR_INEQ: LessonVideoScript[] = [
  {
    subskillId: "m-linear-ineq",
    pattern: "Solving with the Sign-Flip Rule",
    example: 0,
    hook: "Inequalities are equations with one extra rule. Forget it and you get the exact opposite answer.",
    idea: [
      { point: "Same steps as an equation", say: "You isolate x the same way you would in an equation. Add, subtract, multiply, divide." },
      { point: "× or ÷ by a negative: flip it", say: "The one exception: multiply or divide both sides by a negative number, and the sign flips." },
      { point: "Adding and subtracting never flip", say: "Adding or subtracting a negative doesn't count. Only multiplying or dividing by one does." },
    ],
    steps: [
      {
        say: "Here's the inequality. Negative three x plus six is greater than zero. On the graph: where is this line above zero?",
        work: "−3x + 6 > 0",
        focus: ["line", "y6"],
      },
      {
        say: "Subtract six from both sides. No flip here, it's just subtraction.",
        work: "−3x > −6",
        note: "−6 both sides",
        focus: ["line"],
      },
      {
        say: "Now divide by negative three. That's a negative, so the greater than turns into less than. X is less than two.",
        work: "x < 2",
        note: "÷(−3): flip the sign",
        draw: ["bpt", "pos", "ray"],
        focus: ["bpt", "pos", "ray", "line"],
      },
      {
        say: "X greater than two is what you get if you forget the flip. Out there, the line is below zero.",
        strike: [1],
        draw: ["neg"],
        focus: ["neg", "bpt"],
      },
      {
        say: "And the boundary is positive two, since negative six over negative three is two. So both negative twos are out.",
        strike: [2, 3],
        focus: ["bpt", "ray"],
      },
    ],
    answer: "X is less than two. Try zero: six is greater than zero, so it checks.",
    trap: { point: "Trap: dividing by a negative, no flip", say: "The flip often hides in the last step. Every time you divide by a negative, say flip out loud." },
    recap: { point: "Negative × or ÷ flips the sign", say: "Solve it like an equation. Multiply or divide by a negative, and the sign turns around." },
    tint: { x: "blue", "2": "green", "6": "yellow" },
    scene: {
      x: [-2, 5],
      y: [-5, 11],
      objects: [
        { id: "axes", kind: "axes", xStep: 2, yStep: 5 },
        { id: "line", kind: "fn", y: "-3x + 6", color: "blue" },
        { id: "y6", kind: "point", at: [0, 6], color: "yellow", label: "6" },
        { id: "pos", kind: "poly", pts: [[-2, 0], [-2, 11], [-1.667, 11], [2, 0]], fill: true, color: "green" },
        { id: "ray", kind: "seg", from: [2, 0], to: [-2, 0], width: 5, arrow: true, color: "green" },
        { id: "bpt", kind: "point", at: [2, 0], open: true, color: "green", label: "2", labelOffset: [-4, 32] },
        { id: "neg", kind: "poly", pts: [[2, 0], [3.667, -5], [5, -5], [5, 0]], fill: true, color: "orange" },
      ],
    },
  },
  {
    subskillId: "m-linear-ineq",
    pattern: "Word Problems with Inequality Language",
    example: 2,
    hook: "In these, the algebra is easy. The hard part is turning the words into the right sign.",
    idea: [
      { point: "At least → ≥   at most → ≤", say: "At least means that number or more. At most, or no more than, means that number or less." },
      { point: "More than → >, no equals", say: "More than, or exceeds, is strict. The number itself doesn't count." },
      { point: "Translate first, then solve", say: "Write the inequality from the words, then solve it just like you normally would." },
    ],
    steps: [
      {
        say: "Four dollars for the first hour, two for each extra hour, and no more than sixteen total.",
        highlight: ["$4 for the first hour", "$2 for each additional hour", "no more than $16"],
        focus: ["budget", "first"],
      },
      {
        say: "No more than means sixteen is allowed. So four plus two a is less than or equal to sixteen.",
        work: "4 + 2a ≤ 16",
        note: "no more than → ≤",
        focus: ["budget", "first"],
      },
      {
        say: "Subtract the four dollars for the first hour. That leaves twelve dollars for extra hours.",
        work: "2a ≤ 12",
        note: "−4 both sides",
        draw: ["left"],
        focus: ["left"],
      },
      {
        say: "Divide by two. Two-dollar hours fill the twelve exactly six times. A is at most six.",
        work: "a ≤ 6",
        note: "÷2 both sides",
        draw: ["h1", "h2", "h3", "h4", "h5", "h6"],
        focus: ["h1", "h2", "h3", "h4", "h5", "h6", "left"],
      },
      {
        say: "Eight forgets the first hour's four dollars. Twelve is the money left, not the hours.",
        strike: [1, 3],
        focus: ["first", "left"],
      },
      {
        say: "Five works, but six costs exactly sixteen, and that's still no more than sixteen.",
        strike: [2],
        focus: ["h6", "budget"],
      },
    ],
    answer: "Six extra hours. Four plus twelve is sixteen, right at the limit, and that's allowed.",
    trap: { point: "Trap: < when the words mean ≤", say: "At least and at most include the number itself. Using a strict sign throws away the right answer." },
    recap: { point: "Words → sign, then solve", say: "Translate the phrase into the sign first. After that it's the same algebra as always." },
    tint: { a: "blue", "4": "yellow", "12": "green", "6": "blue" },
    scene: {
      x: [-0.8, 16.8],
      y: [-2.8, 5.2],
      objects: [
        { id: "budget", kind: "poly", pts: [[0, 0], [16, 0], [16, 3], [0, 3]], dash: true, color: "white", label: "$16 limit", labelOffset: [0, -34] },
        { id: "first", kind: "poly", pts: [[0.12, 0.12], [3.88, 0.12], [3.88, 2.88], [0.12, 2.88]], fill: true, color: "yellow", label: "$4" },
        { id: "left", kind: "seg", from: [4, -0.9], to: [16, -0.9], dash: true, color: "green", label: "$12 left", labelOffset: [0, 32] },
        { id: "h1", kind: "poly", pts: [[4.12, 0.12], [5.88, 0.12], [5.88, 2.88], [4.12, 2.88]], fill: true, color: "blue", label: "2" },
        { id: "h2", kind: "poly", pts: [[6.12, 0.12], [7.88, 0.12], [7.88, 2.88], [6.12, 2.88]], fill: true, color: "blue", label: "2" },
        { id: "h3", kind: "poly", pts: [[8.12, 0.12], [9.88, 0.12], [9.88, 2.88], [8.12, 2.88]], fill: true, color: "blue", label: "2" },
        { id: "h4", kind: "poly", pts: [[10.12, 0.12], [11.88, 0.12], [11.88, 2.88], [10.12, 2.88]], fill: true, color: "blue", label: "2" },
        { id: "h5", kind: "poly", pts: [[12.12, 0.12], [13.88, 0.12], [13.88, 2.88], [12.12, 2.88]], fill: true, color: "blue", label: "2" },
        { id: "h6", kind: "poly", pts: [[14.12, 0.12], [15.88, 0.12], [15.88, 2.88], [14.12, 2.88]], fill: true, color: "blue", label: "2" },
      ],
    },
  },
  {
    subskillId: "m-linear-ineq",
    pattern: "Matching a Graph, Table, or Point to an Inequality or System",
    example: 0,
    hook: "Sometimes they hand you the answer and ask if it works. That's the easiest kind of checking.",
    idea: [
      { point: "A point: plug it in", say: "For a single point, plug in its x and y and see if the statement comes out true." },
      { point: "A table: every row must pass", say: "For a table, every row has to pass. One failing row rules it out." },
      { point: "Shading: test a point inside", say: "For a shaded graph, find the line, then test a point clearly inside the shading." },
    ],
    steps: [
      {
        say: "Here's the inequality. Y is greater than two x minus four: everything above the dashed line. The point is three, one.",
        highlight: ["(3, 1)", "y > 2x - 4"],
        work: "y > 2x − 4",
        draw: ["P"],
        focus: ["P", "region", "bound"],
      },
      {
        say: "Put in x equals three and y equals one.",
        work: "1 > 2(3) − 4",
        note: "plug in (3, 1)",
        draw: ["up", "L"],
        focus: ["P", "up", "L"],
      },
      {
        say: "Two times three is six, minus four is two. So the question is, is one greater than two? The point sits below the line.",
        work: "1 > 2",
        note: "simplify the right",
        focus: ["P", "L", "up"],
      },
      {
        say: "It isn't. So the yes choices are out, and comparing three to one isn't the test anyway.",
        strike: [1, 3],
        focus: ["P", "region"],
      },
      {
        say: "And flipping it to one less than two changes the inequality you were asked to check.",
        strike: [2],
      },
    ],
    answer: "No. Plugging in gives one greater than two, which is false.",
    trap: { point: "Trap: checking only some points", say: "With a table or a system, one pass isn't enough. Every point has to satisfy every inequality." },
    recap: { point: "Plug in and check true or false", say: "Given a point, substitute it. True means it works, false means it doesn't." },
    tint: { "1": "yellow", "3": "yellow" },
    scene: {
      x: [-0.5, 4.5],
      y: [-2, 4],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 2 },
        { id: "region", kind: "poly", pts: [[-0.5, -2], [1, -2], [4, 4], [-0.5, 4]], fill: true, color: "blue", dash: true },
        { id: "bound", kind: "fn", y: "2x - 4", dash: true, color: "white" },
        { id: "P", kind: "point", at: [3, 1], color: "yellow", label: "(3, 1)", labelOffset: [0, 26] },
        { id: "up", kind: "seg", from: [3, 1], to: [3, 2], dash: true, color: "green" },
        { id: "L", kind: "point", at: [3, 2], color: "green", label: "2", labelOffset: [-26, 0] },
      ],
    },
  },
];
