import type { LessonVideoScript } from "../../types";

export const M_NONLINEAR_FUNC: LessonVideoScript[] = [
  {
    subskillId: "m-nonlinear-func",
    pattern: "Reading Vertex Form Directly",
    example: 1,
    hook: "Vertex form hands you the vertex for free. You just have to read the signs right.",
    idea: [
      { point: "Vertex form shows (h, k)", say: "In the form a times x minus h, squared, plus k, the vertex is h comma k. No work needed." },
      { point: "Inside sign flips; outside sign stays", say: "The template subtracts h, so the number inside shows up with the opposite sign. The number outside keeps its sign." },
    ],
    steps: [
      {
        say: "Here's our function. Negative two times x plus three, squared, minus one. Start from the plain upside-down parabola, peaked at the origin.",
        highlight: ["-2(x + 3)² - 1"],
        work: "f(x) = −2(x + 3)² − 1",
        focus: ["para", "origin"],
      },
      {
        say: "Plus three is really minus negative three. Match it to the template, so h is negative three, and the peak slides three left.",
        work: "f(x) = −2(x − (−3))² + (−1)",
        note: "match a(x − h)² + k",
        set: [{ id: "para", params: { h: -3 } }],
        draw: ["left"],
        focus: ["para", "left"],
      },
      {
        say: "Outside, it's minus one, and that sign stays put. So k is negative one, and the peak drops one.",
        work: "h = −3,  k = −1",
        note: "flip h, keep k",
        set: [{ id: "para", params: { k: -1 } }],
        draw: ["down"],
        focus: ["para", "down"],
      },
      {
        say: "Put them together: negative three, negative one. That's the peak.",
        work: "vertex = (−3, −1)",
        note: "(h, k)",
        draw: ["vertex"],
        focus: ["vertex"],
      },
      {
        say: "Three, negative one is the classic slip: reading plus three as h equals three. That's over on the wrong side.",
        draw: ["wrong"],
        focus: ["wrong", "vertex"],
        strike: [1],
      },
      {
        say: "Negative three, one flips the sign of k. And three, one flips both.",
        strike: [2, 3],
      },
    ],
    answer: "Negative three, negative one. The negative two out front flips the parabola upside down, but it doesn't move the vertex.",
    trap: { point: "Trap: (x + 3) means h = −3", say: "Plus three inside the parentheses means h is negative three, not three. The inside sign always flips." },
    recap: { point: "Inside: flip the sign. Outside: keep it.", say: "Match to the template, flip the inside number, keep the outside one, and the vertex reads itself." },
    tint: { h: "blue", "3": "blue", k: "orange", "1": "orange" },
    // y = −2(x − h)² + k slides from (0, 0) to (−3, −1).
    scene: {
      x: [-6, 4.5],
      y: [-6, 2],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 1, numbers: false },
        { id: "origin", kind: "point", at: [0, 0], color: "gray" },
        { id: "para", kind: "fn", y: "-2(x - h)^2 + k", params: { h: 0, k: 0 }, color: "white" },
        { id: "left", kind: "seg", from: [0, 0.6], to: [-3, 0.6], arrow: true, color: "blue", label: "left 3" },
        { id: "down", kind: "seg", from: [-3.5, 0], to: [-3.5, -1], arrow: true, color: "orange", label: "down 1", labelOffset: [-26, 4] },
        { id: "vertex", kind: "point", at: [-3, -1], color: "green", label: "(−3, −1)", labelOffset: [8, 28] },
        { id: "wrong", kind: "point", at: [3, -1], open: true, color: "gray", label: "(3, −1)", labelOffset: [-26, 28] },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Modeling Growth and Decay with Exponential Functions",
    example: 0,
    hook: "When something changes by a percent every year, it doesn't lose the same amount each time. That's the whole trick.",
    idea: [
      { point: "Percent per period → exponential", say: "A percent of the current amount, again and again, means multiplying. That's exponential, not linear." },
      { point: "Growth: 1 + r. Decay: 1 − r.", say: "The base is what's left after each period. Growing by a rate, use one plus it. Shrinking, use one minus it." },
    ],
    steps: [
      {
        say: "The car loses twelve percent a year, starting from thirty thousand dollars.",
        highlight: ["decreases by 12% each year", "$30,000"],
        work: "value = 30000",
        note: "start",
        focus: ["start"],
      },
      {
        say: "If it loses twelve percent, it keeps eighty-eight percent. So each year, the value shrinks to point eight eight of itself.",
        work: "1 − 0.12 = 0.88",
        note: "decay: 1 − rate",
        draw: ["rider"],
        set: [{ id: "rider", at: [1, 26.4] }],
        focus: ["rider", "start"],
      },
      {
        say: "Multiply by point eight eight once for each year. Two years, so square it.",
        work: "value = 30000(0.88)^2",
        note: "one factor per year",
        draw: ["curve"],
        set: [{ id: "rider", at: [2, 23.232] }],
        focus: ["rider", "curve"],
      },
      {
        say: "Point one two is what the car loses, not what it keeps. That base would crash the value almost to zero.",
        draw: ["wrong"],
        focus: ["wrong"],
        strike: [1],
      },
      {
        say: "Subtracting twelve percent of the original twice is linear, a straight drop. And one point one two would mean the value is growing.",
        draw: ["lin"],
        focus: ["lin", "curve"],
        strike: [2, 3],
      },
    ],
    answer: "Thirty thousand times point eight eight squared. That's about twenty-three thousand two hundred dollars.",
    trap: { point: "Trap: using the rate as the base", say: "Point one two is the loss. The base is what remains, point eight eight." },
    recap: { point: "Base = what's left each period", say: "Percent change each period means exponential. Build the base from what's left, then raise it to the number of periods." },
    tint: { "30000": "yellow", "0.88": "blue", "0.12": "orange" },
    // Value in thousands: 30, then 26.4, then 23.232 after two years.
    scene: {
      x: [-0.35, 4.2],
      y: [12, 32.5],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, numbers: false },
        { id: "start", kind: "point", at: [0, 30], color: "yellow", label: "$30,000" },
        { id: "curve", kind: "fn", y: "30(0.88)^x", domain: [0, 5], color: "blue" },
        { id: "rider", kind: "point", at: [0, 30], color: "blue", label: "×0.88", labelOffset: [-4, 28] },
        { id: "wrong", kind: "fn", y: "30(0.12)^x", domain: [0, 5], dash: true, color: "orange" },
        { id: "lin", kind: "fn", y: "30 - 3.6x", domain: [0, 5], dash: true, color: "gray" },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Initial Value and Growth Factor in Any Exponential Form",
    example: 1,
    hook: "Every exponential has two numbers that matter: where it starts, and what it multiplies by. A table shows you both.",
    idea: [
      { point: "a = f(0), the starting value", say: "In a times b to the x, a is the value at x equals zero. It's also the y-intercept." },
      { point: "b = next output ÷ previous output", say: "B is the factor. Divide any output by the one before it, and check that it holds every time." },
    ],
    steps: [
      {
        say: "Here's the table as points. The x equals zero point sits at three hundred twenty on the y-axis, so that's a.",
        work: "f(0) = 320, so a = 320",
        note: "read the x = 0 row",
        focus: ["p0"],
      },
      {
        say: "Now divide each output by the one before it. Eighty over three twenty is one fourth. The height drops to a quarter.",
        work: "80/320 = 1/4",
        note: "divide, don't subtract",
        draw: ["s1"],
        focus: ["p0", "p1", "s1"],
      },
      {
        say: "Twenty over eighty, five over twenty. Every step is one fourth, so that's the base.",
        work: "20/80 = 1/4, 5/20 = 1/4",
        note: "same ratio every row",
        draw: ["s2", "s3"],
        focus: ["p1", "p2", "p3", "s2", "s3"],
      },
      {
        say: "Put them together: three twenty times one fourth to the x. The curve runs through every point.",
        work: "f(x) = 320(1/4)^x",
        note: "a(b)^x",
        draw: ["curve"],
        focus: ["curve", "p0", "p1", "p2", "p3"],
      },
      {
        say: "A base of four would make the outputs grow. And eighty is the value at x equals one, not the start.",
        strike: [0, 2],
      },
      {
        say: "One fourth in front with three twenty as the base just swaps the two jobs.",
        strike: [1],
      },
    ],
    answer: "Three hundred twenty times one fourth to the x. Start at three twenty, and multiply by one fourth each step.",
    trap: { point: "Trap: a start value that isn't f(0)", say: "The starting value comes from the x equals zero row, not just whichever row you see first." },
    recap: { point: "a from x = 0, b from dividing", say: "Read a where x is zero. Divide neighboring outputs to get b. Then check it on every row." },
    tint: { "320": "yellow", "1/4": "blue" },
    // The table's four rows as points; each drop keeps a quarter.
    scene: {
      x: [-0.5, 3.7],
      y: [-30, 360],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 100 },
        { id: "p0", kind: "point", at: [0, 320], color: "yellow", label: "320" },
        { id: "p1", kind: "point", at: [1, 80], color: "white", label: "80" },
        { id: "p2", kind: "point", at: [2, 20], color: "white", label: "20" },
        { id: "p3", kind: "point", at: [3, 5], color: "white", label: "5" },
        { id: "s1", kind: "seg", from: [1, 320], to: [1, 80], arrow: true, dash: true, color: "blue", label: "×1/4", labelOffset: [30, 0] },
        { id: "s2", kind: "seg", from: [2, 80], to: [2, 20], arrow: true, dash: true, color: "blue" },
        { id: "s3", kind: "seg", from: [3, 20], to: [3, 5], arrow: true, dash: true, color: "blue" },
        { id: "curve", kind: "fn", y: "320(0.25)^x", domain: [-0.2, 3.7], color: "blue" },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Exponential Models with a Time Period in the Exponent",
    example: 2,
    hook: "Doubling every fifteen years doesn't mean doubling every year. Count the periods first, then do the multiplying.",
    idea: [
      { point: "t/k = number of periods", say: "In a model like two to the t over k, the t over k counts how many full periods have passed." },
      { point: "n doublings: × 2^n, not × 2n", say: "Each period multiplies by the base again. Three doublings is two times two times two, which is eight." },
    ],
    steps: [
      {
        say: "From nineteen eighty to twenty twenty-five is forty-five years. Thirty-six thousand is where the curve ends up.",
        highlight: ["doubled every 15 years", "36,000"],
        work: "2025 − 1980 = 45 years",
        note: "time that passed",
        draw: ["span"],
        focus: ["span", "end"],
      },
      {
        say: "Fifteen years per doubling, so that's three doublings.",
        work: "45/15 = 3 doublings",
        note: "count the periods",
        draw: ["curve"],
        focus: ["curve"],
      },
      {
        say: "Three doublings multiply by two cubed, which is eight. So the old population times eight is thirty-six thousand.",
        work: "P · 2³ = 36,000",
        note: "×2 once per period",
        focus: ["curve", "end"],
      },
      {
        say: "To go back in time, divide. Halve it three times, fifteen years at a step. Thirty-six thousand over eight is four thousand five hundred.",
        work: "P = 36,000/8 = 4,500",
        note: "÷8 both sides",
        draw: ["h30", "h15", "h0"],
        focus: ["h30", "h15", "h0", "end"],
      },
      {
        say: "Twelve thousand divides by three, as if the town only tripled. Six thousand treats three doublings as times six.",
        strike: [0, 2],
      },
      {
        say: "Two hundred eighty-eight thousand multiplies by eight, which runs forward to twenty seventy instead of back.",
        strike: [3],
      },
    ],
    answer: "Four thousand five hundred. Double it three times and you land right on thirty-six thousand.",
    trap: { point: "Trap: 3 doublings is × 8, not × 6", say: "Repeated doubling multiplies. Three doublings is times eight, never times six." },
    recap: { point: "Count periods, then use base^periods", say: "Divide the time by the period length, then multiply or divide by the base once per period." },
    tint: { "36,000": "yellow", "4,500": "green", "45": "orange", "3": "orange" },
    // Years since 1980 across, thousands up: 4.5 → 9 → 18 → 36.
    scene: {
      x: [-4, 51],
      y: [-4, 41],
      objects: [
        { id: "axes", kind: "axes", xStep: 15, yStep: 10, numbers: false },
        { id: "end", kind: "point", at: [45, 36], color: "yellow", label: "36,000", labelOffset: [-62, 0] },
        { id: "span", kind: "seg", from: [0, -2], to: [45, -2], arrow: true, color: "orange", label: "45 years", labelOffset: [0, 30] },
        { id: "curve", kind: "fn", y: "4.5 * 2^(x/15)", domain: [0, 45], color: "blue" },
        { id: "h30", kind: "point", at: [30, 18], color: "green", label: "÷2", labelOffset: [0, 0] },
        { id: "h15", kind: "point", at: [15, 9], color: "green", label: "÷2", labelOffset: [0, 0] },
        { id: "h0", kind: "point", at: [0, 4.5], color: "green", label: "4,500", labelOffset: [0, -4] },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Telling Linear from Exponential Growth (Table, Graph, or Words)",
    example: 5,
    hook: "Linear adds the same amount each step. Exponential multiplies by the same amount. Every one of these comes down to that.",
    idea: [
      { point: "Same difference → linear", say: "If the output changes by the same amount each time x goes up by one, it's linear." },
      { point: "Same ratio → exponential", say: "If it's multiplied by the same factor each time, it's exponential. Check at least two steps before you decide." },
      { point: "Read direction left to right", say: "Then read the graph left to right to decide increasing or decreasing." },
    ],
    steps: [
      {
        say: "The marked points go eight, four, two, one.",
        highlight: ["(0, 8), (1, 4), (2, 2), and (3, 1)"],
        focus: ["p0", "p1", "p2", "p3"],
      },
      {
        say: "The drops are four, then two, then one. Watch the orange drops shrink. They're not the same, so it isn't a line.",
        work: "drops: 4 ≠ 2 ≠ 1",
        note: "differences change",
        draw: ["d1", "d2", "d3"],
        focus: ["d1", "d2", "d3"],
      },
      {
        say: "But each point is half the one before. Same factor every time: that's exponential.",
        work: "4/8 = 2/4 = 1/2",
        note: "constant ratio",
        focus: ["p0", "p1", "p2", "p3", "curve"],
      },
      {
        say: "Left to right, the values fall. So it's decreasing.",
        work: "8 > 4 > 2 > 1",
        note: "falling left to right",
        draw: ["rider"],
        set: [{ id: "rider", at: [3, 1] }],
        focus: ["rider", "curve"],
      },
      {
        say: "Both linear choices need a straight line, changing by the same amount every step. A line through the first two points misses the rest.",
        draw: ["lin"],
        focus: ["lin", "p2", "p3"],
        strike: [0, 1],
      },
      {
        say: "The curve bends upward as it flattens out, but the values keep getting smaller. It isn't increasing.",
        strike: [3],
      },
    ],
    answer: "Decreasing exponential. It halves every step, flattening toward the x axis as it goes.",
    trap: { point: "Trap: calling a flattening curve increasing", say: "A decaying curve bends upward as it levels off. Look at the y values, not the bend." },
    recap: { point: "Differences → linear. Ratios → exponential.", say: "Check the differences and the ratios. Whichever stays constant names the function, and left to right gives the direction." },
    tint: { "1/2": "blue" },
    // The figure's curve y = 8(1/2)^x and its four marked points.
    scene: {
      x: [-0.6, 5.5],
      y: [-0.8, 9.2],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 2 },
        { id: "curve", kind: "fn", y: "8(0.5)^x", domain: [-0.2, 5.5], color: "blue" },
        { id: "p0", kind: "point", at: [0, 8], label: "8" },
        { id: "p1", kind: "point", at: [1, 4], label: "4" },
        { id: "p2", kind: "point", at: [2, 2], label: "2" },
        { id: "p3", kind: "point", at: [3, 1], label: "1" },
        { id: "d1", kind: "seg", from: [1, 8], to: [1, 4], color: "orange", width: 4 },
        { id: "d2", kind: "seg", from: [2, 4], to: [2, 2], color: "orange", width: 4 },
        { id: "d3", kind: "seg", from: [3, 2], to: [3, 1], color: "orange", width: 4 },
        { id: "rider", kind: "point", at: [0, 8], color: "blue" },
        { id: "lin", kind: "line", through: [[0, 8], [1, 4]], dash: true, color: "gray" },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Graph Transformations (Shifts)",
    example: 3,
    hook: "A shift moves every point on a graph the same way. Track one point and you've tracked them all.",
    idea: [
      { point: "Outside the function: up or down", say: "A number added outside the function moves the graph up or down, the way the sign says." },
      { point: "Inside: left or right, backwards", say: "A number inside the parentheses moves it sideways, and backwards from how it looks. Minus four goes right." },
    ],
    steps: [
      {
        say: "The maximum of f is at one, nine. Any hill with that peak will do. Track the peak.",
        highlight: ["maximum point at (1, 9)"],
        focus: ["f", "peak"],
      },
      {
        say: "Minus four inside the parentheses shifts right by four. Add four to x.",
        highlight: ["f(x - 4)"],
        work: "x: 1 + 4 = 5",
        note: "inside −4: right 4",
        set: [{ id: "g", params: { h: 5 } }, { id: "top", at: [5, 9] }],
        draw: ["right"],
        focus: ["g", "top", "right"],
      },
      {
        say: "Minus two outside shifts down by two. Subtract two from y.",
        work: "y: 9 − 2 = 7",
        note: "outside −2: down 2",
        set: [{ id: "g", params: { k: 7 } }, { id: "top", at: [5, 7] }],
        draw: ["down"],
        focus: ["g", "top", "down"],
      },
      {
        say: "So the maximum moves to five, seven.",
        work: "max of g = (5, 7)",
        draw: ["ans"],
        focus: ["ans", "g"],
      },
      {
        say: "Negative three, seven shifts left, reading the inside sign at face value.",
        draw: ["wrong"],
        focus: ["wrong"],
        strike: [1],
      },
      {
        say: "The two with eleven add two, when the minus sign outside says go down.",
        strike: [2, 3],
      },
    ],
    answer: "Five, seven. Right four, down two.",
    trap: { point: "Trap: f(x − 4) moving left", say: "Minus inside means right, plus inside means left. It's the one place the sign lies to you." },
    recap: { point: "Inside flips direction; outside doesn't", say: "Move one key point. Inside numbers shift it sideways, opposite the sign. Outside numbers shift it up or down, with the sign." },
    tint: { "4": "blue", "2": "orange", "5": "green", "7": "green" },
    // A sample f with its peak at (1, 9); g is the same hill moved.
    scene: {
      x: [-4.5, 9],
      y: [-2, 11.5],
      objects: [
        { id: "axes", kind: "axes", xStep: 2, yStep: 2, numbers: false },
        { id: "f", kind: "fn", y: "9 - (x - 1)^2", dash: true, color: "gray" },
        { id: "peak", kind: "point", at: [1, 9], color: "gray", label: "(1, 9)", labelOffset: [-58, 0] },
        { id: "g", kind: "fn", y: "k - (x - h)^2", params: { h: 1, k: 9 }, color: "white" },
        { id: "top", kind: "point", at: [1, 9], color: "white" },
        { id: "right", kind: "seg", from: [1, 10.3], to: [5, 10.3], arrow: true, color: "blue", label: "right 4" },
        { id: "down", kind: "seg", from: [5.7, 9], to: [5.7, 7], arrow: true, color: "orange", label: "down 2", labelOffset: [52, 14] },
        { id: "ans", kind: "point", at: [5, 7], color: "green", label: "(5, 7)", labelOffset: [-60, -2] },
        { id: "wrong", kind: "point", at: [-3, 7], open: true, color: "gray", label: "(−3, 7)", labelOffset: [-22, 28] },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Minimum, Maximum, and Asymptote Reasoning for Exponential Functions",
    example: 3,
    hook: "Exponential functions don't have a vertex. They have a level they creep toward and never quite touch.",
    idea: [
      { point: "a·b^x + c levels off at c", say: "In a times b to the x, plus c, the exponential part fades toward zero, so the function levels off at c." },
      { point: "Signs decide floor or ceiling", say: "Whether c is a floor or a ceiling depends on the signs of a and b. The level itself is always c." },
    ],
    steps: [
      {
        say: "The coffee's model is seventy times point nine to the t, plus sixty-eight. Here's its curve, cooling.",
        highlight: ["T(t) = 70(0.9)^t + 68"],
        work: "T(t) = 70(0.9)^t + 68",
        draw: ["temp"],
        focus: ["temp"],
      },
      {
        say: "Point nine is less than one, so every minute that part shrinks. The orange part on its own heads toward zero.",
        work: "70(0.9)^t gets close to 0",
        note: "base under 1: shrinks",
        draw: ["part"],
        focus: ["part"],
      },
      {
        say: "Seventy times almost nothing is still almost nothing. Only the sixty-eight is left over.",
        work: "T gets close to 0 + 68",
        note: "a · (tiny) is tiny",
        focus: ["part", "temp"],
      },
      {
        say: "So it levels off at sixty-eight. That's room temperature, the floor it cools toward and never quite reaches.",
        work: "T gets close to 68",
        note: "only c survives",
        draw: ["floor"],
        focus: ["floor", "temp"],
      },
      {
        say: "Seventy is the coefficient and point nine is the base. Neither one is where it levels off.",
        strike: [1, 2],
      },
      {
        say: "One thirty-eight is seventy plus sixty-eight. That's the temperature when it was poured, not where it ends up.",
        draw: ["poured"],
        focus: ["poured"],
        strike: [3],
      },
    ],
    answer: "Sixty-eight degrees. The coffee cools toward the room and never quite gets there.",
    trap: { point: "Trap: using the coefficient as the limit", say: "The number in front shrinks away. The level comes from the constant added at the end." },
    recap: { point: "Level-off value = the added constant", say: "Let the exponential part fade to zero. Whatever's left over is where the function levels off." },
    tint: { "68": "green", "70": "orange", "0.9": "orange" },
    // T = 70(0.9)^t + 68 starts at 138 and sinks toward 68.
    scene: {
      x: [-3, 46],
      y: [-12, 150],
      objects: [
        { id: "axes", kind: "axes", xStep: 10, yStep: 50 },
        { id: "temp", kind: "fn", y: "70(0.9)^x + 68", domain: [0, 46], color: "blue" },
        { id: "part", kind: "fn", y: "70(0.9)^x", domain: [0, 46], dash: true, color: "orange" },
        { id: "floor", kind: "seg", from: [0, 68], to: [46, 68], dash: true, color: "green", label: "68", labelOffset: [40, 28] },
        { id: "poured", kind: "point", at: [0, 138], color: "white", label: "138" },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Finding the Vertex of a Quadratic from Standard or Factored Form",
    example: 0,
    hook: "Standard form hides the vertex. One short formula digs it out.",
    idea: [
      { point: "Vertex x = −b/2a", say: "The vertex's x value is always negative b over two a." },
      { point: "Plug x back in for y", say: "Then plug that x back into the function to get the y value." },
    ],
    steps: [
      {
        say: "Here a is one and b is negative six. The vertex is the bottom of this parabola.",
        highlight: ["x² - 6x + 5"],
        work: "a = 1, b = −6",
        note: "read a and b",
        focus: ["para"],
      },
      {
        say: "Negative b over two a. The negative of negative six is positive six, over two. That's three, the parabola's line of symmetry.",
        work: "x = −(−6)/(2 · 1) = 3",
        note: "−b/2a",
        draw: ["axis"],
        focus: ["axis", "para"],
      },
      {
        say: "Plug in three to get the height there. Nine minus eighteen plus five.",
        work: "f(3) = 9 − 18 + 5",
        note: "plug in x = 3",
        draw: ["drop"],
        focus: ["drop"],
      },
      {
        say: "That's negative four. So the vertex is three, negative four.",
        work: "f(3) = −4, vertex (3, −4)",
        note: "add it up",
        draw: ["vertex"],
        focus: ["vertex"],
      },
      {
        say: "Negative three is a sign slip in the formula. Positive four is an arithmetic slip. Neither is on the bottom.",
        draw: ["w1", "w2"],
        focus: ["w1", "w2", "vertex"],
        strike: [1, 2],
      },
      {
        say: "Six, five just reads b and c off the equation. Those aren't coordinates of the vertex.",
        strike: [3],
      },
    ],
    answer: "Three, negative four. The formula gives x, and plugging in gives y.",
    trap: { point: "Trap: double negatives in −b/2a", say: "When b is negative, negative b is positive. That's where most points get lost here." },
    recap: { point: "−b/2a, then plug in", say: "Find x with negative b over two a, then plug it back in. The vertex needs both numbers." },
    tint: { "3": "orange", "4": "green" },
    // y = x² − 6x + 5: roots 1 and 5, symmetric about x = 3, vertex (3, −4).
    scene: {
      x: [-4.5, 7.5],
      y: [-6, 7],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 1, numbers: false },
        { id: "para", kind: "fn", y: "x^2 - 6x + 5", color: "blue" },
        { id: "axis", kind: "seg", from: [3, -5.8], to: [3, 6.8], dash: true, color: "orange", label: "x = 3", labelOffset: [24, -46] },
        { id: "drop", kind: "seg", from: [3, 0], to: [3, -4], color: "green", width: 4 },
        { id: "vertex", kind: "point", at: [3, -4], color: "green", label: "(3, −4)", labelOffset: [4, 26] },
        { id: "w1", kind: "point", at: [-3, -4], open: true, color: "gray", label: "(−3, −4)", labelOffset: [-20, 26] },
        { id: "w2", kind: "point", at: [3, 4], open: true, color: "gray", label: "(3, 4)" },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Evaluating a Function and Interpreting Its Output in Context",
    example: 4,
    hook: "Sometimes they give you the output and ask for the input. Then you're running the function backward.",
    idea: [
      { point: "Output given? Set f(x) equal to it", say: "If they tell you the output, set the function equal to it and solve for the input." },
      { point: "Keep only answers that fit", say: "Then check each solution against the story. A negative width or time gets thrown out." },
    ],
    steps: [
      {
        say: "The garden is x wide and x plus six long. Its area is x times x plus six, and it equals forty.",
        highlight: ["A(x) = x(x + 6)", "40 square feet"],
        work: "x(x + 6) = 40",
        note: "set A(x) = 40",
        focus: ["sq", "strip", "wx", "w6", "hx"],
      },
      {
        say: "Multiply out: an x by x square plus an x by six strip. Then move the forty over, so one side is zero.",
        work: "x² + 6x − 40 = 0",
        note: "−40 both sides",
        focus: ["sq", "strip"],
      },
      {
        say: "Two numbers that multiply to negative forty and add to six: ten and negative four.",
        work: "(x + 10)(x − 4) = 0",
        note: "factor",
      },
      {
        say: "So x is negative ten or four.",
        work: "x = −10 or x = 4",
        note: "each factor = 0",
        focus: ["hx", "wx"],
      },
      {
        say: "A garden can't be negative ten feet wide. So it's four, and four times ten is forty. The picture fits exactly.",
        work: "width > 0, so x = 4",
        note: "check the context",
        draw: ["check"],
        focus: ["check", "sq", "strip"],
        strike: [0],
      },
      {
        say: "Ten is actually the length, and a width of ten gives one sixty. Thirty-four just subtracts six from forty.",
        strike: [2, 3],
      },
    ],
    answer: "Four feet. Four wide, ten long, forty square feet.",
    trap: { point: "Trap: keeping a root that can't happen", say: "Both roots solve the equation, but only one can be a real width. Check the story." },
    recap: { point: "Set equal, solve, check context", say: "Set the function equal to the output, solve, and keep only the answer that makes sense." },
    tint: { x: "blue", "6x": "yellow", "6": "yellow", "40": "green" },
    // Drawn true to the answer: x = 4, so the garden is 4 by 10.
    scene: {
      x: [-1.6, 11],
      y: [-1.7, 5.4],
      objects: [
        { id: "sq", kind: "poly", pts: [[0, 0], [4, 0], [4, 4], [0, 4]], fill: true, color: "blue", label: "x²" },
        { id: "strip", kind: "poly", pts: [[4, 0], [10, 0], [10, 4], [4, 4]], fill: true, color: "yellow", label: "6x" },
        { id: "hx", kind: "seg", from: [-0.5, 0], to: [-0.5, 4], color: "blue", label: "x" },
        { id: "wx", kind: "seg", from: [0, -0.5], to: [4, -0.5], color: "blue", label: "x", labelOffset: [0, 28] },
        { id: "w6", kind: "seg", from: [4, -0.5], to: [10, -0.5], color: "yellow", label: "6", labelOffset: [0, 28] },
        { id: "check", kind: "text", at: [5, 4.75], text: "4 × 10 = 40", color: "green", size: 16 },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Reading Key Features from a Nonlinear Graph",
    example: 4,
    hook: "A graph can hand you the coefficients, if you know which feature holds which number.",
    idea: [
      { point: "y-intercept of ax² + bx + c is c", say: "Plug in x equals zero and everything drops out except c. So the y-intercept is c." },
      { point: "Vertex x = −b/(2a)", say: "The vertex sits at x equals negative b over two a. Know a, read the vertex, and solve for b." },
    ],
    steps: [
      {
        say: "The graph crosses the y axis at negative three. At x equals zero only c is left, so c is negative three.",
        highlight: ["The vertex and the y-intercept are marked"],
        work: "c = −3",
        note: "y-intercept = c",
        focus: ["yint"],
      },
      {
        say: "The vertex is at x equals two, on the line of symmetry. Set negative b over two a equal to two.",
        work: "−b/(2 · 1/2) = 2",
        note: "vertex x = −b/2a",
        draw: ["axis"],
        focus: ["axis", "vtx"],
      },
      {
        say: "Two times one half is one, so negative b is two, and b is negative two.",
        work: "−b = 2, so b = −2",
        note: "2 · 1/2 = 1",
        focus: ["axis"],
      },
      {
        say: "Multiply them. Negative two times negative three is positive six.",
        work: "bc = (−2)(−3) = 6",
        note: "multiply",
        focus: ["yint", "axis"],
      },
      {
        say: "Negative six loses the sign on b. Ten uses negative five, the vertex's height, as c. But c is where it crosses the y axis.",
        strike: [0, 1],
        focus: ["vtx", "yint"],
      },
      {
        say: "Twelve drops the a from the formula, which makes b negative four.",
        strike: [2],
      },
    ],
    answer: "Six. The y-intercept gave c, and the vertex gave b.",
    trap: { point: "Trap: using the vertex's height as c", say: "C is where the graph crosses the y axis, not its lowest point. Those are different here." },
    recap: { point: "y-intercept → c. Vertex → b.", say: "Name the feature, then find where it lives. The y-intercept gives c, and the vertex's x value gives b." },
    tint: { c: "yellow", "3": "yellow", b: "orange" },
    // The figure's curve y = ½x² − 2x − 3: y-intercept (0, −3), vertex (2, −5).
    scene: {
      x: [-3, 7],
      y: [-6.2, 4],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 1, numbers: false },
        { id: "para", kind: "fn", y: "0.5x^2 - 2x - 3", color: "blue" },
        { id: "yint", kind: "point", at: [0, -3], color: "yellow", label: "(0, −3)", labelOffset: [-66, 0] },
        { id: "vtx", kind: "point", at: [2, -5], color: "white", label: "(2, −5)", labelOffset: [4, 24] },
        { id: "axis", kind: "seg", from: [2, -6], to: [2, 3.8], dash: true, color: "orange", label: "x = 2", labelOffset: [44, -40] },
      ],
    },
  },
  {
    subskillId: "m-nonlinear-func",
    pattern: "Zeros, Factors, and x-Intercepts of Polynomials",
    example: 0,
    hook: "A zero, an x-intercept, and a factor are the same fact written three ways.",
    idea: [
      { point: "Zero at a → factor (x − a)", say: "If p of a is zero, the graph hits the x axis at a, and x minus a is a factor." },
      { point: "Factor sign is opposite the zero", say: "So the sign in the factor is always the opposite of the zero. A zero at negative two gives x plus two." },
    ],
    steps: [
      {
        say: "The graph crosses the x axis at negative two, one, and four.",
        highlight: ["crosses the x-axis only at the marked points"],
        focus: ["z2", "z1", "z4"],
      },
      {
        say: "Each crossing is a zero. Write x minus each one.",
        work: "x = −2 or 1 or 4",
        note: "read the crossings",
        focus: ["z2", "z1", "z4"],
      },
      {
        say: "X minus negative two is x plus two. The line y equals x plus two hits zero right at negative two, too.",
        work: "x − (−2) = x + 2",
        note: "factor: x − zero",
        draw: ["fac"],
        focus: ["fac", "z2"],
      },
      {
        say: "The other two factors are x minus one and x minus four.",
        work: "(x + 2)(x − 1)(x − 4)",
        note: "one per zero",
        focus: ["z2", "z1", "z4", "curve"],
      },
      {
        say: "X minus two would mean a zero at positive two, and the graph doesn't cross there. It's below the axis.",
        draw: ["w2"],
        focus: ["w2", "curve"],
        strike: [1],
      },
      {
        say: "X plus one and x plus four flip the signs. Those zeros give x minus one and x minus four.",
        strike: [2, 3],
      },
    ],
    answer: "X plus two. The crossing at negative two, with the sign flipped.",
    trap: { point: "Trap: copying the zero's sign into the factor", say: "A zero at negative two means x plus two. The factor and the zero always have opposite signs." },
    recap: { point: "Zero a → factor (x − a)", say: "Read each crossing, then write x minus that number. Watch the double negative." },
    tint: { "2": "green" },
    // The figure's cubic, y = ¼(x + 2)(x − 1)(x − 4); p(2) = −2.
    scene: {
      x: [-3, 5.2],
      y: [-4, 4],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 1, numbers: false },
        { id: "curve", kind: "fn", y: "0.25(x + 2)(x - 1)(x - 4)", color: "blue" },
        { id: "z2", kind: "point", at: [-2, 0], color: "green", label: "−2", labelOffset: [-34, 0] },
        { id: "z1", kind: "point", at: [1, 0], color: "white", label: "1" },
        { id: "z4", kind: "point", at: [4, 0], color: "white", label: "4", labelOffset: [-22, 0] },
        { id: "fac", kind: "line", through: [[-2, 0], [0, 2]], dash: true, color: "green", label: "y = x + 2", labelOffset: [-4, 34] },
        { id: "w2", kind: "point", at: [2, 0], open: true, color: "gray", label: "2", labelOffset: [-4, 26] },
      ],
    },
  },
];
