import type { LessonVideoScript } from "../../types";

export const M_ONE_VAR_DATA: LessonVideoScript[] = [
  {
    subskillId: "m-one-var-data",
    pattern: "Comparing Mean and Median to Detect Skew",
    example: 1,
    hook: "One mansion on the block, and suddenly the average house looks way pricier than it is.",
    idea: [
      { point: "Outliers drag the mean", say: "The mean uses every value, so one extreme value drags it toward itself." },
      { point: "The median barely moves", say: "The median only cares about the middle of the sorted list, so outliers barely touch it." },
      { point: "Mean > median → high outliers", say: "If the mean sits well above the median, a few high values are pulling it up. That's right skew." },
    ],
    steps: [
      {
        say: "Five sale prices, in thousands. One of them, eight ninety, is way off from the rest.",
        highlight: ["240, 210, 890, 230, 225"],
        focus: ["p890"],
      },
      {
        say: "Sort them first. Watch them shuffle into order. The median is the middle of the sorted list, not the list as given.",
        work: "210 < 225 < 230 < 240 < 890",
        note: "sort first",
        set: [
          { id: "p210", at: [250, 3.2] },
          { id: "p225", at: [390, 3.2] },
          { id: "p230", at: [530, 3.2] },
          { id: "p240", at: [670, 3.2] },
          { id: "p890", at: [810, 3.2] },
        ],
      },
      {
        say: "Five values, so the median is the third one. Two thirty.",
        work: "median = 230",
        note: "middle of five",
        focus: ["p230"],
      },
      {
        say: "Now the mean. Everything adds to seventeen ninety-five, over five is three fifty-nine. On a number line, see how far the outlier drags it.",
        work: "mean = 1,795 / 5 = 359",
        note: "pulled up by 890",
        draw: ["nl", "c1", "c5", "med", "mean"],
        focus: ["c1", "c5", "med", "mean"],
      },
      {
        say: "So three fifty-nine is the mean, not the median. And eight ninety is the outlier itself.",
        strike: [1, 2],
        focus: ["mean", "c5"],
      },
      {
        say: "Two twenty-five is second in the sorted list. The middle is one spot over.",
        strike: [3],
        focus: ["p225", "p230"],
      },
    ],
    answer: "Two thirty. The median stays with the typical homes while the mean chases the big sale.",
    trap: { point: "Trap: forgetting to sort", say: "The median is the middle of the sorted list. Pick the middle of the list as given, and you'll land on the wrong value." },
    recap: { point: "Mean follows outliers; median resists", say: "Outliers pull the mean toward them. The median holds steady, so it shows a typical value better." },
    tint: { "230": "green", median: "green", "359": "orange", mean: "orange" },
    scene: {
      x: [170, 930],
      y: [-1.6, 4.2],
      objects: [
        { id: "p240", kind: "point", at: [250, 3.2], label: "240" },
        { id: "p210", kind: "point", at: [390, 3.2], label: "210" },
        { id: "p890", kind: "point", at: [530, 3.2], label: "890" },
        { id: "p230", kind: "point", at: [670, 3.2], label: "230" },
        { id: "p225", kind: "point", at: [810, 3.2], label: "225" },
        { id: "nl", kind: "numline", y: 0, min: 200, max: 900, step: 100 },
        { id: "c1", kind: "seg", from: [210, 0.55], to: [240, 0.55], width: 9 },
        { id: "c5", kind: "point", at: [890, 0.55] },
        { id: "med", kind: "seg", from: [230, 0], to: [230, 1.9], color: "green", label: "median", labelOffset: [8, -22] },
        { id: "mean", kind: "seg", from: [359, 0], to: [359, 1.9], color: "orange", label: "mean", labelOffset: [34, -22] },
      ],
    },
  },
  {
    subskillId: "m-one-var-data",
    pattern: "Interpreting Standard Deviation as Spread",
    example: 1,
    hook: "Two classes, same average. Totally different stories.",
    idea: [
      { point: "Standard deviation = spread, not center", say: "Standard deviation measures how far values typically sit from the mean. It says nothing about how big the mean is." },
      { point: "Same mean, different spread: fine", say: "Two data sets can share a mean and still have very different standard deviations." },
    ],
    steps: [
      {
        say: "Both classes have a mean of seventy-eight. So the center is a tie, and the question is all about spread.",
        highlight: ["mean of 78", "same mean of 78"],
        work: "mean A = mean B = 78",
        note: "center: a tie",
        draw: ["meanLine"],
        focus: ["meanLine"],
      },
      {
        say: "Class A is tightly clustered near seventy-eight. Class B runs all the way from forty to a hundred.",
        highlight: ["tightly clustered", "from 40 to 100"],
        work: "spread B > spread A",
        note: "spread decides",
        draw: ["spanA", "spanB"],
        focus: ["spanA", "spanB"],
      },
      {
        say: "Wider spread around the same mean means a bigger standard deviation. That's Class B, so the Class A choice has them backwards.",
        work: "SD of B > SD of A",
        note: "wider → bigger SD",
        focus: ["spanB", "b1", "b2", "b3", "b4", "b5", "meanLine"],
        strike: [1],
      },
      {
        say: "Sharing a mean doesn't mean sharing a spread. And the descriptions are enough to decide, even without every score.",
        strike: [2, 3],
      },
    ],
    answer: "Class B. Its scores wander much farther from seventy-eight.",
    trap: { point: "Trap: mixing up spread and center", say: "Standard deviation and the mean answer different questions. One is how spread out, the other is where the middle is." },
    recap: { point: "Bigger standard deviation = more spread out", say: "A bigger standard deviation means values sit farther from the mean. That's less consistent, not bigger." },
    tint: { "78": "yellow", A: "blue", B: "orange" },
    scene: {
      x: [33, 104],
      y: [-1.4, 7.4],
      objects: [
        { id: "nlA", kind: "numline", y: 3.4, min: 40, max: 100, step: 10, numbers: false, color: "gray" },
        { id: "nlB", kind: "numline", y: 0, min: 40, max: 100, step: 10 },
        { id: "tA", kind: "text", at: [35, 3.1], text: "A", color: "blue" },
        { id: "tB", kind: "text", at: [35, -0.3], text: "B", color: "orange" },
        { id: "a1", kind: "point", at: [71, 4.1], color: "blue" },
        { id: "a2", kind: "point", at: [74.5, 4.1], color: "blue" },
        { id: "a3", kind: "point", at: [78, 4.1], color: "blue" },
        { id: "a4", kind: "point", at: [81.5, 4.1], color: "blue" },
        { id: "a5", kind: "point", at: [85, 4.1], color: "blue" },
        { id: "b1", kind: "point", at: [40, 0.7], color: "orange" },
        { id: "b2", kind: "point", at: [70, 0.7], color: "orange" },
        { id: "b3", kind: "point", at: [86, 0.7], color: "orange" },
        { id: "b4", kind: "point", at: [94, 0.7], color: "orange" },
        { id: "b5", kind: "point", at: [100, 0.7], color: "orange" },
        { id: "meanLine", kind: "seg", from: [78, -0.3], to: [78, 6.2], dash: true, color: "yellow", label: "78", labelOffset: [-4, 12] },
        { id: "spanA", kind: "seg", from: [71, 5.3], to: [85, 5.3], width: 3, color: "blue" },
        { id: "spanB", kind: "seg", from: [40, 1.9], to: [100, 1.9], width: 3, color: "orange" },
      ],
    },
  },
  {
    subskillId: "m-one-var-data",
    pattern: "Reading Values and Basic Statistics Directly from a Graph or Table",
    example: 4,
    hook: "Two sections, two averages. You can't just average the averages.",
    idea: [
      { point: "Read the exact row you need", say: "Most of these are careful reading. Find the right row or bar, and read its value exactly." },
      { point: "total = count × mean", say: "To combine groups, turn each mean back into a total. The count times the mean gives the total." },
      { point: "Add totals, divide by everyone", say: "Add the totals, then divide by the combined count. Bigger groups count for more." },
    ],
    steps: [
      {
        say: "Section A has eighteen students with a mean of eighty-four. Count times mean: fifteen hundred twelve points. That's the blue block.",
        highlight: ["all 30 students"],
        work: "A: 18 × 84 = 1,512",
        note: "total = count × mean",
        draw: ["rA", "tA"],
        focus: ["rA", "tA"],
      },
      {
        say: "Section B has twelve students with a mean of seventy-nine. Nine hundred forty-eight points, the orange block.",
        work: "B: 12 × 79 = 948",
        note: "total = count × mean",
        draw: ["rB", "tB"],
        focus: ["rB", "tB"],
      },
      {
        say: "Add the two totals. Two thousand four hundred sixty points in all.",
        work: "1,512 + 948 = 2,460",
        note: "add the totals",
        focus: ["rA", "rB"],
      },
      {
        say: "Divide by all thirty students: eighty-two. Level it off, and A's extra on top exactly fills B's gap, because A is wider.",
        work: "2,460 / 30 = 82",
        note: "÷ all 30 students",
        draw: ["level", "excess", "gap", "t82"],
        focus: ["level", "excess", "gap", "t82"],
      },
      {
        say: "Eighty-one and a half averages the two means as if the sections were the same size. Section A is bigger, so it counts more.",
        strike: [0],
      },
      {
        say: "Eighty-one swaps the class sizes. And twenty-four sixty is the total before dividing.",
        strike: [2, 3],
      },
    ],
    answer: "Eighty-two. It lands closer to eighty-four, because Section A has more students.",
    trap: { point: "Trap: averaging the two means", say: "That only works when the groups are the same size. Here they aren't, so weight each mean by its count." },
    recap: { point: "Combine totals, not means", say: "Turn each mean into a total, add the totals, and divide by the total count." },
    tint: { "18": "blue", "84": "blue", "1,512": "blue", "12": "orange", "79": "orange", "948": "orange", "82": "green" },
    scene: {
      x: [-4, 34.5],
      y: [70, 88.5],
      objects: [
        { id: "axes", kind: "axes", xStep: 6, yStep: 5 },
        { id: "rA", kind: "poly", pts: [[0, 70], [18, 70], [18, 84], [0, 84]], fill: true, color: "blue", label: "18 × 84" },
        { id: "tA", kind: "text", at: [9, 84.7], text: "84", size: 13, color: "blue" },
        { id: "rB", kind: "poly", pts: [[18, 70], [30, 70], [30, 79], [18, 79]], fill: true, color: "orange", label: "12 × 79" },
        { id: "tB", kind: "text", at: [24, 79.7], text: "79", size: 13, color: "orange" },
        { id: "level", kind: "seg", from: [0, 82], to: [30, 82], width: 3, color: "green" },
        { id: "excess", kind: "poly", pts: [[0, 82], [18, 82], [18, 84], [0, 84]], fill: true, color: "yellow" },
        { id: "gap", kind: "poly", pts: [[18, 79], [30, 79], [30, 82], [18, 82]], fill: true, dash: true, color: "yellow" },
        { id: "t82", kind: "text", at: [32.6, 81.4], text: "82", size: 14, color: "green" },
      ],
    },
  },
  {
    subskillId: "m-one-var-data",
    pattern: "How Changing a Data Set Changes Its Statistics",
    example: 2,
    hook: "Add one score to a list, and the mean moves. The question is how far.",
    idea: [
      { point: "Shift every value → mean shifts too", say: "Add the same amount to every value, and the mean and median move by that amount. The range stays put." },
      { point: "New point? Rebuild the total", say: "When one new value joins, rebuild the old total from the mean, add the new value, and divide again." },
    ],
    steps: [
      {
        say: "Five scores with a mean of eighty. Picture them leveled off at eighty. A sixth score of ninety-two joins.",
        highlight: ["Five test scores have a mean of 80", "A sixth score of 92"],
        focus: ["s1", "s2", "s3", "s4", "s5", "m80"],
      },
      {
        say: "Five scores averaging eighty means they add to four hundred.",
        work: "5 × 80 = 400",
        note: "old total",
        focus: ["s1", "s2", "s3", "s4", "s5"],
      },
      {
        say: "Add the new score. Four hundred plus ninety-two is four ninety-two. It sticks up twelve above the line.",
        work: "400 + 92 = 492",
        note: "add the new score",
        draw: ["s6", "p0", "p1", "p2", "p3", "p4", "p5"],
        focus: ["s6", "p0", "p1", "p2", "p3", "p4", "p5"],
      },
      {
        say: "Now divide by six. Share those twelve extra points out, two to each score, and everyone sits at eighty-two.",
        work: "492 / 6 = 82",
        note: "÷ new count",
        move: [
          { id: "p0", by: [-5, 0] },
          { id: "p1", by: [-4, -2] },
          { id: "p2", by: [-3, -4] },
          { id: "p3", by: [-2, -6] },
          { id: "p4", by: [-1, -8] },
          { id: "p5", by: [0, -10] },
        ],
        draw: ["l82", "t82"],
        focus: ["p0", "p1", "p2", "p3", "p4", "p5", "l82", "t82"],
      },
      {
        say: "Eighty-six averages eighty and ninety-two as if they counted equally. But eighty stands for five scores.",
        strike: [1],
      },
      {
        say: "Eighty ignores the new score, which is above the mean and pulls it up. Ninety-two is just the new score.",
        strike: [2, 3],
      },
    ],
    answer: "Eighty-two. One high score nudges the mean up, but only a little.",
    trap: { point: "Trap: averaging old mean with new value", say: "The old mean stands for five scores, not one. Rebuild the total before you add anything." },
    recap: { point: "Mean × count = total, then redo it", say: "Turn the mean into a total, add or remove the value, and divide by the new count." },
    tint: { "80": "blue", "400": "blue", "92": "orange", "82": "green" },
    scene: {
      x: [-1, 7.4],
      y: [70, 93.5],
      objects: [
        { id: "axes", kind: "axes", yStep: 5 },
        { id: "s1", kind: "poly", pts: [[0.7, 70], [1.3, 70], [1.3, 80], [0.7, 80]], fill: true, color: "blue" },
        { id: "s2", kind: "poly", pts: [[1.7, 70], [2.3, 70], [2.3, 80], [1.7, 80]], fill: true, color: "blue" },
        { id: "s3", kind: "poly", pts: [[2.7, 70], [3.3, 70], [3.3, 80], [2.7, 80]], fill: true, color: "blue" },
        { id: "s4", kind: "poly", pts: [[3.7, 70], [4.3, 70], [4.3, 80], [3.7, 80]], fill: true, color: "blue" },
        { id: "s5", kind: "poly", pts: [[4.7, 70], [5.3, 70], [5.3, 80], [4.7, 80]], fill: true, color: "blue" },
        { id: "m80", kind: "seg", from: [0.4, 80], to: [6.7, 80], dash: true, color: "gray" },
        { id: "s6", kind: "poly", pts: [[5.7, 70], [6.3, 70], [6.3, 80], [5.7, 80]], fill: true, color: "orange" },
        { id: "p0", kind: "poly", pts: [[5.7, 80], [6.3, 80], [6.3, 82], [5.7, 82]], fill: true, color: "orange" },
        { id: "p1", kind: "poly", pts: [[5.7, 82], [6.3, 82], [6.3, 84], [5.7, 84]], fill: true, color: "orange" },
        { id: "p2", kind: "poly", pts: [[5.7, 84], [6.3, 84], [6.3, 86], [5.7, 86]], fill: true, color: "orange" },
        { id: "p3", kind: "poly", pts: [[5.7, 86], [6.3, 86], [6.3, 88], [5.7, 88]], fill: true, color: "orange" },
        { id: "p4", kind: "poly", pts: [[5.7, 88], [6.3, 88], [6.3, 90], [5.7, 90]], fill: true, color: "orange" },
        { id: "p5", kind: "poly", pts: [[5.7, 90], [6.3, 90], [6.3, 92], [5.7, 92]], fill: true, color: "orange" },
        { id: "l82", kind: "seg", from: [0.4, 82], to: [6.6, 82], dash: true, color: "green" },
        { id: "t82", kind: "text", at: [7.0, 81.3], text: "82", size: 13, color: "green" },
      ],
    },
  },
];
