import type { LessonVideoScript } from "../../types";

export const M_PERCENTAGES: LessonVideoScript[] = [
  {
    subskillId: "m-percentages",
    pattern: "Straightforward Percent Change and Discount Problems",
    example: 3,
    hook: "Going forward with a discount is easy. Going backward is where people slip.",
    idea: [
      { point: "25% off → pay 75%: × 0.75", say: "Think in multipliers. Twenty-five percent off means you pay seventy-five percent, so multiply by zero point seven five." },
      { point: "To undo a change, divide", say: "To get back to the original, divide by that multiplier. Don't just add the percent back on." },
    ],
    steps: [
      {
        say: "The jacket is twenty percent off, and it now costs sixty-four dollars. We want the price before the sale.",
        highlight: ["After a 20% discount", "$64"],
        focus: ["pay", "off"],
      },
      {
        say: "Twenty percent off means the sale price is the other eighty percent of the original. So zero point eight times the original is sixty-four.",
        work: "0.80 × original = 64",
        note: "pay 80%",
        focus: ["pay"],
      },
      {
        say: "Undo the multiply: divide both sides by zero point eight. In the bar, sixty-four splits into four twenty-percent blocks of sixteen.",
        work: "original = 64 / 0.80",
        note: "÷0.80 both sides",
        draw: ["d1", "d2", "d3", "t1", "t2", "t3", "t4"],
        focus: ["pay", "d1", "d2", "d3", "t1", "t2", "t3", "t4"],
      },
      {
        say: "The missing twenty percent is one more block of sixteen. Five blocks make eighty. The original was eighty dollars.",
        work: "original = 80",
        note: "64 ÷ 0.8",
        draw: ["t5", "brace", "t80"],
        focus: ["off", "t5", "brace", "t80"],
      },
      {
        say: "Seventy-six dollars and eighty cents adds twenty percent of sixty-four. But the twenty percent came off the original, not off sixty-four.",
        strike: [1],
      },
      {
        say: "Fifty-one dollars and twenty cents takes the discount off a second time. And eighty-four just adds twenty dollars back.",
        strike: [2, 3],
      },
    ],
    answer: "Eighty dollars. Check it: twenty percent of eighty is sixteen, and eighty minus sixteen is sixty-four.",
    trap: { point: "Trap: adding the percent back on", say: "The percent was taken from the original price. Adding it to the sale price uses the wrong base." },
    recap: { point: "Forward: multiply. Backward: divide.", say: "Turn the percent into a multiplier. Multiply to go forward, and divide by it to go back." },
    tint: { "64": "yellow", "0.80": "yellow", original: "green", "80": "green" },
    scene: {
      x: [-1, 11],
      y: [-0.7, 5.8],
      objects: [
        { id: "whole", kind: "poly", pts: [[0, 1.6], [10, 1.6], [10, 3.6], [0, 3.6]] },
        { id: "pay", kind: "poly", pts: [[0, 1.6], [8, 1.6], [8, 3.6], [0, 3.6]], fill: true, color: "yellow", label: "$64", labelOffset: [0, -30] },
        { id: "off", kind: "poly", pts: [[8, 1.6], [10, 1.6], [10, 3.6], [8, 3.6]], fill: true, dash: true, color: "gray", label: "20% off", labelOffset: [0, -30] },
        { id: "d1", kind: "seg", from: [2, 1.6], to: [2, 3.6], width: 1.6, color: "yellow" },
        { id: "d2", kind: "seg", from: [4, 1.6], to: [4, 3.6], width: 1.6, color: "yellow" },
        { id: "d3", kind: "seg", from: [6, 1.6], to: [6, 3.6], width: 1.6, color: "yellow" },
        { id: "t1", kind: "text", at: [1, 2.4], text: "16", size: 14, color: "yellow" },
        { id: "t2", kind: "text", at: [3, 2.4], text: "16", size: 14, color: "yellow" },
        { id: "t3", kind: "text", at: [5, 2.4], text: "16", size: 14, color: "yellow" },
        { id: "t4", kind: "text", at: [7, 2.4], text: "16", size: 14, color: "yellow" },
        { id: "t5", kind: "text", at: [9, 2.4], text: "16", size: 14, color: "green" },
        { id: "brace", kind: "seg", from: [0, 1.1], to: [10, 1.1], width: 2.4, color: "green" },
        { id: "t80", kind: "text", at: [5, 0.05], text: "original = $80", size: 14, color: "green" },
      ],
    },
  },
  {
    subskillId: "m-percentages",
    pattern: "Successive Percent Changes (Compounding, Not Additive)",
    example: 0,
    hook: "Up twenty percent, then down twenty percent. Back where you started? Nope.",
    idea: [
      { point: "Changes multiply, they don't add", say: "Percent changes stack by multiplying. Each one is taken from whatever the value is at that moment." },
      { point: "Start at 100 and follow it", say: "The easy way to see it: start with a price of one hundred and apply each change in order." },
    ],
    steps: [
      {
        say: "The price goes up twenty percent, then down twenty percent. Start with a price of one hundred.",
        highlight: ["increases by 20%", "decreases by 20%"],
        focus: ["b100"],
      },
      {
        say: "Up twenty percent means times one point two. Twenty percent of one hundred is twenty, so the bar grows to one hundred twenty.",
        work: "100 × 1.20 = 120",
        note: "+20% → × 1.20",
        draw: ["b120", "add"],
        focus: ["b120", "add"],
      },
      {
        say: "Now down twenty percent, but of one hundred twenty. That's twenty-four, a bigger bite than the twenty we added. Ninety-six is left.",
        work: "120 × 0.80 = 96",
        note: "−20% → × 0.80",
        draw: ["b96", "cut"],
        focus: ["b96", "cut"],
      },
      {
        say: "Compare with the start. Ninety-six falls four short of the dashed line at one hundred.",
        work: "100 − 96 = 4",
        note: "compare to start",
        draw: ["gap"],
        focus: ["ref", "gap", "b96"],
      },
      {
        say: "Four out of the original one hundred is four percent lower. So it's not the same: the drop came from a bigger number.",
        work: "4/100 = 4% lower",
        note: "4 out of 100",
        strike: [1],
      },
      {
        say: "Four percent higher gets the direction wrong, and forty percent lower adds the two percents together.",
        strike: [2, 3],
      },
    ],
    answer: "Four percent lower. One hundred, then one twenty, then ninety-six.",
    trap: { point: "Trap: +20% and −20% cancel", say: "They don't cancel. The second twenty percent is taken from a new, bigger base." },
    recap: { point: "Apply changes in order, as multipliers", say: "Turn each change into a multiplier and apply them one after another. Starting at one hundred makes it easy." },
    tint: { "120": "green", "96": "blue", "4": "yellow", "4%": "yellow" },
    scene: {
      x: [-1, 14.5],
      y: [-0.9, 7.2],
      objects: [
        { id: "ref", kind: "seg", from: [10, -0.4], to: [10, 6.8], dash: true, color: "gray" },
        { id: "b100", kind: "seg", from: [0, 5.6], to: [10, 5.6], width: 10, label: "100" },
        { id: "b120", kind: "seg", from: [0, 3.2], to: [10, 3.2], width: 10, label: "120", labelOffset: [24, 0] },
        { id: "add", kind: "seg", from: [10.25, 3.2], to: [12, 3.2], width: 10, color: "green", label: "+20", labelOffset: [6, 0] },
        { id: "b96", kind: "seg", from: [0, 0.8], to: [9.6, 0.8], width: 10, color: "blue", label: "96" },
        { id: "cut", kind: "seg", from: [9.85, 0.8], to: [12, 0.8], width: 10, dash: true, color: "orange", label: "−24", labelOffset: [14, 26] },
        { id: "gap", kind: "seg", from: [9.6, 2], to: [10, 2], width: 4, color: "yellow", label: "4", labelOffset: [-14, 2] },
      ],
    },
  },
  {
    subskillId: "m-percentages",
    pattern: "Percent, Part, and Whole: Solving for the Missing One",
    example: 5,
    hook: "Every one of these is the same three numbers: a part, a whole, and a percent.",
    idea: [
      { point: "part = percent × whole", say: "The part equals the percent times the whole. You're given two of them, and you find the third." },
      { point: "Percent = part / whole", say: "To find a percent, divide the part by the whole. The whole is what you're comparing to." },
      { point: "Make sure you have the right part", say: "Sometimes the part isn't given directly, and you have to subtract to find it first." },
    ],
    steps: [
      {
        say: "Sixty-three of the one eighty picked option A. The rest picked B, and that's what the question asks about.",
        highlight: ["63 out of 180 respondents preferred option A", "option B"],
        work: "B = 180 − 63",
        note: "the rest",
        draw: ["B"],
        focus: ["A", "B"],
      },
      {
        say: "One eighty minus sixty-three is one hundred seventeen people for B.",
        work: "B = 117",
        note: "subtract",
        focus: ["B"],
      },
      {
        say: "Now it's part over whole. B's part is one seventeen, and the whole is all one eighty. Lay a percent scale under the bar.",
        work: "percent = 117/180",
        note: "part over whole",
        draw: ["scale", "drop"],
        focus: ["B", "scale", "drop"],
      },
      {
        say: "One seventeen over one eighty is zero point six five. B covers sixty-five percent of the bar.",
        work: "117/180 = 0.65 = 65%",
        note: "× 100",
        draw: ["share"],
        focus: ["B", "share"],
      },
      {
        say: "Thirty-five percent is option A's share, the yellow piece. Sixty-three is a count of people, not a percent.",
        strike: [1, 2],
        focus: ["A"],
      },
      {
        say: "And thirty-one and a half doesn't match any split here. B's share really is sixty-five.",
        strike: [3],
      },
    ],
    answer: "Sixty-five percent. And A's thirty-five plus B's sixty-five makes a hundred, so it checks out.",
    trap: { point: "Trap: using the given count as the part", say: "The number in the question belongs to option A. Subtract first to get B's part." },
    recap: { point: "Label part and whole, then divide", say: "Figure out which number is the part and which is the whole. Then the percent is part over whole." },
    tint: { B: "blue", "117": "blue", "117/180": "blue", "65%": "blue", "0.65": "blue", "63": "yellow" },
    scene: {
      x: [-8, 108],
      y: [-2.6, 10],
      objects: [
        { id: "whole", kind: "seg", from: [0, 7], to: [100, 7], width: 16, label: "180 people", labelOffset: [0, -4] },
        { id: "A", kind: "seg", from: [0, 7], to: [35, 7], width: 16, color: "yellow", label: "63", labelOffset: [0, 30] },
        { id: "B", kind: "seg", from: [35, 7], to: [100, 7], width: 16, color: "blue", label: "117", labelOffset: [0, 30] },
        { id: "scale", kind: "numline", y: 0.6, min: 0, max: 100, step: 25 },
        { id: "drop", kind: "seg", from: [35, 5.6], to: [35, 0.6], dash: true, color: "gray" },
        { id: "share", kind: "seg", from: [35, 2.4], to: [100, 2.4], width: 3, arrow: true, color: "blue", label: "65%" },
      ],
    },
  },
];
