import type { LessonVideoScript } from "../../types";

export const M_PROBABILITY: LessonVideoScript[] = [
  {
    subskillId: "m-probability",
    pattern: "Basic and Compound Probability",
    example: 1,
    hook: "\"And\" and \"or\" look like tiny words. In probability, they change the whole method.",
    idea: [
      { point: "P = favorable / total", say: "Basic probability is favorable outcomes over total outcomes." },
      { point: "Independent \"and\" → multiply", say: "For two independent events both happening, multiply their probabilities." },
      { point: "\"Or\" → add, then subtract overlap", say: "For either one happening, add them, then subtract the chance of both, so you don't count it twice." },
    ],
    steps: [
      {
        say: "Five red, three blue, and the marble goes back in. Across: first draw red, five eighths. Up: second draw blue, three eighths.",
        highlight: ["5 red marbles and 3 blue marbles", "replaced", "the first marble is red OR the second marble is blue"],
        work: "red: 5/8, blue: 3/8",
        note: "favorable / total",
        draw: ["red", "tRed", "blue", "tBlue"],
        focus: ["red", "tRed", "blue", "tBlue"],
      },
      {
        say: "Both can happen at once: that's the yellow corner. The draws are independent, so multiply for the overlap.",
        work: "both: 5/8 × 3/8 = 15/64",
        note: "and → multiply",
        draw: ["both"],
        focus: ["both"],
      },
      {
        say: "Or means add the pink and blue regions. But the yellow corner sits in both, so take it away once.",
        work: "5/8 + 3/8 − 15/64",
        note: "add, − overlap",
        focus: ["red", "blue", "both"],
      },
      {
        say: "Put it all over sixty-four. Forty plus twenty-four minus fifteen is forty-nine: the whole outlined region.",
        work: "40/64 + 24/64 − 15/64 = 49/64",
        note: "over 64",
        draw: ["union", "t49"],
        focus: ["union", "t49"],
      },
      {
        say: "One comes from adding without subtracting the overlap. It counts the yellow corner twice.",
        strike: [1],
        focus: ["both"],
      },
      {
        say: "Five eighths is only the first draw, and fifteen sixty-fourths is only the overlap.",
        strike: [2, 3],
      },
    ],
    answer: "Forty-nine sixty-fourths. Add the two, minus the part you counted twice.",
    trap: { point: "Trap: forgetting to subtract the overlap", say: "If both events can happen together, adding them counts that outcome twice. Take it out once." },
    recap: { point: "And: multiply. Or: add, minus overlap.", say: "Independent and, multiply. Or, add them and subtract the chance of both." },
    tint: { "5/8": "pink", "40/64": "pink", "3/8": "blue", "24/64": "blue", "15/64": "yellow", "49/64": "green" },
    scene: {
      x: [-1.2, 16.4],
      y: [-2.1, 8.6],
      objects: [
        { id: "sq", kind: "poly", pts: [[0, 0], [8, 0], [8, 8], [0, 8]], color: "gray" },
        { id: "red", kind: "poly", pts: [[0, 0], [5, 0], [5, 8], [0, 8]], fill: true, color: "pink" },
        { id: "tRed", kind: "text", at: [2.5, -1.5], text: "1st red: 5/8", size: 13, color: "pink" },
        { id: "blue", kind: "poly", pts: [[0, 0], [8, 0], [8, 3], [0, 3]], fill: true, color: "blue" },
        { id: "tBlue", kind: "text", at: [12, 1.1], text: "2nd blue: 3/8", size: 13, color: "blue" },
        { id: "both", kind: "poly", pts: [[0, 0], [5, 0], [5, 3], [0, 3]], fill: true, color: "yellow", label: "15/64" },
        { id: "union", kind: "poly", pts: [[0, 0], [8, 0], [8, 3], [5, 3], [5, 8], [0, 8]], color: "green" },
        { id: "t49", kind: "text", at: [12, 5.4], text: "49/64", size: 17, color: "green" },
      ],
    },
  },
  {
    subskillId: "m-probability",
    pattern: "Conditional Probability",
    example: 1,
    hook: "\"Given that\" is the most important phrase in the question. It shrinks your world.",
    idea: [
      { point: "\"Given that\" → shrink the group", say: "Given that tells you to ignore everyone outside a certain group." },
      { point: "That group is the new total", say: "The size of that group becomes your denominator, not the whole sample." },
    ],
    steps: [
      {
        say: "Given that they play a sport. So everyone else drops out, and the one hundred twenty athletes become the whole world.",
        highlight: ["given that they play a sport", "120 play a sport"],
        work: "total = 120",
        note: "given: sport only",
        hide: ["non", "tNon", "all", "tAll"],
        set: [{ id: "view", x: [-8, 128], y: [-28, 45] }],
        focus: ["sport", "tSport"],
      },
      {
        say: "Of those one twenty, forty-five also play an instrument. Shade them in.",
        highlight: ["45 also play a musical instrument"],
        work: "P = 45/120",
        note: "favorable / new total",
        draw: ["inst"],
        focus: ["inst", "sport"],
      },
      {
        say: "Both divide by fifteen. Cut the athletes into eight blocks of fifteen: the shaded part is three of them. Three eighths.",
        work: "P = 3/8",
        note: "÷15 top and bottom",
        draw: ["d1", "d2", "d3", "d4", "d5", "d6", "d7"],
        focus: ["inst", "d1", "d2", "d3", "d4", "d5", "d6", "d7"],
      },
      {
        say: "Forty-five over two hundred uses everyone surveyed. Nine fortieths is that same fraction, reduced.",
        strike: [1, 2],
      },
      {
        say: "And eighty is the number who don't play a sport. The condition says we only want the ones who do.",
        strike: [3],
      },
    ],
    answer: "Three eighths. Forty-five out of the one hundred twenty athletes.",
    trap: { point: "Trap: dividing by the whole sample", say: "The condition cuts the group down. Divide by the size of that smaller group, not everyone." },
    recap: { point: "Find the group, then count inside it", say: "Find the group the condition describes. Then count only inside it." },
    tint: { "120": "blue", "45/120": "yellow", "3/8": "yellow" },
    scene: {
      x: [-10, 210],
      y: [-48, 70],
      objects: [
        { id: "all", kind: "poly", pts: [[0, 0], [200, 0], [200, 30], [0, 30]] },
        { id: "tAll", kind: "text", at: [100, 42], text: "200 students", size: 14 },
        { id: "sport", kind: "poly", pts: [[0, 0], [120, 0], [120, 30], [0, 30]], fill: true, color: "blue" },
        { id: "tSport", kind: "text", at: [60, -18], text: "120 play a sport", size: 14, color: "blue" },
        { id: "non", kind: "poly", pts: [[120, 0], [200, 0], [200, 30], [120, 30]], fill: true, color: "gray" },
        { id: "tNon", kind: "text", at: [160, -18], text: "80", size: 14, color: "gray" },
        { id: "inst", kind: "poly", pts: [[0, 0], [45, 0], [45, 30], [0, 30]], fill: true, color: "yellow", label: "45" },
        { id: "d1", kind: "seg", from: [15, 0], to: [15, 30], width: 1.6 },
        { id: "d2", kind: "seg", from: [30, 0], to: [30, 30], width: 1.6 },
        { id: "d3", kind: "seg", from: [45, 0], to: [45, 30], width: 1.6 },
        { id: "d4", kind: "seg", from: [60, 0], to: [60, 30], width: 1.6 },
        { id: "d5", kind: "seg", from: [75, 0], to: [75, 30], width: 1.6 },
        { id: "d6", kind: "seg", from: [90, 0], to: [90, 30], width: 1.6 },
        { id: "d7", kind: "seg", from: [105, 0], to: [105, 30], width: 1.6 },
      ],
    },
  },
];
