import type { LessonVideoScript } from "../../types";

export const M_RATIOS_RATES: LessonVideoScript[] = [
  {
    subskillId: "m-ratios-rates",
    pattern: "Setting Up Proportions Correctly",
    example: 0,
    hook: "Proportion problems are rarely hard to compute. They're just easy to set up wrong.",
    idea: [
      { point: "Match units in matching spots", say: "Put the same kind of thing on top of both fractions, and the same kind on the bottom." },
      { point: "Then cross-multiply", say: "Once the units line up, cross-multiply and solve. The arithmetic is the easy part." },
    ],
    steps: [
      {
        say: "Cups over cookies on both sides. Two over twelve equals x over thirty. Watch both bars stretch to thirty cookies.",
        highlight: ["2 cups of flour for 12 cookies", "30 cookies"],
        work: "2/12 = x/30",
        note: "cups/cookies twice",
        draw: ["ck30", "cuX"],
        focus: ["ck30", "cuX", "ck12", "cu2"],
      },
      {
        say: "Cross-multiply. Twelve times x equals two times thirty.",
        work: "12 · x = 2 · 30",
        note: "cross-multiply",
        focus: ["ck30", "cuX"],
      },
      {
        say: "Two times thirty is sixty. So twelve x equals sixty.",
        work: "12x = 60",
        note: "2 · 30 = 60",
      },
      {
        say: "Divide both sides by twelve. X is five. The picture agrees: every six cookies take one cup, and thirty is five sixes.",
        work: "x = 5",
        note: "÷12 both sides",
        draw: ["d1", "d2", "d3", "d4", "one"],
        focus: ["d1", "d2", "d3", "d4", "one", "cuX"],
      },
      {
        say: "Point eight goes the wrong way. More cookies need more than two cups, not less.",
        strike: [2],
      },
      {
        say: "One eighty flips one side, putting cookies on top. And twenty fails a quick check: thirty cookies is five sixes, so five cups.",
        strike: [1, 3],
      },
    ],
    answer: "Five cups. One cup for every six cookies, and thirty cookies is five sixes.",
    trap: { point: "Trap: cups/cookies = cookies/cups", say: "If one fraction has cups on top and the other has cookies on top, the answer comes out confidently wrong." },
    recap: { point: "Same units, same positions", say: "Line up the units first, then cross-multiply. If the units match, the math follows." },
    tint: { x: "yellow", "2": "yellow", "5": "yellow", "12": "blue", "30": "blue" },
    scene: {
      x: [-9, 32.5],
      y: [-3, 14],
      objects: [
        { id: "tCk", kind: "text", at: [-4.6, 8.4], text: "cookies", size: 13, color: "blue" },
        { id: "tCu", kind: "text", at: [-4.6, 2.4], text: "cups", size: 13, color: "yellow" },
        { id: "ck12", kind: "seg", from: [0, 9], to: [12, 9], width: 12, color: "blue", label: "12", labelOffset: [36, -2] },
        { id: "cu2", kind: "seg", from: [0, 3], to: [12, 3], width: 12, color: "yellow", label: "2", labelOffset: [36, -2] },
        { id: "ck30", kind: "seg", from: [0, 9], to: [30, 9], width: 12, color: "blue", label: "30", labelOffset: [90, -2] },
        { id: "cuX", kind: "seg", from: [0, 3], to: [30, 3], width: 12, color: "yellow", label: "x", labelOffset: [90, -2] },
        { id: "d1", kind: "seg", from: [6, 1.4], to: [6, 10.6], width: 2 },
        { id: "d2", kind: "seg", from: [12, 1.4], to: [12, 10.6], width: 2 },
        { id: "d3", kind: "seg", from: [18, 1.4], to: [18, 10.6], width: 2 },
        { id: "d4", kind: "seg", from: [24, 1.4], to: [24, 10.6], width: 2 },
        { id: "one", kind: "text", at: [15, -1.6], text: "1 cup per 6 cookies", size: 13, color: "white" },
      ],
    },
  },
  {
    subskillId: "m-ratios-rates",
    pattern: "Unit Conversion Chains",
    example: 0,
    hook: "Don't guess whether to multiply or divide. Line up the units and let them cancel.",
    idea: [
      { point: "Chain factors so units cancel", say: "Write each conversion as a fraction, so the unit you don't want sits once on top and once on the bottom." },
      { point: "What's left is the answer's unit", say: "Cancel them, and whatever units survive should be exactly what the question asks for." },
    ],
    steps: [
      {
        say: "Start with sixty miles per hour: sixty miles of road for one hour of time. We want feet per minute.",
        highlight: ["60 miles per hour", "feet per minute"],
        work: "60 mi/hr",
        note: "start here",
        focus: ["dist", "time", "tMi", "tHr"],
      },
      {
        say: "Multiply by five thousand two hundred eighty feet per mile. Miles on top, miles on the bottom: they cancel.",
        work: "60 mi/hr × 5,280 ft/mi",
        note: "miles cancel",
        draw: ["tFt"],
        hide: ["tMi"],
        focus: ["dist", "tFt"],
      },
      {
        say: "That's three hundred sixteen thousand eight hundred feet, but still per hour. That choice stops one step early.",
        work: "316,800 ft/hr",
        note: "60 × 5,280",
        focus: ["tFt", "time", "tHr"],
        strike: [1],
      },
      {
        say: "Now swap the hour for sixty minutes. The hour gets chopped into sixty equal slices.",
        work: "316,800 ft / 60 min",
        note: "1 hr = 60 min",
        draw: ["ticks", "tMin"],
        hide: ["tHr"],
        focus: ["ticks", "tMin", "dist"],
      },
      {
        say: "Take one slice. One minute of time covers one sixtieth of the distance: five thousand two hundred eighty feet per minute.",
        work: "5,280 ft/min",
        note: "÷60: one minute",
        draw: ["sTime", "sDist"],
        focus: ["sTime", "sDist"],
      },
      {
        say: "Eighty-eight is feet per second, and sixty-three thousand three hundred sixty is the inches in a mile.",
        strike: [2, 3],
      },
    ],
    answer: "Five thousand two hundred eighty feet per minute. Sixty miles an hour is exactly a mile a minute.",
    trap: { point: "Trap: a conversion factor upside down", say: "If a unit doesn't cancel, that fraction is flipped. Fix it before you touch the numbers." },
    recap: { point: "Chain it, cancel it, check the units", say: "Build the chain so every unwanted unit cancels. If what's left matches the question, the setup is right." },
    tint: { "316,800": "orange", "5,280": "yellow", "60": "blue" },
    scene: {
      x: [-3, 63],
      y: [-1.2, 9.4],
      objects: [
        { id: "dist", kind: "seg", from: [0, 6.2], to: [60, 6.2], width: 12, color: "orange" },
        { id: "tMi", kind: "text", at: [30, 8.2], text: "60 miles", color: "orange" },
        { id: "time", kind: "seg", from: [0, 2], to: [60, 2], width: 3, color: "blue" },
        { id: "tHr", kind: "text", at: [30, -0.2], text: "1 hour", color: "blue" },
        { id: "tFt", kind: "text", at: [30, 8.2], text: "316,800 feet", color: "orange" },
        { id: "ticks", kind: "numline", y: 2, min: 0, max: 60, step: 1, numbers: false, color: "blue" },
        { id: "tMin", kind: "text", at: [30, -0.2], text: "60 minutes", color: "blue" },
        { id: "sDist", kind: "seg", from: [0, 6.2], to: [1, 6.2], width: 16, color: "yellow", label: "5,280 ft", labelOffset: [12, -4] },
        { id: "sTime", kind: "seg", from: [0, 2], to: [1, 2], width: 9, color: "yellow", label: "1 min", labelOffset: [8, 34] },
      ],
    },
  },
  {
    subskillId: "m-ratios-rates",
    pattern: "Expressing One Quantity as an Algebraic Ratio Expression",
    example: 4,
    hook: "A ratio question with letters is still just multiplying. The hard part is which way.",
    idea: [
      { point: "Write the ratio as a fraction", say: "Turn the ratio into a fraction exactly as it's stated, then multiply the known quantity by it." },
      { point: "Check the direction", say: "Then sanity-check. If there are more of one thing, its expression should come out bigger." },
    ],
    steps: [
      {
        say: "One manager for every six engineers, so engineers are six times managers. The engineer bar is six manager bars long.",
        highlight: ["managers to engineers is 1 to 6"],
        work: "engineers = 6m",
        note: "1 to 6: × 6",
        draw: ["eBar"],
        focus: ["mBar", "eBar"],
      },
      {
        say: "Three engineers for every ten interns. So each group of three engineers becomes ten interns: ten thirds as many.",
        highlight: ["engineers to interns is 3 to 10"],
        work: "interns = (10/3) × engineers",
        note: "3 to 10: × 10/3",
        draw: ["eDiv", "i1", "con1"],
        focus: ["eBar", "eDiv", "i1", "con1"],
      },
      {
        say: "Swap in six m for the engineers. That's two groups of three, so two groups of ten.",
        work: "interns = (10/3)(6m)",
        note: "substitute",
        draw: ["i2", "con2"],
        focus: ["eBar", "i1", "i2", "con2"],
      },
      {
        say: "Ten thirds of six is twenty. So the interns are twenty m.",
        work: "interns = 20m",
        note: "(10/3)(6) = 20",
        draw: ["total"],
        focus: ["i1", "i2", "total"],
      },
      {
        say: "Eighteen m multiplies six by three, and sixty m multiplies six by ten. Neither one divides by three.",
        strike: [1, 3],
      },
      {
        say: "M over twenty flips it. Look at the bars: there are far more interns than managers, not fewer.",
        strike: [2],
        focus: ["mBar", "i1", "i2"],
      },
    ],
    answer: "Twenty m. Every manager comes with six engineers, and those six engineers come with twenty interns.",
    trap: { point: "Trap: flipping the ratio's fraction", say: "Three to ten means interns are ten thirds of the engineers, not three tenths. More interns, bigger fraction." },
    recap: { point: "Ratio → fraction → multiply, then check", say: "Chain one ratio at a time, as fractions, and check that the bigger group gets the bigger expression." },
    tint: { m: "blue", engineers: "yellow", interns: "orange", "10/3": "orange" },
    scene: {
      x: [-6.5, 22],
      y: [-3.8, 12.6],
      objects: [
        { id: "tM", kind: "text", at: [-3.4, 10.6], text: "mgrs", size: 13, color: "blue" },
        { id: "tE", kind: "text", at: [-3.4, 5.6], text: "engs", size: 13, color: "yellow" },
        { id: "tI", kind: "text", at: [-3.4, 0.6], text: "interns", size: 13, color: "orange" },
        { id: "mBar", kind: "seg", from: [0, 11], to: [1, 11], width: 11, color: "blue", label: "m", labelOffset: [22, 13] },
        { id: "eBar", kind: "seg", from: [0, 6], to: [6, 6], width: 11, color: "yellow", label: "6m", labelOffset: [48, 13] },
        { id: "eDiv", kind: "seg", from: [3, 7.1], to: [3, 4.9], width: 2 },
        { id: "i1", kind: "seg", from: [0, 1], to: [10, 1], width: 11, color: "orange", label: "10m" },
        { id: "con1", kind: "seg", from: [3, 4.9], to: [10, 2.1], dash: true, color: "gray" },
        { id: "i2", kind: "seg", from: [10, 1], to: [20, 1], width: 11, color: "orange", label: "10m" },
        { id: "con2", kind: "seg", from: [6, 4.9], to: [20, 2.1], dash: true, color: "gray" },
        { id: "total", kind: "text", at: [10, -2.6], text: "20m in all", size: 14, color: "orange" },
      ],
    },
  },
];
