import type { LessonVideoScript } from "../../types";

export const M_RIGHT_TRI_TRIG: LessonVideoScript[] = [
  {
    subskillId: "m-right-tri-trig",
    pattern: "SOH-CAH-TOA Setup",
    example: 0,
    hook: "The formula's never the hard part. Knowing which side is which is.",
    idea: [
      { point: "SOH-CAH-TOA", say: "Sine is opposite over hypotenuse. Cosine is adjacent over hypotenuse. Tangent is opposite over adjacent." },
      { point: "Label sides from the angle", say: "Stand at the angle you're using. The side across from you is opposite, the leg touching you is adjacent." },
    ],
    steps: [
      {
        say: "The angle is forty degrees, down at the ground. The fifteen feet runs along the ground, right next to it.",
        highlight: ["15 feet from the base of a pole", "40° angle of elevation"],
        focus: ["ang", "adj"],
      },
      {
        say: "The pole's height is across from the angle, so it's opposite. Fifteen is adjacent. No hypotenuse needed.",
        highlight: ["pole's height"],
        work: "opp = h, adj = 15",
        note: "label the sides",
        draw: ["opp"],
        focus: ["ang", "opp", "adj"],
      },
      {
        say: "Opposite and adjacent means tangent. So tangent of forty degrees equals h over fifteen.",
        work: "tan(40°) = h/15",
        note: "TOA",
        focus: ["ang", "opp", "adj"],
      },
      {
        say: "Multiply both sides by fifteen to get h alone.",
        work: "h = 15 · tan(40°)",
        note: "×15 both sides",
        focus: ["opp"],
      },
      {
        say: "Sine and cosine both need the cable, the hypotenuse, which we don't have.",
        strike: [1, 2],
        focus: ["hyp"],
      },
      {
        say: "And fifteen over tangent divides when the equation says multiply.",
        strike: [3],
      },
    ],
    answer: "Fifteen times the tangent of forty degrees. Opposite and adjacent, so tangent.",
    trap: { point: "Trap: mixing up opposite and adjacent", say: "Opposite and adjacent depend on which angle you're standing at. Switch angles, and they switch too." },
    recap: { point: "Label from the angle, then pick the ratio", say: "Find the angle, label the sides from there, and let the two sides you have pick the ratio." },
    tint: { h: "blue", "15": "yellow", "40": "green" },
    scene: {
      // Anchor at A, pole at B: height 15·tan 40° = 12.59.
      x: [-2.5, 19.5],
      y: [-2.6, 14],
      pts: { A: [0, 0], B: [15, 0], T: [15, 12.586] },
      objects: [
        { id: "pole", kind: "seg", from: "B", to: "T" },
        { id: "hyp", kind: "seg", from: "A", to: "T", color: "gray", label: "cable", labelOffset: [-10, -2] },
        { id: "adj", kind: "seg", from: "A", to: "B", color: "yellow", label: "15", labelOffset: [0, 26] },
        { id: "right", kind: "angle", at: "B", from: "A", to: "T", right: true, color: "gray" },
        { id: "ang", kind: "angle", at: "A", from: "B", to: "T", r: 34, color: "green", label: "40°", labelOffset: [14, -3] },
        { id: "opp", kind: "seg", from: "B", to: "T", color: "blue", label: "h", labelOffset: [30, 0] },
      ],
    },
  },
  {
    subskillId: "m-right-tri-trig",
    pattern: "Special Right Triangles (30-60-90 and 45-45-90)",
    example: 4,
    hook: "See a sixty degree angle in a right triangle? You already know every side.",
    idea: [
      { point: "45-45-90: x, x, x√2", say: "In a forty-five forty-five ninety triangle, the legs are equal and the hypotenuse is a leg times root two." },
      { point: "30-60-90: x, x√3, 2x", say: "In a thirty sixty ninety, the short side is x, the side across from sixty is x root three, and the hypotenuse is two x." },
    ],
    steps: [
      {
        say: "The hypotenuse is sixteen and one angle is sixty. That's a thirty sixty ninety triangle.",
        highlight: ["hypotenuse measures 16", "60°"],
        work: "sides: x, x√3, 2x",
        note: "30-60-90",
        focus: ["hyp", "ang60", "ang30", "right"],
      },
      {
        say: "Why two x? Fold the triangle down. Two copies make an equilateral triangle, so twice the short side equals the hypotenuse, sixteen.",
        work: "2x = 16",
        note: "hypotenuse = 2x",
        draw: ["gA", "ghost", "full"],
        set: [
          { id: "gA", at: [0, -8] },
          { id: "view", x: [-9, 22.5], y: [-10.3, 10.3] },
        ],
        focus: ["ghost", "full", "hyp", "sx"],
      },
      {
        say: "Divide by two. The short side, across from thirty degrees, is eight.",
        work: "x = 8",
        note: "÷2 both sides",
        hide: ["gA", "ghost", "full", "sx"],
        draw: ["sx8"],
        set: [{ id: "view", x: [-2.5, 16.5], y: [-2.5, 10.5] }],
        focus: ["sx8", "ang30"],
      },
      {
        say: "The side across from sixty is x root three. That's eight root three.",
        work: "x√3 = 8√3",
        note: "long leg",
        hide: ["long"],
        draw: ["long8"],
        focus: ["long8", "ang60"],
      },
      {
        say: "Eight is the short side, across from thirty. Sixteen root three starts from the hypotenuse instead of the short side.",
        strike: [1, 2],
        focus: ["sx8", "hyp"],
      },
      {
        say: "And four root three halves one too many times.",
        strike: [3],
      },
    ],
    answer: "Eight root three. Halve the hypotenuse, then multiply by root three.",
    trap: { point: "Trap: mixing up the two ratios", say: "Root two belongs to the forty-five triangle, root three to the thirty sixty. Check the angles before you pick." },
    recap: { point: "Spot the angles, use the ratio", say: "Recognize the special angles and the sides come straight from the ratio. No Pythagorean theorem needed." },
    tint: { x: "blue", "8": "blue", "16": "green", "√3": "yellow" },
    scene: {
      // Right angle at C, 60° at A, 30° at B: CA = 8, CB = 8√3 = 13.86, AB = 16.
      x: [-2.5, 16.5],
      y: [-2.5, 10.5],
      pts: { C: [0, 0], B: [13.856, 0], A: [0, 8], A2: [0, -8] },
      objects: [
        { id: "sx", kind: "seg", from: "C", to: "A", color: "blue", label: "x" },
        { id: "long", kind: "seg", from: "C", to: "B", color: "yellow", label: "?", labelOffset: [0, 26] },
        { id: "hyp", kind: "seg", from: "A", to: "B", color: "green", label: "16" },
        { id: "right", kind: "angle", at: "C", from: "B", to: "A", right: true, color: "gray" },
        { id: "ang60", kind: "angle", at: "A", from: "C", to: "B", r: 22, label: "60°", labelOffset: [4, 4] },
        { id: "ang30", kind: "angle", at: "B", from: "A", to: "C", r: 34, color: "gray", label: "30°", labelOffset: [-6, 0] },
        { id: "gA", kind: "point", at: "A", color: "green" },
        { id: "ghost", kind: "poly", pts: ["C", "B", "gA"], color: "green", fill: true, dash: true },
        { id: "full", kind: "seg", from: "A", to: "A2", color: "green", label: "16", labelOffset: [-10, 20] },
        { id: "sx8", kind: "seg", from: "C", to: "A", color: "blue", label: "8" },
        { id: "long8", kind: "seg", from: "C", to: "B", color: "yellow", label: "8√3", labelOffset: [0, 26] },
      ],
    },
  },
  {
    subskillId: "m-right-tri-trig",
    pattern: "Using the Pythagorean Theorem Before Computing a Trig Ratio",
    example: 3,
    hook: "Sometimes you're handed two sides, and they're the wrong two. So go get the third.",
    idea: [
      { point: "Ratio needs sides you don't have?", say: "A trig ratio uses two specific sides. If one of them is missing, you can't skip ahead." },
      { point: "a² + b² = c² finds it first", say: "Use the Pythagorean theorem to find the missing side, then set up the ratio." },
    ],
    steps: [
      {
        say: "We want the angle that isn't next to the nine, so nine is opposite it. The fifteen is the hypotenuse.",
        highlight: ["one leg measures 9", "hypotenuse measures 15", "NOT adjacent to the leg of length 9"],
        focus: ["theta", "opp", "hyp"],
      },
      {
        say: "Cosine needs the adjacent side, and that's the one that's missing. So find it. Hypotenuse squared minus the known leg squared.",
        work: "b² = 15² − 9²",
        note: "missing leg",
        focus: ["adj", "opp", "hyp", "right"],
      },
      {
        say: "Fifteen squared is two hundred twenty-five, nine squared is eighty-one. Subtract, and you get one hundred forty-four.",
        work: "b² = 225 − 81 = 144",
        note: "square and subtract",
        focus: ["adj", "opp", "hyp"],
      },
      {
        say: "The square root of one hundred forty-four is twelve. That's the adjacent side.",
        work: "b = 12",
        note: "take the root",
        hide: ["adj"],
        draw: ["adj12"],
        focus: ["adj12"],
      },
      {
        say: "Cosine is adjacent over hypotenuse. Twelve over fifteen, which simplifies to four fifths.",
        work: "cos θ = 12/15 = 4/5",
        note: "CAH, simplify",
        focus: ["theta", "adj12", "hyp"],
      },
      {
        say: "Three fifths is the sine. Nine fifteenths treats nine as adjacent, and twelve ninths skips the hypotenuse.",
        strike: [1, 2, 3],
        focus: ["theta", "opp"],
      },
    ],
    answer: "Four fifths. Twelve adjacent, fifteen hypotenuse.",
    trap: { point: "Trap: using the two sides you're given", say: "It's tempting to make a ratio from whatever's on the page. Check that they're the sides the ratio actually needs." },
    recap: { point: "Find the third side, then the ratio", say: "Label the sides from the angle, fill in the missing one with Pythagoras, then build the ratio." },
    tint: { "9": "blue", "81": "blue", "15": "green", "225": "green", b: "yellow", "144": "yellow", "12": "yellow", "12/15": "yellow" },
    scene: {
      // A 9-12-15 right triangle, θ at A, so 9 is across from it.
      x: [-2.5, 14.5],
      y: [-2.6, 10.8],
      pts: { C: [0, 0], A: [12, 0], B: [0, 9] },
      objects: [
        { id: "opp", kind: "seg", from: "C", to: "B", color: "blue", label: "9" },
        { id: "adj", kind: "seg", from: "C", to: "A", color: "yellow", label: "?", labelOffset: [0, 26] },
        { id: "hyp", kind: "seg", from: "A", to: "B", color: "green", label: "15" },
        { id: "right", kind: "angle", at: "C", from: "A", to: "B", right: true, color: "gray" },
        { id: "theta", kind: "angle", at: "A", from: "C", to: "B", r: 34, label: "θ", labelOffset: [-4, 0] },
        { id: "adj12", kind: "seg", from: "C", to: "A", color: "yellow", label: "12", labelOffset: [0, 26] },
      ],
    },
  },
  {
    subskillId: "m-right-tri-trig",
    pattern: "Radian Measure and Coterminal Angles",
    example: 5,
    hook: "A big negative angle looks scary. Spin it around until it lands somewhere familiar.",
    idea: [
      { point: "Add or subtract 2π until in range", say: "A full turn is two pi. Adding or subtracting full turns lands you in the exact same spot." },
      { point: "Same spot, same trig values", say: "And angles that land in the same spot have the same sine, cosine, and tangent." },
    ],
    steps: [
      {
        say: "Negative eleven pi over three means turning clockwise, almost two full times. Watch where it lands.",
        highlight: ["cos(-11π/3)"],
        move: [{ id: "ray", turn: -660, about: "O" }],
        focus: ["ray"],
      },
      {
        say: "Two pi is six thirds pi, so add that. The arrow spins a full turn and stops in the very same spot.",
        work: "−11π/3 + 6π/3 = −5π/3",
        note: "+2π",
        move: [{ id: "ray", turn: 360, about: "O" }],
        focus: ["ray"],
      },
      {
        say: "Still negative. Add another full turn. Same spot again, and now it's just pi over three.",
        work: "−5π/3 + 6π/3 = π/3",
        note: "+2π again",
        move: [{ id: "ray", turn: 360, about: "O" }],
        draw: ["arc"],
        focus: ["ray", "arc"],
      },
      {
        say: "Cosine is how far right the point sits. Pi over three is sixty degrees, and that's one half. Positive, since it's on the right.",
        work: "cos(π/3) = 1/2",
        note: "known value",
        draw: ["guide", "cosSeg"],
        focus: ["cosSeg", "guide", "ray"],
      },
      {
        say: "Negative one half comes from stopping after one turn and getting the sign wrong.",
        strike: [1],
        focus: ["cosSeg"],
      },
      {
        say: "Root three over two is the height, the sine, not cosine. Negative root three over two is the wrong value and the wrong sign.",
        strike: [2, 3],
        draw: ["sinSeg"],
        focus: ["sinSeg"],
      },
    ],
    answer: "One half. Two full turns, and it's just pi over three.",
    trap: { point: "Trap: evaluating the big angle directly", say: "Don't try to picture negative eleven pi over three. Reduce it first, then evaluate." },
    recap: { point: "Reduce by 2π, then evaluate", say: "Add or subtract two pi until the angle's between zero and two pi. Then use the values you know." },
    tint: { "1/2": "green", "6π": "orange" },
    scene: {
      // The unit circle; the arrow turns −660°, which lands at 60° (π/3).
      x: [-2.2, 2.2],
      y: [-1.4, 1.4],
      pts: { O: [0, 0], P: [0.5, 0.866], X: [0.5, 0] },
      objects: [
        { id: "xAx", kind: "seg", from: [-1.45, 0], to: [1.45, 0], color: "gray" },
        { id: "yAx", kind: "seg", from: [0, -1.3], to: [0, 1.3], color: "gray" },
        { id: "circ", kind: "circle", c: "O", r: 1 },
        { id: "ray", kind: "seg", from: "O", to: [1, 0], color: "orange", arrow: true, width: 3 },
        { id: "arc", kind: "angle", at: "O", from: [1, 0], to: "P", r: 26, color: "blue", label: "π/3", labelOffset: [18, 6] },
        { id: "guide", kind: "seg", from: "P", to: "X", dash: true, color: "gray" },
        { id: "cosSeg", kind: "seg", from: "O", to: "X", color: "green", width: 4, label: "1/2", labelOffset: [0, 38] },
        { id: "sinSeg", kind: "seg", from: "X", to: "P", color: "purple", width: 4, label: "√3/2", labelOffset: [44, 0] },
      ],
    },
  },
  {
    subskillId: "m-right-tri-trig",
    pattern: "Using the Pythagorean Theorem Alone to Find a Missing Side",
    example: 4,
    hook: "Radical sides look messy, but squaring them cleans them right up.",
    idea: [
      { point: "a² + b² = c², c is the hypotenuse", say: "The two legs squared add up to the hypotenuse squared. The hypotenuse is across from the right angle." },
      { point: "(a√b)² = a² × b", say: "To square something like four root three, square the four and drop the root. Sixteen times three." },
    ],
    steps: [
      {
        say: "The legs are four root three and four. Build a square on each leg. We want the hypotenuse, so add the squares.",
        highlight: ["legs of length 4√3 and 4"],
        work: "c² = (4√3)² + 4²",
        note: "legs squared",
        draw: ["sqA", "sqB"],
        focus: ["sqA", "sqB", "legA", "legB"],
      },
      {
        say: "Four root three squared is sixteen times three, which is forty-eight. Four squared is sixteen.",
        work: "c² = 48 + 16",
        note: "16 × 3 = 48",
        draw: ["t48", "t16"],
        focus: ["sqA", "sqB", "t48", "t16"],
      },
      {
        say: "Add them up. The square on the hypotenuse holds sixty-four.",
        work: "c² = 64",
        note: "add",
        draw: ["sqC", "t64"],
        focus: ["sqC", "t64"],
      },
      {
        say: "Take the square root. The hypotenuse is eight.",
        work: "c = 8",
        note: "√ both sides",
        hide: ["hyp"],
        draw: ["hyp8"],
        focus: ["hyp8", "sqC"],
      },
      {
        say: "Sixty-four is c squared, one step early. Four root three plus four just adds the legs.",
        strike: [2, 3],
        focus: ["t64", "legA", "legB"],
      },
      {
        say: "And four root seven mashes the legs under one root instead of squaring each one.",
        strike: [1],
      },
    ],
    answer: "Eight. Forty-eight plus sixteen is sixty-four, and its root is eight.",
    trap: { point: "Trap: squaring a radical wrong", say: "Four root three squared is sixteen times three. Not sixteen plus three, and not four times three." },
    recap: { point: "Square, add, root", say: "Square each leg carefully, add, and take the square root. Simplify whatever's left." },
    tint: { "48": "yellow", "√3": "yellow", "16": "blue", "64": "green", c: "green" },
    scene: {
      // Legs 4√3 = 6.93 and 4, hypotenuse 8, with the squares drawn on all three sides.
      x: [-12, 19.5],
      y: [-9.4, 11.6],
      pts: { C: [0, 0], B: [6.928, 0], A: [0, 4] },
      objects: [
        { id: "legA", kind: "seg", from: "C", to: "B", color: "yellow", label: "4√3", labelOffset: [0, 84] },
        { id: "legB", kind: "seg", from: "C", to: "A", color: "blue", label: "4", labelOffset: [-34, 0] },
        { id: "hyp", kind: "seg", from: "A", to: "B", color: "green", label: "?", labelOffset: [2, 2] },
        { id: "right", kind: "angle", at: "C", from: "B", to: "A", right: true, r: 9, color: "gray" },
        { id: "sqA", kind: "poly", pts: ["C", "B", [6.928, -6.928], [0, -6.928]], color: "yellow", fill: true },
        { id: "sqB", kind: "poly", pts: ["C", "A", [-4, 4], [-4, 0]], color: "blue", fill: true },
        { id: "t48", kind: "text", at: [3.464, -4.1], text: "48", color: "yellow", size: 17 },
        { id: "t16", kind: "text", at: [-2, 1.4], text: "16", color: "blue", size: 15 },
        { id: "sqC", kind: "poly", pts: ["B", "A", [4, 10.928], [10.928, 6.928]], color: "green", fill: true },
        { id: "t64", kind: "text", at: [6.3, 6.2], text: "64", color: "green", size: 17 },
        { id: "hyp8", kind: "seg", from: "A", to: "B", color: "green", label: "8", labelOffset: [2, 2] },
      ],
    },
  },
  {
    subskillId: "m-right-tri-trig",
    pattern: "The Sine-Cosine Complementary Angle Relationship",
    example: 2,
    hook: "When sine of one angle equals cosine of another, the angles are telling you something.",
    idea: [
      { point: "Acute angles add to 90°", say: "In a right triangle, the two smaller angles always add up to ninety degrees." },
      { point: "sin(x°) = cos(90° − x°)", say: "One angle's opposite side is the other's adjacent side. So sine of one equals cosine of the other." },
    ],
    steps: [
      {
        say: "Sine of three x equals cosine of two x plus fifteen. So those are the two acute angles of one right triangle.",
        highlight: ["sin(3x°) = cos(2x° + 15°)"],
        focus: ["angA", "angB"],
      },
      {
        say: "Slide both into the right-angle corner. Together they fill it exactly, so they add to ninety.",
        work: "3x + (2x + 15) = 90",
        note: "sum to 90°",
        draw: ["copyA", "copyB"],
        move: [
          { id: "copyA", by: [-8, 0], turn: -135 },
          { id: "copyB", by: [0, -8], turn: 135 },
        ],
        focus: ["copyA", "copyB", "right"],
      },
      {
        say: "Combine the x terms. Five x plus fifteen.",
        work: "5x + 15 = 90",
        note: "combine like terms",
        focus: ["copyA", "copyB"],
      },
      {
        say: "Subtract fifteen from both sides.",
        work: "5x = 75",
        note: "−15 both sides",
      },
      {
        say: "Divide by five. X is fifteen, so both angles are forty-five degrees.",
        work: "x = 15",
        note: "÷5 both sides",
        focus: ["angA", "angB"],
      },
      {
        say: "Twenty-five makes the angles add to one hundred forty, five makes forty, and thirty-seven point five puts three x over ninety alone.",
        strike: [1, 2, 3],
      },
    ],
    answer: "Fifteen. The angles are forty-five and forty-five, which add to ninety.",
    trap: { point: "Trap: sine and cosine of one angle", say: "The shortcut links sine of one angle to cosine of its partner. Sine and cosine of the same angle usually differ." },
    recap: { point: "sin = cos means sum is 90°", say: "Whenever sine of one angle equals cosine of another, those two angles add up to ninety degrees." },
    tint: { "3x": "yellow", "2x": "orange", "90": "green" },
    scene: {
      // Drawn at the answer: both acute angles are 45°.
      x: [-3, 14],
      y: [-1.6, 9.6],
      pts: { C: [0, 0], A: [8, 0], B: [0, 8] },
      objects: [
        { id: "tri", kind: "poly", pts: ["C", "A", "B"] },
        { id: "right", kind: "angle", at: "C", from: "A", to: "B", right: true, r: 14, color: "green" },
        { id: "angA", kind: "angle", at: "A", from: "C", to: "B", r: 36, color: "yellow", label: "3x°" },
        { id: "angB", kind: "angle", at: "B", from: "C", to: "A", r: 36, color: "orange", label: "(2x + 15)°", labelOffset: [44, -4] },
        { id: "copyA", kind: "angle", at: "A", from: "C", to: "B", r: 36, color: "yellow" },
        { id: "copyB", kind: "angle", at: "B", from: "C", to: "A", r: 36, color: "orange" },
      ],
    },
  },
];
