import type { LessonVideoScript } from "../../types";

export const M_SYSTEMS: LessonVideoScript[] = [
  {
    subskillId: "m-systems",
    pattern: "Solving by Substitution and Setting Up Systems from Words",
    example: 3,
    hook: "A word problem with two unknowns is really two equations wearing a trench coat.",
    idea: [
      { point: "Name both unknowns, translate each fact", say: "Give each unknown a letter. Then turn each fact into its own equation, one phrase at a time." },
      { point: "Already solved for one? Substitute", say: "If one equation already says L equals something, swap that whole expression into the other, in parentheses." },
      { point: "Answer what they asked", say: "Before you pick, check which unknown they want. The other one's always sitting in the choices." },
    ],
    steps: [
      {
        say: "A fifty-one foot rope, cut in two. The longer piece plus the shorter piece is the whole rope.",
        highlight: ["51-foot rope"],
        work: "L + S = 51",
        note: "two pieces, one rope",
        draw: ["Lp", "Sp"],
        hide: ["rope"],
      },
      {
        say: "Six more than twice the shorter. Twice S first, then add six. L equals two S plus six.",
        highlight: ["6 feet more than twice the length of the shorter piece"],
        work: "L = 2S + 6",
        note: "6 more than twice S",
        draw: ["s1", "s2", "six"],
        move: [
          { id: "s1", by: [-36, -4] },
          { id: "s2", by: [-21, -4] },
        ],
        focus: ["Lp", "s1", "s2", "six"],
      },
      {
        say: "The second equation is already solved for L, so swap it into the first.",
        work: "(2S + 6) + S = 51",
        note: "substitute for L",
        hide: ["Lp"],
        move: [
          { id: "s1", by: [0, 4] },
          { id: "s2", by: [0, 4] },
          { id: "six", by: [0, 4] },
        ],
      },
      {
        say: "Combine to get three S plus six, then subtract six from both sides. Three S equals forty-five.",
        work: "3S = 45",
        note: "combine, then −6",
        focus: ["s1", "s2", "Sp"],
      },
      {
        say: "Divide by three. S is fifteen. That's the shorter piece, and it's sitting in the choices as bait.",
        work: "S = 15",
        note: "÷3 both sides",
        draw: ["n1", "n2", "n3"],
        strike: [1],
      },
      {
        say: "Plug back in. The longer piece is thirty-six. Thirty-eight comes from setting it up with the six doubled, and thirty-two with it subtracted.",
        work: "L = 2(15) + 6 = 36",
        note: "plug back in",
        draw: ["Lback"],
        focus: ["Lback"],
        strike: [2, 3],
      },
    ],
    answer: "Thirty-six feet. And thirty-six plus fifteen is fifty-one, so it checks out.",
    trap: { point: "Trap: answering with the other unknown", say: "You solved for the short piece first, but they asked for the long one. Read the question again before choosing." },
    recap: { point: "Translate, substitute, answer the question", say: "Turn each fact into an equation, substitute the one that's already solved, and give them the unknown they asked for." },
    tint: { S: "blue", L: "yellow", "51": "white", "6": "orange" },
    scene: {
      x: [-2, 53],
      y: [-9, 7],
      objects: [
        { id: "rope", kind: "seg", from: [0, 0], to: [51, 0], width: 7, label: "51 ft" },
        { id: "Lp", kind: "seg", from: [0, 0], to: [35.6, 0], width: 7, color: "yellow", label: "L" },
        { id: "Sp", kind: "seg", from: [36.4, 0], to: [51, 0], width: 7, color: "blue", label: "S" },
        { id: "s1", kind: "seg", from: [36.4, 0], to: [51, 0], width: 7, color: "blue" },
        { id: "s2", kind: "seg", from: [36.4, 0], to: [51, 0], width: 7, color: "blue" },
        { id: "six", kind: "seg", from: [30.4, -4], to: [35.6, -4], width: 7, color: "orange", label: "6", labelOffset: [0, 30] },
        { id: "n1", kind: "text", at: [7.5, 3.4], text: "15", color: "blue" },
        { id: "n2", kind: "text", at: [22.5, 3.4], text: "15", color: "blue" },
        { id: "n3", kind: "text", at: [43.7, 3.4], text: "15", color: "blue" },
        { id: "Lback", kind: "seg", from: [0, -5], to: [35.6, -5], width: 7, color: "yellow", label: "L = 36", labelOffset: [0, 32] },
      ],
    },
  },
  {
    subskillId: "m-systems",
    pattern: "Solving for a Specific Value via Elimination",
    example: 1,
    hook: "If two equations share a term, you can make it disappear in one move.",
    idea: [
      { point: "Line up the terms", say: "When both equations look like a x plus b y equals c, stack them and compare the terms." },
      { point: "Add or subtract to cancel one", say: "If a term matches, subtract. If it's opposite, add. Otherwise, multiply one equation first." },
    ],
    steps: [
      {
        say: "Three x plus two y equals sixteen. That's one line.",
        highlight: ["3x + 2y = 16"],
        work: "3x + 2y = 16",
        draw: ["L1"],
        focus: ["L1"],
      },
      {
        say: "And three x minus five y equals negative twelve. Both start with three x, so subtracting will cancel it.",
        highlight: ["3x - 5y = -12"],
        work: "3x − 5y = −12",
        note: "same 3x: subtract",
        draw: ["L2"],
        focus: ["L2"],
      },
      {
        say: "Subtract the whole second equation from the first. Every term in it gets a minus, including the negative twelve.",
        work: "(3x + 2y) − (3x − 5y) = 16 − (−12)",
        note: "subtract everything",
        draw: ["comb"],
        focus: ["comb", "L1", "L2"],
      },
      {
        say: "Three x minus three x is zero, so the tilt is gone. Two y minus negative five y is seven y. Sixteen minus negative twelve: twenty-eight.",
        work: "7y = 28",
        note: "3x cancels",
        set: [{ id: "comb", params: { t: 1 } }],
        focus: ["comb", "L1", "L2"],
      },
      {
        say: "Divide by seven. Y is four. It's the height where the two lines cross.",
        work: "y = 4",
        note: "÷7 both sides",
        draw: ["sol", "ylab"],
        focus: ["comb", "sol", "ylab"],
      },
      {
        say: "Negative four is a sign slip in the subtraction. Twenty-eight is seven y, and seven is just the coefficient.",
        strike: [1, 2, 3],
      },
    ],
    answer: "Y equals four. One subtraction and x was gone.",
    trap: { point: "Trap: dropping signs when subtracting", say: "Subtracting an equation means subtracting every term. Minus a negative becomes plus, on both sides." },
    recap: { point: "Match a term, cancel it", say: "Line the equations up, add or subtract to cancel one variable, and solve for the one that's left." },
    tint: { y: "green", "28": "green", "4": "green" },
    scene: {
      x: [-2, 7],
      y: [-2, 9],
      objects: [
        { id: "axes", kind: "axes", xStep: 2, yStep: 4 },
        { id: "L1", kind: "fn", y: "(16 - 3x)/2", color: "yellow" },
        { id: "L2", kind: "fn", y: "(3x + 12)/5", color: "blue" },
        { id: "comb", kind: "fn", y: "(16 + 12t - (3 - 3t)x)/(2 + 5t)", params: { t: 0 }, color: "green" },
        { id: "sol", kind: "point", at: [2.667, 4], color: "green" },
        { id: "ylab", kind: "text", at: [5.8, 3.1], text: "y = 4", color: "green" },
      ],
    },
  },
  {
    subskillId: "m-systems",
    pattern: "Determining the Number of Solutions Without Fully Solving",
    example: 1,
    hook: "How many solutions? You don't have to solve anything. Just compare the lines.",
    idea: [
      { point: "Different slopes → exactly one", say: "Different slopes means the lines cross once. Exactly one solution." },
      { point: "Same slope, different b → none", say: "Same slope with different intercepts means parallel lines. They never meet, so no solution." },
      { point: "Same slope, same b → infinite", say: "Same slope and same intercept means it's the same line twice. Every point on it works." },
    ],
    steps: [
      {
        say: "Two x plus y equals five, and four x plus two y equals ten. Put both in y equals m x plus b form.",
        highlight: ["2x + y = 5", "4x + 2y = 10"],
        work: "2x + y = 5",
      },
      {
        say: "First one: subtract two x. Y equals negative two x plus five. Here's its line.",
        work: "y = −2x + 5",
        note: "−2x both sides",
        draw: ["L1"],
        focus: ["L1"],
      },
      {
        say: "Now the second one. Four x plus two y equals ten.",
        work: "4x + 2y = 10",
        note: "second equation",
        focus: ["L1"],
      },
      {
        say: "Subtract four x first. Two y equals negative four x plus ten.",
        work: "2y = −4x + 10",
        note: "−4x both sides",
        focus: ["L1"],
      },
      {
        say: "Divide by two. Y equals negative two x plus five. Same slope, same intercept. It lands right on the first line.",
        work: "y = −2x + 5",
        note: "÷2 both sides",
        draw: ["L2", "p1", "p2", "p3"],
        focus: ["L1", "L2", "p1", "p2", "p3"],
      },
      {
        say: "No solution needs different intercepts. Exactly one needs different slopes. And it can be determined: we just did it.",
        strike: [1, 2, 3],
        focus: ["L1", "L2", "p1", "p2", "p3"],
      },
    ],
    answer: "Infinitely many. It's one line written two ways, so every point on it works.",
    trap: { point: "Trap: comparing before converting", say: "Two equations can look different and still be the same line. Put both in the same form before you compare." },
    recap: { point: "Compare slopes, then intercepts", say: "Different slopes, one solution. Same slope, different intercept, none. Same slope and intercept, infinitely many." },
    tint: { "2x": "yellow", "5": "yellow", "4x": "blue", "10": "blue", "2y": "blue" },
    scene: {
      x: [-1, 4],
      y: [-2, 7],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 2 },
        { id: "L1", kind: "fn", y: "-2x + 5", color: "yellow" },
        { id: "L2", kind: "fn", y: "(10 - 4x)/2", color: "blue", dash: true },
        { id: "p1", kind: "point", at: [0.5, 4], color: "white" },
        { id: "p2", kind: "point", at: [1.5, 2], color: "white" },
        { id: "p3", kind: "point", at: [3, -1], color: "white" },
      ],
    },
  },
  {
    subskillId: "m-systems",
    pattern: "Reading the Solution Directly from a Graph",
    example: 2,
    hook: "When the lines are drawn for you, the solution is just the spot where they cross.",
    idea: [
      { point: "Solution = where the lines cross", say: "A system's solution is the point on both lines at once. On a graph, that's the crossing." },
      { point: "Read x first, then y", say: "Read the crossing point's x, then its y, and write them in that order." },
    ],
    steps: [
      {
        say: "One line crosses the y-axis at zero comma six, the other at zero comma one.",
        highlight: ["(0, 6)", "(0, 1)"],
        work: "intercepts: (0, 6), (0, 1)",
        note: "each line on its own",
        draw: ["pA", "pB"],
        focus: ["pA", "pB"],
      },
      {
        say: "Those are where each line meets the y-axis. Neither is on both lines, so neither is the solution.",
        strike: [1, 2],
        focus: ["pA", "pB", "L1", "L2"],
      },
      {
        say: "The two lines cross each other at two comma four. That point is on both lines.",
        highlight: ["cross each other at the point (2, 4)"],
        work: "both lines: (2, 4)",
        note: "where they cross",
        draw: ["sol", "gx", "gy"],
        focus: ["sol", "gx", "gy", "L1", "L2"],
      },
      {
        say: "And six comma one just glues the two intercept values together. It isn't on either line.",
        strike: [3],
        draw: ["fake"],
        focus: ["fake", "L1", "L2"],
      },
    ],
    answer: "Two comma four. The one point both lines share.",
    trap: { point: "Trap: picking an intercept", say: "Each y-intercept belongs to one line only. The solution has to be on both, so it's the crossing." },
    recap: { point: "Find the crossing, read x then y", say: "Find where the lines cross, then read its x and y in order. That's the solution." },
    tint: { "6": "yellow", "1": "blue", "2": "green", "4": "green" },
    scene: {
      x: [-1, 7],
      y: [-1, 8],
      objects: [
        { id: "axes", kind: "axes", xStep: 2, yStep: 2 },
        { id: "L1", kind: "fn", y: "6 - x", color: "yellow" },
        { id: "L2", kind: "fn", y: "1.5x + 1", color: "blue" },
        { id: "pA", kind: "point", at: [0, 6], color: "yellow", label: "(0, 6)" },
        { id: "pB", kind: "point", at: [0, 1], color: "blue", label: "(0, 1)", labelOffset: [14, 22] },
        { id: "gx", kind: "seg", from: [2, 4], to: [2, 0], dash: true, color: "green" },
        { id: "gy", kind: "seg", from: [2, 4], to: [0, 4], dash: true, color: "green" },
        { id: "sol", kind: "point", at: [2, 4], color: "green", label: "(2, 4)", labelOffset: [6, 12] },
        { id: "fake", kind: "point", at: [6, 1], open: true, color: "gray", label: "(6, 1)", labelOffset: [-22, -8] },
      ],
    },
  },
];
