import type { LessonVideoScript } from "../../types";

export const M_TWO_VAR_DATA: LessonVideoScript[] = [
  {
    subskillId: "m-two-var-data",
    pattern: "Choosing the Right Model Shape from a Scatterplot's Pattern",
    example: 1,
    hook: "Lots of scatterplots go up and to the right. What matters is how they go up.",
    idea: [
      { point: "Constant rate → linear", say: "If the points climb by the same amount each step, that's a straight line. Linear." },
      { point: "Rate keeps growing → exponential", say: "If each jump is bigger than the last, and it never turns around, that's exponential." },
      { point: "One peak or low point → quadratic", say: "If the points rise and then fall, or fall and then rise, that's a quadratic." },
    ],
    steps: [
      {
        say: "Slow at first, then steeper and steeper. Look at the yellow jumps: each one is bigger than the one before.",
        highlight: ["rising slowly at first, then increasingly steeply", "each step producing a noticeably bigger jump than the last"],
        draw: ["r0", "r1", "r2", "r3", "r4", "r5"],
        focus: ["r0", "r1", "r2", "r3", "r4", "r5"],
      },
      {
        say: "The rate itself is changing, so no straight line can follow it. See the points sag away from this one. Linear's out.",
        work: "growing jumps → not linear",
        note: "rate isn't constant",
        draw: ["lin"],
        focus: ["lin", "e0", "e1", "e2", "e3", "e4", "e5", "e6"],
        strike: [1],
      },
      {
        say: "A quadratic can curve up too, but it turns around at its vertex. Run this one backward and it climbs again. These points never do.",
        work: "never turns → not quadratic",
        note: "no vertex",
        hide: ["lin"],
        draw: ["quad", "vtx"],
        focus: ["quad", "vtx"],
        strike: [2],
      },
      {
        say: "Speeding up in one direction forever, flattening out to the left, is exactly exponential growth. So one of these models definitely fits.",
        work: "keeps accelerating → exponential",
        note: "match the shape",
        hide: ["quad", "vtx"],
        draw: ["expo"],
        focus: ["expo", "e0", "e1", "e2", "e3", "e4", "e5", "e6"],
        strike: [3],
      },
    ],
    answer: "Exponential. The rate of increase keeps increasing.",
    trap: { point: "Trap: \"curves up\" means quadratic", say: "Curving isn't enough. Ask whether it ever turns around. Quadratics do. Exponentials just keep speeding up." },
    recap: { point: "Watch how the rate behaves", say: "Steady rate, linear. Growing rate, exponential. A rate that flips direction, quadratic." },
    tint: { exponential: "blue", linear: "gray", quadratic: "orange", jumps: "yellow" },
    scene: {
      x: [-3.6, 6.8],
      y: [-1.5, 29.5],
      objects: [
        { id: "axes", kind: "axes", numbers: false, grid: false },
        { id: "e0", kind: "point", at: [0, 2.0] },
        { id: "e1", kind: "point", at: [1, 3.0] },
        { id: "e2", kind: "point", at: [2, 4.5] },
        { id: "e3", kind: "point", at: [3, 6.75] },
        { id: "e4", kind: "point", at: [4, 10.125] },
        { id: "e5", kind: "point", at: [5, 15.188] },
        { id: "e6", kind: "point", at: [6, 22.781] },
        { id: "r0", kind: "seg", from: [1, 2.0], to: [1, 3.0], width: 3, color: "yellow" },
        { id: "r1", kind: "seg", from: [2, 3.0], to: [2, 4.5], width: 3, color: "yellow" },
        { id: "r2", kind: "seg", from: [3, 4.5], to: [3, 6.75], width: 3, color: "yellow" },
        { id: "r3", kind: "seg", from: [4, 6.75], to: [4, 10.125], width: 3, color: "yellow" },
        { id: "r4", kind: "seg", from: [5, 10.125], to: [5, 15.188], width: 3, color: "yellow" },
        { id: "r5", kind: "seg", from: [6, 15.188], to: [6, 22.781], width: 3, color: "yellow" },
        { id: "lin", kind: "fn", y: "2 + 3.47*x", domain: [-0.6, 5.8], dash: true, color: "gray", label: "linear" },
        { id: "quad", kind: "fn", y: "0.628*x^2 - 0.3*x + 2", domain: [-3.5, 5.8], color: "orange", label: "quadratic" },
        { id: "vtx", kind: "point", at: [0.24, 1.96], color: "orange", label: "vertex", labelOffset: [-58, 22] },
        { id: "expo", kind: "fn", y: "2*(1.5)^x", domain: [-3.5, 5.8], color: "blue", label: "exponential" },
      ],
    },
  },
  {
    subskillId: "m-two-var-data",
    pattern: "Using a Line of Best Fit",
    example: 0,
    hook: "When there's a line drawn through the dots, work from the line, not the dots.",
    idea: [
      { point: "Sign first: falling line, negative slope", say: "Start with the sign. A line that falls from left to right has a negative slope." },
      { point: "Intercept: where it meets the y-axis", say: "The y-intercept is where the line meets the y-axis, at x equals zero." },
      { point: "Slope = change in y / change in x", say: "Then slope is the change in y over the change in x, read off the axis numbers." },
    ],
    steps: [
      {
        say: "Snow melting over the days after a storm. Work from the line, not the dots. It falls, so the slope is negative.",
        highlight: ["line of best fit"],
        focus: ["fit"],
      },
      {
        say: "The line meets the y-axis at twenty-four inches, and hits zero on day twelve. Rise over run.",
        work: "slope = (0 − 24)/(12 − 0)",
        note: "rise over run",
        draw: ["yInt", "xInt", "run", "drop"],
        focus: ["yInt", "xInt", "run", "drop", "fit"],
      },
      {
        say: "It drops twenty-four over a run of twelve. Negative twenty-four over twelve is negative two: about two inches a day.",
        work: "slope = −2",
        note: "−24 ÷ 12",
        focus: ["run", "drop"],
      },
      {
        say: "Put the slope and intercept together. Y equals negative two x plus twenty-four.",
        work: "y = −2x + 24",
        note: "b = 24",
        focus: ["yInt", "fit"],
      },
      {
        say: "A positive two would make the line rise. And twelve is where it meets the x-axis, not the y-axis.",
        strike: [0, 1],
        focus: ["xInt"],
      },
      {
        say: "Negative one half is the slope upside down: the change in x over the change in y.",
        strike: [3],
      },
    ],
    answer: "Y equals negative two x plus twenty-four. Right sign, right intercept, right steepness.",
    trap: { point: "Trap: slope upside down", say: "Slope is change in y over change in x. Flip it and you get the wrong steepness." },
    recap: { point: "Sign, then intercept, then steepness", say: "Check the sign, find where it meets the y-axis, then work out rise over run." },
    tint: { "24": "yellow", "2": "orange", "12": "blue" },
    scene: {
      x: [-1.6, 14.6],
      y: [-2.5, 28.5],
      objects: [
        { id: "axes", kind: "axes", xStep: 3, yStep: 8 },
        { id: "s0", kind: "point", at: [1, 23.5], color: "gray" },
        { id: "s1", kind: "point", at: [2, 18], color: "gray" },
        { id: "s2", kind: "point", at: [3, 20], color: "gray" },
        { id: "s3", kind: "point", at: [4, 15], color: "gray" },
        { id: "s4", kind: "point", at: [5, 14.5], color: "gray" },
        { id: "s5", kind: "point", at: [6, 13.5], color: "gray" },
        { id: "s6", kind: "point", at: [7, 7.5], color: "gray" },
        { id: "s7", kind: "point", at: [8, 9], color: "gray" },
        { id: "s8", kind: "point", at: [9, 5], color: "gray" },
        { id: "s9", kind: "point", at: [10, 4.5], color: "gray" },
        { id: "s10", kind: "point", at: [11, 1.5], color: "gray" },
        { id: "fit", kind: "fn", y: "-2*x + 24", domain: [0, 12], color: "white" },
        { id: "yInt", kind: "point", at: [0, 24], color: "yellow", label: "24" },
        { id: "xInt", kind: "point", at: [12, 0], color: "blue" },
        { id: "run", kind: "seg", from: [0, 24], to: [12, 24], dash: true, color: "blue", label: "run 12" },
        { id: "drop", kind: "seg", from: [12, 24], to: [12, 0], color: "orange", label: "−24", labelOffset: [36, 0] },
      ],
    },
  },
  {
    subskillId: "m-two-var-data",
    pattern: "Interpreting Residuals",
    example: 1,
    hook: "A residual tells you how far off the model was, and in which direction.",
    idea: [
      { point: "Residual = actual − predicted", say: "A residual is the actual value minus the predicted value. Always in that order." },
      { point: "Negative → came in below prediction", say: "A negative residual means the real value came in below what the model predicted." },
    ],
    steps: [
      {
        say: "The model's line predicted twenty-four centimeters at six weeks. The plant actually measured nineteen, below the line.",
        highlight: ["predicts a plant will be 24 cm tall", "actual measured height is 19 cm"],
        focus: ["pred", "act", "model"],
      },
      {
        say: "Residual is actual minus predicted. Always in that order.",
        work: "residual = actual − predicted",
        note: "always this order",
        focus: ["act", "pred"],
      },
      {
        say: "Actual is nineteen, predicted is twenty-four.",
        work: "residual = 19 − 24",
        note: "plug in",
        focus: ["act", "pred"],
      },
      {
        say: "Nineteen minus twenty-four is negative five. The arrow from the line to the real plant points down: it grew less than expected.",
        work: "residual = −5",
        note: "points down: below",
        draw: ["res"],
        focus: ["res", "act"],
      },
      {
        say: "The positive fives flip the subtraction. And negative five meaning grew more gets the sign backwards.",
        strike: [1, 2, 3],
      },
    ],
    answer: "Negative five, and the plant grew less than predicted.",
    trap: { point: "Trap: predicted minus actual", say: "Subtract in the wrong order and the sign flips, and so does the meaning." },
    recap: { point: "Actual minus predicted, then read the sign", say: "Actual minus predicted. Positive means above the model, negative means below it." },
    tint: { actual: "blue", "19": "blue", predicted: "yellow", "24": "yellow", "−5": "orange" },
    scene: {
      x: [3, 8],
      y: [13, 28],
      objects: [
        { id: "axes", kind: "axes", xStep: 1, yStep: 5 },
        { id: "model", kind: "fn", y: "4*x", domain: [3.3, 6.7], color: "gray", label: "model" },
        { id: "pred", kind: "point", at: [6, 24], color: "yellow", label: "24", labelOffset: [-36, 4] },
        { id: "act", kind: "point", at: [6, 19], color: "blue", label: "19", labelOffset: [-36, 8] },
        { id: "res", kind: "seg", from: [6, 23.4], to: [6, 19.6], width: 3, arrow: true, color: "orange", label: "−5", labelOffset: [32, 0] },
      ],
    },
  },
];
